In [1]:
import pandas as pd

## 1. Bagdol last 30 days data cleaning

In [2]:
df30 = pd.read_csv('Bagdol_last30days.csv')
df30

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,6230465,Bagdol,pm1,13.3,µg/m³,2026-09-12T01:00:00Z,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
1,6230465,Bagdol,pm1,20.1,µg/m³,2026-09-12T02:00:00Z,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
2,6230465,Bagdol,pm1,22.0,µg/m³,2026-09-12T03:00:00Z,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
3,6230465,Bagdol,pm1,23.0,µg/m³,2026-09-12T04:00:00Z,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
4,6230465,Bagdol,pm1,17.6,µg/m³,2026-09-12T05:00:00Z,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3590,6230465,Bagdol,um003,1279.0,particles/cm³,2026-10-11T20:00:00Z,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
3591,6230465,Bagdol,um003,1193.0,particles/cm³,2026-10-11T21:00:00Z,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
3592,6230465,Bagdol,um003,1174.0,particles/cm³,2026-10-11T22:00:00Z,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
3593,6230465,Bagdol,um003,1218.0,particles/cm³,2026-10-11T23:00:00Z,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
3594,6230465,Bagdol,um003,1276.0,particles/cm³,2026-10-12T00:00:00Z,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient

In [3]:
df30.info()

<class 'pandas.DataFrame'>
RangeIndex: 3595 entries, 0 to 3594
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    3595 non-null   int64
 1   location_name  3595 non-null   str
 2   parameter      3595 non-null   str
 3   value          3595 non-null   float64
 4   unit           3595 non-null   str
 5   datetimeUtc    3595 non-null   str
 6   datetimeLocal  3595 non-null   str
 7   timezone       3595 non-null   str
 8   latitude       3595 non-null   float64
 9   longitude      3595 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     3595 non-null   str
 14  provider       3595 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 750.7 KB

In [25]:
df30.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      3595
isMobile         3595
isMonitor        3595
owner_name          0
provider            0
dtype: int64

In [39]:
df30.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [38]:
cleaned =df30.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6230465,Bagdol,pm1,13.3,µg/m³,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
1,6230465,Bagdol,pm1,20.1,µg/m³,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
2,6230465,Bagdol,pm1,22.0,µg/m³,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
3,6230465,Bagdol,pm1,23.0,µg/m³,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
4,6230465,Bagdol,pm1,17.6,µg/m³,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
3590,6230465,Bagdol,um003,1279.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
3591,6230465,Bagdol,um003,1193.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
3592,6230465,Bagdol,um003,1174.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
3593,6230465,Bagdol,um003,1218.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
3594,6230465,Bagdol,um003,1276.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient

In [7]:
df30['parameter'].unique()

<ArrowStringArray>
['pm1', 'pm25', 'relativehumidity', 'temperature', 'um003']
Length: 5, dtype: str

In [8]:
cleaned = cleaned[cleaned['parameter']=='pm25']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
719,6230465,Bagdol,pm25,23.8,µg/m³,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
720,6230465,Bagdol,pm25,29.0,µg/m³,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
721,6230465,Bagdol,pm25,32.0,µg/m³,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
722,6230465,Bagdol,pm25,33.3,µg/m³,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
723,6230465,Bagdol,pm25,25.3,µg/m³,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
1433,6230465,Bagdol,pm25,33.6,µg/m³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
1434,6230465,Bagdol,pm25,31.9,µg/m³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
1435,6230465,Bagdol,pm25,32.0,µg/m³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
1436,6230465,Bagdol,pm25,32.4,µg/m³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
1437,6230465,Bagdol,pm25,33.0,µg/m³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient

In [9]:
cleaned['datetimeLocal'].unique()

<ArrowStringArray>
['2026-09-12T06:45:00+05:45', '2026-09-12T07:45:00+05:45',
 '2026-09-12T08:45:00+05:45', '2026-09-12T09:45:00+05:45',
 '2026-09-12T10:45:00+05:45', '2026-09-12T11:45:00+05:45',
 '2026-09-12T12:45:00+05:45', '2026-09-12T13:45:00+05:45',
 '2026-09-12T14:45:00+05:45', '2026-09-12T15:45:00+05:45',
 ...
 '2026-10-11T20:45:00+05:45', '2026-10-11T21:45:00+05:45',
 '2026-10-11T22:45:00+05:45', '2026-10-11T23:45:00+05:45',
 '2026-10-12T00:45:00+05:45', '2026-10-12T01:45:00+05:45',
 '2026-10-12T02:45:00+05:45', '2026-10-12T03:45:00+05:45',
 '2026-10-12T04:45:00+05:45', '2026-10-12T05:45:00+05:45']
Length: 719, dtype: str

In [10]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
719,6230465,Bagdol,pm25,23.8,µg/m³,2026-09-12 06:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-09-12,06:45:00
720,6230465,Bagdol,pm25,29.0,µg/m³,2026-09-12 07:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-09-12,07:45:00
721,6230465,Bagdol,pm25,32.0,µg/m³,2026-09-12 08:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-09-12,08:45:00
722,6230465,Bagdol,pm25,33.3,µg/m³,2026-09-12 09:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-09-12,09:45:00
723,6230465,Bagdol,pm25,25.3,µg/m³,2026-09-12 10:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-09-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1433,6230465,Bagdol,pm25,33.6,µg/m³,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-12,01:45:00
1434,6230465,Bagdol,pm25,31.9,µg/m³,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-12,02:45:00
1435,6230465,Bagdol,pm25,32.0,µg/m³,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-12,03:45:00
1436,6230465,Bagdol,pm25,32.4,µg/m³,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-12,04:45:00
1437,6230465,Bagdol,pm25,33.0,µg/m³,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-12,05:45:00

In [11]:
# cleaned['value'].unique
cleaned['unit'].unique

<bound method Series.unique of 719     µg/m³
720     µg/m³
721     µg/m³
722     µg/m³
723     µg/m³
        ...
1433    µg/m³
1434    µg/m³
1435    µg/m³
1436    µg/m³
1437    µg/m³
Name: unit, Length: 719, dtype: str>

In [35]:
cleaned.to_csv('cleaned_bagdolLast30days.csv', index=False)

## 2. Bagdol last 7 Days Cleaning

In [13]:
df7 = pd.read_csv('Bagdol_last1week.csv')
df7

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,6230465,Bagdol,pm1,30.4,µg/m³,2026-10-05T01:00:00Z,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
1,6230465,Bagdol,pm1,30.3,µg/m³,2026-10-05T02:00:00Z,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
2,6230465,Bagdol,pm1,31.0,µg/m³,2026-10-05T03:00:00Z,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
3,6230465,Bagdol,pm1,30.8,µg/m³,2026-10-05T04:00:00Z,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
4,6230465,Bagdol,pm1,27.2,µg/m³,2026-10-05T05:00:00Z,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
835,6230465,Bagdol,um003,1279.0,particles/cm³,2026-10-11T20:00:00Z,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
836,6230465,Bagdol,um003,1193.0,particles/cm³,2026-10-11T21:00:00Z,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
837,6230465,Bagdol,um003,1174.0,particles/cm³,2026-10-11T22:00:00Z,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
838,6230465,Bagdol,um003,1218.0,particles/cm³,2026-10-11T23:00:00Z,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
839,6230465,Bagdol,um003,1276.0,particles/cm³,2026-10-12T00:00:00Z,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient

In [14]:
df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 840 entries, 0 to 839
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    840 non-null    int64
 1   location_name  840 non-null    str
 2   parameter      840 non-null    str
 3   value          840 non-null    float64
 4   unit           840 non-null    str
 5   datetimeUtc    840 non-null    str
 6   datetimeLocal  840 non-null    str
 7   timezone       840 non-null    str
 8   latitude       840 non-null    float64
 9   longitude      840 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     840 non-null    str
 14  provider       840 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 175.5 KB

In [15]:
df7.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      840
isMobile         840
isMonitor        840
owner_name         0
provider           0
dtype: int64

In [16]:
df7.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [17]:
cleaned1 =df7.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6230465,Bagdol,pm1,30.4,µg/m³,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
1,6230465,Bagdol,pm1,30.3,µg/m³,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
2,6230465,Bagdol,pm1,31.0,µg/m³,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
3,6230465,Bagdol,pm1,30.8,µg/m³,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
4,6230465,Bagdol,pm1,27.2,µg/m³,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
835,6230465,Bagdol,um003,1279.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
836,6230465,Bagdol,um003,1193.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
837,6230465,Bagdol,um003,1174.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
838,6230465,Bagdol,um003,1218.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
839,6230465,Bagdol,um003,1276.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient

In [18]:
cleaned1['parameter'].unique()

<ArrowStringArray>
['pm1', 'pm25', 'relativehumidity', 'temperature', 'um003']
Length: 5, dtype: str

In [19]:
cleaned1['datetimeLocal'].unique()

<ArrowStringArray>
['2026-10-05T06:45:00+05:45', '2026-10-05T07:45:00+05:45',
 '2026-10-05T08:45:00+05:45', '2026-10-05T09:45:00+05:45',
 '2026-10-05T10:45:00+05:45', '2026-10-05T11:45:00+05:45',
 '2026-10-05T12:45:00+05:45', '2026-10-05T13:45:00+05:45',
 '2026-10-05T14:45:00+05:45', '2026-10-05T15:45:00+05:45',
 ...
 '2026-10-11T20:45:00+05:45', '2026-10-11T21:45:00+05:45',
 '2026-10-11T22:45:00+05:45', '2026-10-11T23:45:00+05:45',
 '2026-10-12T00:45:00+05:45', '2026-10-12T01:45:00+05:45',
 '2026-10-12T02:45:00+05:45', '2026-10-12T03:45:00+05:45',
 '2026-10-12T04:45:00+05:45', '2026-10-12T05:45:00+05:45']
Length: 168, dtype: str

In [20]:
# seperating date and time
cleaned1['datetimeLocal']=pd.to_datetime(cleaned1['datetimeLocal'])
cleaned1['date']=cleaned1['datetimeLocal'].dt.date
cleaned1['time']=cleaned1['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
0,6230465,Bagdol,pm1,30.4,µg/m³,2026-10-05 06:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-05,06:45:00
1,6230465,Bagdol,pm1,30.3,µg/m³,2026-10-05 07:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-05,07:45:00
2,6230465,Bagdol,pm1,31.0,µg/m³,2026-10-05 08:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-05,08:45:00
3,6230465,Bagdol,pm1,30.8,µg/m³,2026-10-05 09:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-05,09:45:00
4,6230465,Bagdol,pm1,27.2,µg/m³,2026-10-05 10:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-05,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
835,6230465,Bagdol,um003,1279.0,particles/cm³,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-12,01:45:00
836,6230465,Bagdol,um003,1193.0,particles/cm³,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-12,02:45:00
837,6230465,Bagdol,um003,1174.0,particles/cm³,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-12,03:45:00
838,6230465,Bagdol,um003,1218.0,particles/cm³,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-12,04:45:00
839,6230465,Bagdol,um003,1276.0,particles/cm³,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-12,05:45:00

In [21]:
# cleaned['value'].unique
cleaned1['unit'].unique

<bound method Series.unique of 0              µg/m³
1              µg/m³
2              µg/m³
3              µg/m³
4              µg/m³
           ...
835    particles/cm³
836    particles/cm³
837    particles/cm³
838    particles/cm³
839    particles/cm³
Name: unit, Length: 840, dtype: str>

In [22]:
cleaned1.to_csv('cleaned_bagdolLast7days.csv', index=False)

## 3. Bagdol Last 24 hours data cleaning

In [26]:
df24 = pd.read_csv('Bagdol_last24hours.csv')
df24.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    120 non-null    int64
 1   location_name  120 non-null    str
 2   parameter      120 non-null    str
 3   value          120 non-null    float64
 4   unit           120 non-null    str
 5   datetimeUtc    120 non-null    str
 6   datetimeLocal  120 non-null    str
 7   timezone       120 non-null    str
 8   latitude       120 non-null    float64
 9   longitude      120 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     120 non-null    str
 14  provider       120 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 25.2 KB

In [27]:
df24.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      120
isMobile         120
isMonitor        120
owner_name         0
provider           0
dtype: int64

In [29]:
cleaned2 = df24.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6230465,Bagdol,pm1,18.3,µg/m³,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
1,6230465,Bagdol,pm1,20.9,µg/m³,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
2,6230465,Bagdol,pm1,22.5,µg/m³,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
3,6230465,Bagdol,pm1,28.1,µg/m³,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
4,6230465,Bagdol,pm1,26.8,µg/m³,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
115,6230465,Bagdol,um003,1279.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
116,6230465,Bagdol,um003,1193.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
117,6230465,Bagdol,um003,1174.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
118,6230465,Bagdol,um003,1218.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
119,6230465,Bagdol,um003,1276.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient

In [32]:
# df24['parameter'].unique()
cleaned2 = cleaned2[cleaned2['parameter']=='pm25']
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
24,6230465,Bagdol,pm25,28.8,µg/m³,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
25,6230465,Bagdol,pm25,31.9,µg/m³,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
26,6230465,Bagdol,pm25,34.0,µg/m³,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
27,6230465,Bagdol,pm25,42.5,µg/m³,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
28,6230465,Bagdol,pm25,40.7,µg/m³,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
29,6230465,Bagdol,pm25,32.2,µg/m³,2026-10-11T11:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
30,6230465,Bagdol,pm25,25.1,µg/m³,2026-10-11T12:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
31,6230465,Bagdol,pm25,20.8,µg/m³,2026-10-11T13:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
32,6230465,Bagdol,pm25,24.6,µg/m³,2026-10-11T14:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
33,6230465,Bagdol,pm25,27.7,µg/m³,2026-10-11T15:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
34,6230465,Bagdol,pm25,26.2,µg/m³,2026-10-11T16:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
35,6230465,Bagdol,pm25,24.6,µg/m³,2026-10-11T17:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
36,6230465,Bagdol,pm25,30.1,µg/m³,2026-10-11T18:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
37,6230465,Bagdol,pm25,37.5,µg/m³,2026-10-11T19:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
38,6230465,Bagdol,pm25,35.8,µg/m³,2026-10-11T20:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
39,6230465,Bagdol,pm25,33.7,µg/m³,2026-10-11T21:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
40,6230465,Bagdol,pm25,34.0,µg/m³,2026-10-11T22:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
41,6230465,Bagdol,pm25,33.3,µg/m³,2026-10-11T23:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
42,6230465,Bagdol,pm25,34.3,µg/m³,2026-10-12T00:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
43,6230465,Bagdol,pm25,33.6,µg/m³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
44,6230465,Bagdol,pm25,31.9,µg/m³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
45,6230465,Bagdol,pm25,32.0,µg/m³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
46,6230465,Bagdol,pm25,32.4,µg/m³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
47,6230465,Bagdol,pm25,33.0,µg/m³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient

In [34]:
# cleaned2['datetimeLocal'].unique()

# seperating date and time
cleaned2['datetimeLocal']=pd.to_datetime(cleaned2['datetimeLocal'])
cleaned2['date']=cleaned2['datetimeLocal'].dt.date
cleaned2['time']=cleaned2['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
24,6230465,Bagdol,pm25,28.8,µg/m³,2026-10-11 06:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,06:45:00
25,6230465,Bagdol,pm25,31.9,µg/m³,2026-10-11 07:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,07:45:00
26,6230465,Bagdol,pm25,34.0,µg/m³,2026-10-11 08:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,08:45:00
27,6230465,Bagdol,pm25,42.5,µg/m³,2026-10-11 09:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,09:45:00
28,6230465,Bagdol,pm25,40.7,µg/m³,2026-10-11 10:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,10:45:00
29,6230465,Bagdol,pm25,32.2,µg/m³,2026-10-11 11:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,11:45:00
30,6230465,Bagdol,pm25,25.1,µg/m³,2026-10-11 12:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,12:45:00
31,6230465,Bagdol,pm25,20.8,µg/m³,2026-10-11 13:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,13:45:00
32,6230465,Bagdol,pm25,24.6,µg/m³,2026-10-11 14:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,14:45:00
33,6230465,Bagdol,pm25,27.7,µg/m³,2026-10-11 15:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,15:45:00
34,6230465,Bagdol,pm25,26.2,µg/m³,2026-10-11 16:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,16:45:00
35,6230465,Bagdol,pm25,24.6,µg/m³,2026-10-11 17:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,17:45:00
36,6230465,Bagdol,pm25,30.1,µg/m³,2026-10-11 18:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,18:45:00
37,6230465,Bagdol,pm25,37.5,µg/m³,2026-10-11 19:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,19:45:00
38,6230465,Bagdol,pm25,35.8,µg/m³,2026-10-11 20:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,20:45:00
39,6230465,Bagdol,pm25,33.7,µg/m³,2026-10-11 21:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,21:45:00
40,6230465,Bagdol,pm25,34.0,µg/m³,2026-10-11 22:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,22:45:00
41,6230465,Bagdol,pm25,33.3,µg/m³,2026-10-11 23:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-11,23:45:00
42,6230465,Bagdol,pm25,34.3,µg/m³,2026-10-12 00:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-12,00:45:00
43,6230465,Bagdol,pm25,33.6,µg/m³,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-12,01:45:00
44,6230465,Bagdol,pm25,31.9,µg/m³,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-12,02:45:00
45,6230465,Bagdol,pm25,32.0,µg/m³,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-12,03:45:00
46,6230465,Bagdol,pm25,32.4,µg/m³,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-12,04:45:00
47,6230465,Bagdol,pm25,33.0,µg/m³,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient,2026-10-12,05:45:00

In [36]:
cleaned2.to_csv('cleaned_bagdolLast24hours.csv', index=False)