In [2]:
import pandas as pd

## 1. Gothatar last 365 days data cleaning

In [17]:
df365 = pd.read_csv('Gothatar_last365days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.2 MB

In [18]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [19]:
df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [20]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6071242,Gothatar (SC-12) - GD Labs,pm1,22.887972,µg/m³,2025-10-12T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1,6071242,Gothatar (SC-12) - GD Labs,pm1,25.466125,µg/m³,2025-10-12T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2,6071242,Gothatar (SC-12) - GD Labs,pm1,24.403958,µg/m³,2025-10-12T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3,6071242,Gothatar (SC-12) - GD Labs,pm1,28.085181,µg/m³,2025-10-12T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4,6071242,Gothatar (SC-12) - GD Labs,pm1,21.547167,µg/m³,2025-10-12T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,6071242,Gothatar (SC-12) - GD Labs,um003,2552.810514,particles/cm³,2025-11-23T23:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4996,6071242,Gothatar (SC-12) - GD Labs,um003,2491.397500,particles/cm³,2025-11-24T00:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4997,6071242,Gothatar (SC-12) - GD Labs,um003,2088.775334,particles/cm³,2025-11-24T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4998,6071242,Gothatar (SC-12) - GD Labs,um003,2226.969670,particles/cm³,2025-11-24T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4999,6071242,Gothatar (SC-12) - GD Labs,um003,2102.525332,particles/cm³,2025-11-24T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [21]:
cleaned = cleaned[cleaned['parameter']=='pm25']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
1000,6071242,Gothatar (SC-12) - GD Labs,pm25,38.636417,µg/m³,2025-10-12T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1001,6071242,Gothatar (SC-12) - GD Labs,pm25,41.426667,µg/m³,2025-10-12T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1002,6071242,Gothatar (SC-12) - GD Labs,pm25,40.298959,µg/m³,2025-10-12T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1003,6071242,Gothatar (SC-12) - GD Labs,pm25,45.891291,µg/m³,2025-10-12T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1004,6071242,Gothatar (SC-12) - GD Labs,pm25,35.801584,µg/m³,2025-10-12T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
1995,6071242,Gothatar (SC-12) - GD Labs,pm25,57.847666,µg/m³,2025-11-23T23:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1996,6071242,Gothatar (SC-12) - GD Labs,pm25,56.817000,µg/m³,2025-11-24T00:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1997,6071242,Gothatar (SC-12) - GD Labs,pm25,49.019500,µg/m³,2025-11-24T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1998,6071242,Gothatar (SC-12) - GD Labs,pm25,51.608167,µg/m³,2025-11-24T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1999,6071242,Gothatar (SC-12) - GD Labs,pm25,49.325500,µg/m³,2025-11-24T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [22]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
1000,6071242,Gothatar (SC-12) - GD Labs,pm25,38.636417,µg/m³,2025-10-12 06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-10-12,06:45:00
1001,6071242,Gothatar (SC-12) - GD Labs,pm25,41.426667,µg/m³,2025-10-12 07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-10-12,07:45:00
1002,6071242,Gothatar (SC-12) - GD Labs,pm25,40.298959,µg/m³,2025-10-12 08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-10-12,08:45:00
1003,6071242,Gothatar (SC-12) - GD Labs,pm25,45.891291,µg/m³,2025-10-12 09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-10-12,09:45:00
1004,6071242,Gothatar (SC-12) - GD Labs,pm25,35.801584,µg/m³,2025-10-12 10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-10-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,6071242,Gothatar (SC-12) - GD Labs,pm25,57.847666,µg/m³,2025-11-23 23:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-11-23,23:45:00
1996,6071242,Gothatar (SC-12) - GD Labs,pm25,56.817000,µg/m³,2025-11-24 00:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-11-24,00:45:00
1997,6071242,Gothatar (SC-12) - GD Labs,pm25,49.019500,µg/m³,2025-11-24 01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-11-24,01:45:00
1998,6071242,Gothatar (SC-12) - GD Labs,pm25,51.608167,µg/m³,2025-11-24 02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-11-24,02:45:00
1999,6071242,Gothatar (SC-12) - GD Labs,pm25,49.325500,µg/m³,2025-11-24 03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-11-24,03:45:00

In [23]:
cleaned.to_csv('cleaned_GothatarLast365days.csv', index=False)

## 2. Gothatar last 30 days data cleaning

In [24]:
df30 = pd.read_csv('Gothatar_last1month.csv')
df30

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,6071242,Gothatar (SC-12) - GD Labs,pm1,5.3,µg/m³,2026-09-12T01:00:00Z,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
1,6071242,Gothatar (SC-12) - GD Labs,pm1,7.9,µg/m³,2026-09-12T02:00:00Z,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
2,6071242,Gothatar (SC-12) - GD Labs,pm1,7.6,µg/m³,2026-09-12T03:00:00Z,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3,6071242,Gothatar (SC-12) - GD Labs,pm1,7.0,µg/m³,2026-09-12T04:00:00Z,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4,6071242,Gothatar (SC-12) - GD Labs,pm1,6.1,µg/m³,2026-09-12T05:00:00Z,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3565,6071242,Gothatar (SC-12) - GD Labs,um003,1221.0,particles/cm³,2026-10-11T20:00:00Z,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3566,6071242,Gothatar (SC-12) - GD Labs,um003,939.0,particles/cm³,2026-10-11T21:00:00Z,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3567,6071242,Gothatar (SC-12) - GD Labs,um003,990.0,particles/cm³,2026-10-11T22:00:00Z,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3568,6071242,Gothatar (SC-12) - GD Labs,um003,1207.0,particles/cm³,2026-10-11T23:00:00Z,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3569,6071242,Gothatar (SC-12) - GD Labs,um003,1007.0,particles/cm³,2026-10-12T00:00:00Z,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient

In [25]:
df30.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      3570
isMobile         3570
isMonitor        3570
owner_name          0
provider            0
dtype: int64

In [26]:
df30.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [27]:
cleaned1 =df30.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6071242,Gothatar (SC-12) - GD Labs,pm1,5.3,µg/m³,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1,6071242,Gothatar (SC-12) - GD Labs,pm1,7.9,µg/m³,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2,6071242,Gothatar (SC-12) - GD Labs,pm1,7.6,µg/m³,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3,6071242,Gothatar (SC-12) - GD Labs,pm1,7.0,µg/m³,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4,6071242,Gothatar (SC-12) - GD Labs,pm1,6.1,µg/m³,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
3565,6071242,Gothatar (SC-12) - GD Labs,um003,1221.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3566,6071242,Gothatar (SC-12) - GD Labs,um003,939.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3567,6071242,Gothatar (SC-12) - GD Labs,um003,990.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3568,6071242,Gothatar (SC-12) - GD Labs,um003,1207.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3569,6071242,Gothatar (SC-12) - GD Labs,um003,1007.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [28]:
cleaned1 = cleaned1[cleaned1['parameter']=='pm25']
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
714,6071242,Gothatar (SC-12) - GD Labs,pm25,10.6,µg/m³,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
715,6071242,Gothatar (SC-12) - GD Labs,pm25,16.3,µg/m³,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
716,6071242,Gothatar (SC-12) - GD Labs,pm25,17.7,µg/m³,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
717,6071242,Gothatar (SC-12) - GD Labs,pm25,15.8,µg/m³,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
718,6071242,Gothatar (SC-12) - GD Labs,pm25,12.1,µg/m³,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
1423,6071242,Gothatar (SC-12) - GD Labs,pm25,33.4,µg/m³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1424,6071242,Gothatar (SC-12) - GD Labs,pm25,27.7,µg/m³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1425,6071242,Gothatar (SC-12) - GD Labs,pm25,29.3,µg/m³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1426,6071242,Gothatar (SC-12) - GD Labs,pm25,33.5,µg/m³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1427,6071242,Gothatar (SC-12) - GD Labs,pm25,29.7,µg/m³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [29]:
# seperating date and time
cleaned1['datetimeLocal']=pd.to_datetime(cleaned1['datetimeLocal'])
cleaned1['date']=cleaned1['datetimeLocal'].dt.date
cleaned1['time']=cleaned1['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
714,6071242,Gothatar (SC-12) - GD Labs,pm25,10.6,µg/m³,2026-09-12 06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-09-12,06:45:00
715,6071242,Gothatar (SC-12) - GD Labs,pm25,16.3,µg/m³,2026-09-12 07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-09-12,07:45:00
716,6071242,Gothatar (SC-12) - GD Labs,pm25,17.7,µg/m³,2026-09-12 08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-09-12,08:45:00
717,6071242,Gothatar (SC-12) - GD Labs,pm25,15.8,µg/m³,2026-09-12 09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-09-12,09:45:00
718,6071242,Gothatar (SC-12) - GD Labs,pm25,12.1,µg/m³,2026-09-12 10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-09-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1423,6071242,Gothatar (SC-12) - GD Labs,pm25,33.4,µg/m³,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
1424,6071242,Gothatar (SC-12) - GD Labs,pm25,27.7,µg/m³,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
1425,6071242,Gothatar (SC-12) - GD Labs,pm25,29.3,µg/m³,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
1426,6071242,Gothatar (SC-12) - GD Labs,pm25,33.5,µg/m³,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
1427,6071242,Gothatar (SC-12) - GD Labs,pm25,29.7,µg/m³,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [30]:
cleaned1.to_csv('cleaned_GothatarLast30days.csv', index=False)

## 3. Gothatar last 7 Days data Cleaning

In [31]:
df7 = pd.read_csv('Gothatar_last1week.csv')
df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 810 entries, 0 to 809
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    810 non-null    int64
 1   location_name  810 non-null    str
 2   parameter      810 non-null    str
 3   value          810 non-null    float64
 4   unit           810 non-null    str
 5   datetimeUtc    810 non-null    str
 6   datetimeLocal  810 non-null    str
 7   timezone       810 non-null    str
 8   latitude       810 non-null    float64
 9   longitude      810 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     810 non-null    str
 14  provider       810 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 207.2 KB

In [32]:
df7.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      810
isMobile         810
isMonitor        810
owner_name         0
provider           0
dtype: int64

In [33]:
cleaned2 =df7.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6071242,Gothatar (SC-12) - GD Labs,pm1,28.3,µg/m³,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1,6071242,Gothatar (SC-12) - GD Labs,pm1,31.0,µg/m³,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2,6071242,Gothatar (SC-12) - GD Labs,pm1,34.7,µg/m³,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3,6071242,Gothatar (SC-12) - GD Labs,pm1,35.6,µg/m³,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4,6071242,Gothatar (SC-12) - GD Labs,pm1,27.0,µg/m³,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
805,6071242,Gothatar (SC-12) - GD Labs,um003,1221.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
806,6071242,Gothatar (SC-12) - GD Labs,um003,939.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
807,6071242,Gothatar (SC-12) - GD Labs,um003,990.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
808,6071242,Gothatar (SC-12) - GD Labs,um003,1207.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
809,6071242,Gothatar (SC-12) - GD Labs,um003,1007.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [35]:
cleaned2 = cleaned2[cleaned2['parameter']=='pm25']
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
162,6071242,Gothatar (SC-12) - GD Labs,pm25,45.2,µg/m³,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
163,6071242,Gothatar (SC-12) - GD Labs,pm25,49.5,µg/m³,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
164,6071242,Gothatar (SC-12) - GD Labs,pm25,55.8,µg/m³,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
165,6071242,Gothatar (SC-12) - GD Labs,pm25,58.0,µg/m³,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
166,6071242,Gothatar (SC-12) - GD Labs,pm25,42.9,µg/m³,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
319,6071242,Gothatar (SC-12) - GD Labs,pm25,33.4,µg/m³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
320,6071242,Gothatar (SC-12) - GD Labs,pm25,27.7,µg/m³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
321,6071242,Gothatar (SC-12) - GD Labs,pm25,29.3,µg/m³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
322,6071242,Gothatar (SC-12) - GD Labs,pm25,33.5,µg/m³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
323,6071242,Gothatar (SC-12) - GD Labs,pm25,29.7,µg/m³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [36]:
# seperating date and time
cleaned2['datetimeLocal']=pd.to_datetime(cleaned2['datetimeLocal'])
cleaned2['date']=cleaned2['datetimeLocal'].dt.date
cleaned2['time']=cleaned2['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
162,6071242,Gothatar (SC-12) - GD Labs,pm25,45.2,µg/m³,2026-10-05 06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-05,06:45:00
163,6071242,Gothatar (SC-12) - GD Labs,pm25,49.5,µg/m³,2026-10-05 07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-05,07:45:00
164,6071242,Gothatar (SC-12) - GD Labs,pm25,55.8,µg/m³,2026-10-05 08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-05,08:45:00
165,6071242,Gothatar (SC-12) - GD Labs,pm25,58.0,µg/m³,2026-10-05 09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-05,09:45:00
166,6071242,Gothatar (SC-12) - GD Labs,pm25,42.9,µg/m³,2026-10-05 10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-05,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,6071242,Gothatar (SC-12) - GD Labs,pm25,33.4,µg/m³,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
320,6071242,Gothatar (SC-12) - GD Labs,pm25,27.7,µg/m³,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
321,6071242,Gothatar (SC-12) - GD Labs,pm25,29.3,µg/m³,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
322,6071242,Gothatar (SC-12) - GD Labs,pm25,33.5,µg/m³,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
323,6071242,Gothatar (SC-12) - GD Labs,pm25,29.7,µg/m³,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [37]:
cleaned2.to_csv('cleaned_GothatarLast7days.csv', index=False)

## 4. Gothatar Last 24 hours data Cleaning

In [38]:
df24 = pd.read_csv('Gothatar_last24hours.csv')
df24.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    120 non-null    int64
 1   location_name  120 non-null    str
 2   parameter      120 non-null    str
 3   value          120 non-null    float64
 4   unit           120 non-null    str
 5   datetimeUtc    120 non-null    str
 6   datetimeLocal  120 non-null    str
 7   timezone       120 non-null    str
 8   latitude       120 non-null    float64
 9   longitude      120 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     120 non-null    str
 14  provider       120 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 30.8 KB

In [39]:
df24.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      120
isMobile         120
isMonitor        120
owner_name         0
provider           0
dtype: int64

In [40]:
cleaned3 = df24.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6071242,Gothatar (SC-12) - GD Labs,pm1,17.7,µg/m³,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1,6071242,Gothatar (SC-12) - GD Labs,pm1,24.4,µg/m³,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2,6071242,Gothatar (SC-12) - GD Labs,pm1,22.5,µg/m³,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3,6071242,Gothatar (SC-12) - GD Labs,pm1,20.0,µg/m³,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4,6071242,Gothatar (SC-12) - GD Labs,pm1,18.4,µg/m³,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
115,6071242,Gothatar (SC-12) - GD Labs,um003,1221.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
116,6071242,Gothatar (SC-12) - GD Labs,um003,939.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
117,6071242,Gothatar (SC-12) - GD Labs,um003,990.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
118,6071242,Gothatar (SC-12) - GD Labs,um003,1207.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
119,6071242,Gothatar (SC-12) - GD Labs,um003,1007.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [41]:
# df24['parameter'].unique()
cleaned3 = cleaned3[cleaned3['parameter']=='pm25']
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
24,6071242,Gothatar (SC-12) - GD Labs,pm25,28.1,µg/m³,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
25,6071242,Gothatar (SC-12) - GD Labs,pm25,37.1,µg/m³,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
26,6071242,Gothatar (SC-12) - GD Labs,pm25,34.5,µg/m³,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
27,6071242,Gothatar (SC-12) - GD Labs,pm25,30.6,µg/m³,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
28,6071242,Gothatar (SC-12) - GD Labs,pm25,29.6,µg/m³,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
29,6071242,Gothatar (SC-12) - GD Labs,pm25,26.9,µg/m³,2026-10-11T11:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
30,6071242,Gothatar (SC-12) - GD Labs,pm25,32.5,µg/m³,2026-10-11T12:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
31,6071242,Gothatar (SC-12) - GD Labs,pm25,28.0,µg/m³,2026-10-11T13:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
32,6071242,Gothatar (SC-12) - GD Labs,pm25,24.7,µg/m³,2026-10-11T14:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
33,6071242,Gothatar (SC-12) - GD Labs,pm25,21.4,µg/m³,2026-10-11T15:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
34,6071242,Gothatar (SC-12) - GD Labs,pm25,22.1,µg/m³,2026-10-11T16:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
35,6071242,Gothatar (SC-12) - GD Labs,pm25,25.4,µg/m³,2026-10-11T17:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
36,6071242,Gothatar (SC-12) - GD Labs,pm25,28.7,µg/m³,2026-10-11T18:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
37,6071242,Gothatar (SC-12) - GD Labs,pm25,36.9,µg/m³,2026-10-11T19:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
38,6071242,Gothatar (SC-12) - GD Labs,pm25,47.3,µg/m³,2026-10-11T20:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
39,6071242,Gothatar (SC-12) - GD Labs,pm25,42.7,µg/m³,2026-10-11T21:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
40,6071242,Gothatar (SC-12) - GD Labs,pm25,38.4,µg/m³,2026-10-11T22:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
41,6071242,Gothatar (SC-12) - GD Labs,pm25,30.4,µg/m³,2026-10-11T23:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
42,6071242,Gothatar (SC-12) - GD Labs,pm25,30.3,µg/m³,2026-10-12T00:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
43,6071242,Gothatar (SC-12) - GD Labs,pm25,33.4,µg/m³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
44,6071242,Gothatar (SC-12) - GD Labs,pm25,27.7,µg/m³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
45,6071242,Gothatar (SC-12) - GD Labs,pm25,29.3,µg/m³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
46,6071242,Gothatar (SC-12) - GD Labs,pm25,33.5,µg/m³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
47,6071242,Gothatar (SC-12) - GD Labs,pm25,29.7,µg/m³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [42]:

# seperating date and time
cleaned3['datetimeLocal']=pd.to_datetime(cleaned3['datetimeLocal'])
cleaned3['date']=cleaned3['datetimeLocal'].dt.date
cleaned3['time']=cleaned3['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
24,6071242,Gothatar (SC-12) - GD Labs,pm25,28.1,µg/m³,2026-10-11 06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,06:45:00
25,6071242,Gothatar (SC-12) - GD Labs,pm25,37.1,µg/m³,2026-10-11 07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,07:45:00
26,6071242,Gothatar (SC-12) - GD Labs,pm25,34.5,µg/m³,2026-10-11 08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,08:45:00
27,6071242,Gothatar (SC-12) - GD Labs,pm25,30.6,µg/m³,2026-10-11 09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,09:45:00
28,6071242,Gothatar (SC-12) - GD Labs,pm25,29.6,µg/m³,2026-10-11 10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,10:45:00
29,6071242,Gothatar (SC-12) - GD Labs,pm25,26.9,µg/m³,2026-10-11 11:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,11:45:00
30,6071242,Gothatar (SC-12) - GD Labs,pm25,32.5,µg/m³,2026-10-11 12:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,12:45:00
31,6071242,Gothatar (SC-12) - GD Labs,pm25,28.0,µg/m³,2026-10-11 13:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,13:45:00
32,6071242,Gothatar (SC-12) - GD Labs,pm25,24.7,µg/m³,2026-10-11 14:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,14:45:00
33,6071242,Gothatar (SC-12) - GD Labs,pm25,21.4,µg/m³,2026-10-11 15:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,15:45:00
34,6071242,Gothatar (SC-12) - GD Labs,pm25,22.1,µg/m³,2026-10-11 16:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,16:45:00
35,6071242,Gothatar (SC-12) - GD Labs,pm25,25.4,µg/m³,2026-10-11 17:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,17:45:00
36,6071242,Gothatar (SC-12) - GD Labs,pm25,28.7,µg/m³,2026-10-11 18:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,18:45:00
37,6071242,Gothatar (SC-12) - GD Labs,pm25,36.9,µg/m³,2026-10-11 19:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,19:45:00
38,6071242,Gothatar (SC-12) - GD Labs,pm25,47.3,µg/m³,2026-10-11 20:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,20:45:00
39,6071242,Gothatar (SC-12) - GD Labs,pm25,42.7,µg/m³,2026-10-11 21:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,21:45:00
40,6071242,Gothatar (SC-12) - GD Labs,pm25,38.4,µg/m³,2026-10-11 22:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,22:45:00
41,6071242,Gothatar (SC-12) - GD Labs,pm25,30.4,µg/m³,2026-10-11 23:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,23:45:00
42,6071242,Gothatar (SC-12) - GD Labs,pm25,30.3,µg/m³,2026-10-12 00:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,00:45:00
43,6071242,Gothatar (SC-12) - GD Labs,pm25,33.4,µg/m³,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
44,6071242,Gothatar (SC-12) - GD Labs,pm25,27.7,µg/m³,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
45,6071242,Gothatar (SC-12) - GD Labs,pm25,29.3,µg/m³,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
46,6071242,Gothatar (SC-12) - GD Labs,pm25,33.5,µg/m³,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
47,6071242,Gothatar (SC-12) - GD Labs,pm25,29.7,µg/m³,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [43]:
cleaned3.to_csv('cleaned_GothatarLast24hours.csv', index=False)