In [1]:
import pandas as pd

## 1. Gothatar last 365 days data cleaning

In [2]:
df365 = pd.read_csv('Gothatar_last365days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.2 MB

In [3]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [4]:
df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [5]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6071242,Gothatar (SC-12) - GD Labs,pm1,22.887972,µg/m³,2025-10-12T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1,6071242,Gothatar (SC-12) - GD Labs,pm1,25.466125,µg/m³,2025-10-12T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2,6071242,Gothatar (SC-12) - GD Labs,pm1,24.403958,µg/m³,2025-10-12T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3,6071242,Gothatar (SC-12) - GD Labs,pm1,28.085181,µg/m³,2025-10-12T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4,6071242,Gothatar (SC-12) - GD Labs,pm1,21.547167,µg/m³,2025-10-12T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,6071242,Gothatar (SC-12) - GD Labs,um003,2552.810514,particles/cm³,2025-11-23T23:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4996,6071242,Gothatar (SC-12) - GD Labs,um003,2491.397500,particles/cm³,2025-11-24T00:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4997,6071242,Gothatar (SC-12) - GD Labs,um003,2088.775334,particles/cm³,2025-11-24T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4998,6071242,Gothatar (SC-12) - GD Labs,um003,2226.969670,particles/cm³,2025-11-24T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4999,6071242,Gothatar (SC-12) - GD Labs,um003,2102.525332,particles/cm³,2025-11-24T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [6]:
# cleaned = cleaned[cleaned['parameter']=='pm25']
# cleaned = cleaned[cleaned['parameter']=='temperature']
cleaned = cleaned[cleaned['parameter']=='relativehumidity']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
2000,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,54.360528,%,2025-10-12T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2001,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,51.080333,%,2025-10-12T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2002,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,42.371125,%,2025-10-12T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2003,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,40.663944,%,2025-10-12T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2004,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,37.478667,%,2025-10-12T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
2995,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,49.635333,%,2025-11-23T23:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2996,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,49.816833,%,2025-11-24T00:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2997,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,49.766833,%,2025-11-24T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2998,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,50.080833,%,2025-11-24T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2999,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,50.190333,%,2025-11-24T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [7]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
2000,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,54.360528,%,2025-10-12 06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-10-12,06:45:00
2001,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,51.080333,%,2025-10-12 07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-10-12,07:45:00
2002,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,42.371125,%,2025-10-12 08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-10-12,08:45:00
2003,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,40.663944,%,2025-10-12 09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-10-12,09:45:00
2004,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,37.478667,%,2025-10-12 10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-10-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,49.635333,%,2025-11-23 23:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-11-23,23:45:00
2996,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,49.816833,%,2025-11-24 00:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-11-24,00:45:00
2997,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,49.766833,%,2025-11-24 01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-11-24,01:45:00
2998,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,50.080833,%,2025-11-24 02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-11-24,02:45:00
2999,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,50.190333,%,2025-11-24 03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-11-24,03:45:00

In [10]:
cleaned.to_csv('cleaned_GothatarLast365days.csv', index=False)

## 2. Gothatar last 30 days data cleaning

In [11]:
df30 = pd.read_csv('Gothatar_last1month.csv')
df30

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,6071242,Gothatar (SC-12) - GD Labs,pm1,5.3,µg/m³,2026-09-12T01:00:00Z,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
1,6071242,Gothatar (SC-12) - GD Labs,pm1,7.9,µg/m³,2026-09-12T02:00:00Z,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
2,6071242,Gothatar (SC-12) - GD Labs,pm1,7.6,µg/m³,2026-09-12T03:00:00Z,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3,6071242,Gothatar (SC-12) - GD Labs,pm1,7.0,µg/m³,2026-09-12T04:00:00Z,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4,6071242,Gothatar (SC-12) - GD Labs,pm1,6.1,µg/m³,2026-09-12T05:00:00Z,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3565,6071242,Gothatar (SC-12) - GD Labs,um003,1221.0,particles/cm³,2026-10-11T20:00:00Z,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3566,6071242,Gothatar (SC-12) - GD Labs,um003,939.0,particles/cm³,2026-10-11T21:00:00Z,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3567,6071242,Gothatar (SC-12) - GD Labs,um003,990.0,particles/cm³,2026-10-11T22:00:00Z,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3568,6071242,Gothatar (SC-12) - GD Labs,um003,1207.0,particles/cm³,2026-10-11T23:00:00Z,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3569,6071242,Gothatar (SC-12) - GD Labs,um003,1007.0,particles/cm³,2026-10-12T00:00:00Z,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient

In [12]:
df30.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      3570
isMobile         3570
isMonitor        3570
owner_name          0
provider            0
dtype: int64

In [13]:
df30.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [14]:
cleaned1 =df30.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6071242,Gothatar (SC-12) - GD Labs,pm1,5.3,µg/m³,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1,6071242,Gothatar (SC-12) - GD Labs,pm1,7.9,µg/m³,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2,6071242,Gothatar (SC-12) - GD Labs,pm1,7.6,µg/m³,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3,6071242,Gothatar (SC-12) - GD Labs,pm1,7.0,µg/m³,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4,6071242,Gothatar (SC-12) - GD Labs,pm1,6.1,µg/m³,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
3565,6071242,Gothatar (SC-12) - GD Labs,um003,1221.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3566,6071242,Gothatar (SC-12) - GD Labs,um003,939.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3567,6071242,Gothatar (SC-12) - GD Labs,um003,990.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3568,6071242,Gothatar (SC-12) - GD Labs,um003,1207.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3569,6071242,Gothatar (SC-12) - GD Labs,um003,1007.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [15]:
cleaned1['parameter'].unique()

<ArrowStringArray>
['pm1', 'pm25', 'relativehumidity', 'temperature', 'um003']
Length: 5, dtype: str

In [16]:
# cleaned1 = cleaned1[cleaned1['parameter']=='pm25']
# cleaned1 = cleaned1[cleaned1['parameter']=='temperature']
cleaned1 = cleaned1[cleaned1['parameter']=='relativehumidity']
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
1428,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,59.0,%,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1429,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,56.0,%,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1430,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,50.0,%,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1431,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,44.0,%,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1432,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,43.0,%,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
2137,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,56.0,%,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2138,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,55.0,%,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2139,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,56.0,%,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2140,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,57.0,%,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2141,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,57.0,%,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [17]:
# seperating date and time
cleaned1['datetimeLocal']=pd.to_datetime(cleaned1['datetimeLocal'])
cleaned1['date']=cleaned1['datetimeLocal'].dt.date
cleaned1['time']=cleaned1['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
1428,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,59.0,%,2026-09-12 06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-09-12,06:45:00
1429,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,56.0,%,2026-09-12 07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-09-12,07:45:00
1430,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,50.0,%,2026-09-12 08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-09-12,08:45:00
1431,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,44.0,%,2026-09-12 09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-09-12,09:45:00
1432,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,43.0,%,2026-09-12 10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-09-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2137,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,56.0,%,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
2138,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,55.0,%,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
2139,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,56.0,%,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
2140,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,57.0,%,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
2141,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,57.0,%,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [18]:
cleaned1.to_csv('cleaned_GothatarLast30days.csv', index=False)

## 3. Gothatar last 7 Days data Cleaning

In [19]:
df7 = pd.read_csv('Gothatar_last1week.csv')
df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 810 entries, 0 to 809
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    810 non-null    int64
 1   location_name  810 non-null    str
 2   parameter      810 non-null    str
 3   value          810 non-null    float64
 4   unit           810 non-null    str
 5   datetimeUtc    810 non-null    str
 6   datetimeLocal  810 non-null    str
 7   timezone       810 non-null    str
 8   latitude       810 non-null    float64
 9   longitude      810 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     810 non-null    str
 14  provider       810 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 207.2 KB

In [20]:
df7.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      810
isMobile         810
isMonitor        810
owner_name         0
provider           0
dtype: int64

In [21]:
cleaned2 =df7.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6071242,Gothatar (SC-12) - GD Labs,pm1,28.3,µg/m³,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1,6071242,Gothatar (SC-12) - GD Labs,pm1,31.0,µg/m³,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2,6071242,Gothatar (SC-12) - GD Labs,pm1,34.7,µg/m³,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3,6071242,Gothatar (SC-12) - GD Labs,pm1,35.6,µg/m³,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4,6071242,Gothatar (SC-12) - GD Labs,pm1,27.0,µg/m³,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
805,6071242,Gothatar (SC-12) - GD Labs,um003,1221.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
806,6071242,Gothatar (SC-12) - GD Labs,um003,939.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
807,6071242,Gothatar (SC-12) - GD Labs,um003,990.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
808,6071242,Gothatar (SC-12) - GD Labs,um003,1207.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
809,6071242,Gothatar (SC-12) - GD Labs,um003,1007.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [22]:
# cleaned2 = cleaned2[cleaned2['parameter']=='pm25']
# cleaned2 = cleaned2[cleaned2['parameter']=='temperature']
cleaned2 = cleaned2[cleaned2['parameter']=='relativehumidity']
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
324,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,56.0,%,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
325,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,53.0,%,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
326,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,52.0,%,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
327,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,51.0,%,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
328,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,44.0,%,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
481,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,56.0,%,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
482,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,55.0,%,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
483,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,56.0,%,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
484,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,57.0,%,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
485,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,57.0,%,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [23]:
# seperating date and time
cleaned2['datetimeLocal']=pd.to_datetime(cleaned2['datetimeLocal'])
cleaned2['date']=cleaned2['datetimeLocal'].dt.date
cleaned2['time']=cleaned2['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
324,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,56.0,%,2026-10-05 06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-05,06:45:00
325,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,53.0,%,2026-10-05 07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-05,07:45:00
326,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,52.0,%,2026-10-05 08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-05,08:45:00
327,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,51.0,%,2026-10-05 09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-05,09:45:00
328,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,44.0,%,2026-10-05 10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-05,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,56.0,%,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
482,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,55.0,%,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
483,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,56.0,%,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
484,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,57.0,%,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
485,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,57.0,%,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [24]:
cleaned2.to_csv('cleaned_GothatarLast7days.csv', index=False)

## 4. Gothatar Last 24 hours data Cleaning

In [25]:
df24 = pd.read_csv('Gothatar_last24hours.csv')
df24.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    120 non-null    int64
 1   location_name  120 non-null    str
 2   parameter      120 non-null    str
 3   value          120 non-null    float64
 4   unit           120 non-null    str
 5   datetimeUtc    120 non-null    str
 6   datetimeLocal  120 non-null    str
 7   timezone       120 non-null    str
 8   latitude       120 non-null    float64
 9   longitude      120 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     120 non-null    str
 14  provider       120 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 30.8 KB

In [26]:
df24.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      120
isMobile         120
isMonitor        120
owner_name         0
provider           0
dtype: int64

In [27]:
cleaned3 = df24.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6071242,Gothatar (SC-12) - GD Labs,pm1,17.7,µg/m³,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1,6071242,Gothatar (SC-12) - GD Labs,pm1,24.4,µg/m³,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2,6071242,Gothatar (SC-12) - GD Labs,pm1,22.5,µg/m³,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3,6071242,Gothatar (SC-12) - GD Labs,pm1,20.0,µg/m³,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4,6071242,Gothatar (SC-12) - GD Labs,pm1,18.4,µg/m³,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
115,6071242,Gothatar (SC-12) - GD Labs,um003,1221.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
116,6071242,Gothatar (SC-12) - GD Labs,um003,939.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
117,6071242,Gothatar (SC-12) - GD Labs,um003,990.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
118,6071242,Gothatar (SC-12) - GD Labs,um003,1207.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
119,6071242,Gothatar (SC-12) - GD Labs,um003,1007.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [28]:
# df24['parameter'].unique()
# cleaned3 = cleaned3[cleaned3['parameter']=='pm25']
# cleaned3 = cleaned3[cleaned3['parameter']=='temperature']
cleaned3 = cleaned3[cleaned3['parameter']=='relativehumidity']
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
48,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,58.0,%,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
49,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,57.0,%,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
50,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,52.0,%,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
51,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,49.0,%,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
52,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,44.0,%,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
53,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,39.0,%,2026-10-11T11:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
54,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,40.0,%,2026-10-11T12:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
55,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,41.0,%,2026-10-11T13:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
56,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,42.0,%,2026-10-11T14:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
57,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,42.0,%,2026-10-11T15:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
58,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,41.0,%,2026-10-11T16:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
59,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,44.0,%,2026-10-11T17:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
60,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,49.0,%,2026-10-11T18:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
61,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,52.0,%,2026-10-11T19:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
62,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,54.0,%,2026-10-11T20:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
63,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,55.0,%,2026-10-11T21:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
64,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,55.0,%,2026-10-11T22:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
65,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,54.0,%,2026-10-11T23:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
66,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,55.0,%,2026-10-12T00:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
67,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,56.0,%,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
68,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,55.0,%,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
69,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,56.0,%,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
70,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,57.0,%,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
71,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,57.0,%,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [29]:

# seperating date and time
cleaned3['datetimeLocal']=pd.to_datetime(cleaned3['datetimeLocal'])
cleaned3['date']=cleaned3['datetimeLocal'].dt.date
cleaned3['time']=cleaned3['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
48,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,58.0,%,2026-10-11 06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,06:45:00
49,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,57.0,%,2026-10-11 07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,07:45:00
50,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,52.0,%,2026-10-11 08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,08:45:00
51,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,49.0,%,2026-10-11 09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,09:45:00
52,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,44.0,%,2026-10-11 10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,10:45:00
53,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,39.0,%,2026-10-11 11:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,11:45:00
54,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,40.0,%,2026-10-11 12:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,12:45:00
55,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,41.0,%,2026-10-11 13:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,13:45:00
56,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,42.0,%,2026-10-11 14:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,14:45:00
57,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,42.0,%,2026-10-11 15:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,15:45:00
58,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,41.0,%,2026-10-11 16:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,16:45:00
59,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,44.0,%,2026-10-11 17:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,17:45:00
60,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,49.0,%,2026-10-11 18:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,18:45:00
61,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,52.0,%,2026-10-11 19:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,19:45:00
62,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,54.0,%,2026-10-11 20:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,20:45:00
63,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,55.0,%,2026-10-11 21:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,21:45:00
64,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,55.0,%,2026-10-11 22:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,22:45:00
65,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,54.0,%,2026-10-11 23:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-11,23:45:00
66,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,55.0,%,2026-10-12 00:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,00:45:00
67,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,56.0,%,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
68,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,55.0,%,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
69,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,56.0,%,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
70,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,57.0,%,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
71,6071242,Gothatar (SC-12) - GD Labs,relativehumidity,57.0,%,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [31]:
cleaned3.to_csv('cleaned_GothatarLast24hours.csv', index=False)