In [1]:
import pandas as pd

## 1. Gothatar last 365 days data cleaning

In [4]:
df365 = pd.read_csv('Gothatar_last365days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.2 MB

In [5]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [6]:
df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [7]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6071242,Gothatar (SC-12) - GD Labs,pm1,22.887972,µg/m³,2025-10-12T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1,6071242,Gothatar (SC-12) - GD Labs,pm1,25.466125,µg/m³,2025-10-12T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
2,6071242,Gothatar (SC-12) - GD Labs,pm1,24.403958,µg/m³,2025-10-12T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
3,6071242,Gothatar (SC-12) - GD Labs,pm1,28.085181,µg/m³,2025-10-12T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4,6071242,Gothatar (SC-12) - GD Labs,pm1,21.547167,µg/m³,2025-10-12T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,6071242,Gothatar (SC-12) - GD Labs,um003,2552.810514,particles/cm³,2025-11-23T23:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4996,6071242,Gothatar (SC-12) - GD Labs,um003,2491.397500,particles/cm³,2025-11-24T00:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4997,6071242,Gothatar (SC-12) - GD Labs,um003,2088.775334,particles/cm³,2025-11-24T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4998,6071242,Gothatar (SC-12) - GD Labs,um003,2226.969670,particles/cm³,2025-11-24T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
4999,6071242,Gothatar (SC-12) - GD Labs,um003,2102.525332,particles/cm³,2025-11-24T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [8]:
cleaned = cleaned[cleaned['parameter']=='pm25']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
1000,6071242,Gothatar (SC-12) - GD Labs,pm25,38.636417,µg/m³,2025-10-12T06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1001,6071242,Gothatar (SC-12) - GD Labs,pm25,41.426667,µg/m³,2025-10-12T07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1002,6071242,Gothatar (SC-12) - GD Labs,pm25,40.298959,µg/m³,2025-10-12T08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1003,6071242,Gothatar (SC-12) - GD Labs,pm25,45.891291,µg/m³,2025-10-12T09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1004,6071242,Gothatar (SC-12) - GD Labs,pm25,35.801584,µg/m³,2025-10-12T10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
1995,6071242,Gothatar (SC-12) - GD Labs,pm25,57.847666,µg/m³,2025-11-23T23:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1996,6071242,Gothatar (SC-12) - GD Labs,pm25,56.817000,µg/m³,2025-11-24T00:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1997,6071242,Gothatar (SC-12) - GD Labs,pm25,49.019500,µg/m³,2025-11-24T01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1998,6071242,Gothatar (SC-12) - GD Labs,pm25,51.608167,µg/m³,2025-11-24T02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient
1999,6071242,Gothatar (SC-12) - GD Labs,pm25,49.325500,µg/m³,2025-11-24T03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient

In [9]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
1000,6071242,Gothatar (SC-12) - GD Labs,pm25,38.636417,µg/m³,2025-10-12 06:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-10-12,06:45:00
1001,6071242,Gothatar (SC-12) - GD Labs,pm25,41.426667,µg/m³,2025-10-12 07:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-10-12,07:45:00
1002,6071242,Gothatar (SC-12) - GD Labs,pm25,40.298959,µg/m³,2025-10-12 08:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-10-12,08:45:00
1003,6071242,Gothatar (SC-12) - GD Labs,pm25,45.891291,µg/m³,2025-10-12 09:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-10-12,09:45:00
1004,6071242,Gothatar (SC-12) - GD Labs,pm25,35.801584,µg/m³,2025-10-12 10:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-10-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,6071242,Gothatar (SC-12) - GD Labs,pm25,57.847666,µg/m³,2025-11-23 23:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-11-23,23:45:00
1996,6071242,Gothatar (SC-12) - GD Labs,pm25,56.817000,µg/m³,2025-11-24 00:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-11-24,00:45:00
1997,6071242,Gothatar (SC-12) - GD Labs,pm25,49.019500,µg/m³,2025-11-24 01:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-11-24,01:45:00
1998,6071242,Gothatar (SC-12) - GD Labs,pm25,51.608167,µg/m³,2025-11-24 02:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-11-24,02:45:00
1999,6071242,Gothatar (SC-12) - GD Labs,pm25,49.325500,µg/m³,2025-11-24 03:45:00+05:45,Asia/Kathmandu,27.710911,85.380372,Green Decision Labs and Research,AirGradient,2025-11-24,03:45:00

In [10]:
cleaned.to_csv('cleaned_GothatarLast365days.csv', index=False)