In [1]:
import pandas as pd

## 1. Handigaun last 365 days data cleaning

In [2]:
df365 = pd.read_csv('Handigaun_last365days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.1 MB

In [3]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [4]:
df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [5]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,2848864,"Dabali, Handigaun",pm1,35.375694,µg/m³,2025-10-12T06:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1,2848864,"Dabali, Handigaun",pm1,36.312987,µg/m³,2025-10-12T07:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
2,2848864,"Dabali, Handigaun",pm1,26.454127,µg/m³,2025-10-12T08:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
3,2848864,"Dabali, Handigaun",pm1,29.551948,µg/m³,2025-10-12T09:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
4,2848864,"Dabali, Handigaun",pm1,23.263343,µg/m³,2025-10-12T10:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,2848864,"Dabali, Handigaun",um003,6945.656250,particles/cm³,2025-11-25T17:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
4996,2848864,"Dabali, Handigaun",um003,6480.934524,particles/cm³,2025-11-25T18:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
4997,2848864,"Dabali, Handigaun",um003,7145.914286,particles/cm³,2025-11-25T19:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
4998,2848864,"Dabali, Handigaun",um003,10071.276786,particles/cm³,2025-11-25T20:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
4999,2848864,"Dabali, Handigaun",um003,7244.398268,particles/cm³,2025-11-25T21:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient

In [6]:
cleaned = cleaned[cleaned['parameter']=='pm25']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
1000,2848864,"Dabali, Handigaun",pm25,56.245883,µg/m³,2025-10-12T06:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1001,2848864,"Dabali, Handigaun",pm25,57.654112,µg/m³,2025-10-12T07:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1002,2848864,"Dabali, Handigaun",pm25,42.654445,µg/m³,2025-10-12T08:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1003,2848864,"Dabali, Handigaun",pm25,46.807793,µg/m³,2025-10-12T09:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1004,2848864,"Dabali, Handigaun",pm25,37.498016,µg/m³,2025-10-12T10:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
1995,2848864,"Dabali, Handigaun",pm25,46.697024,µg/m³,2025-11-25T17:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1996,2848864,"Dabali, Handigaun",pm25,44.546131,µg/m³,2025-11-25T18:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1997,2848864,"Dabali, Handigaun",pm25,47.059048,µg/m³,2025-11-25T19:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1998,2848864,"Dabali, Handigaun",pm25,60.145833,µg/m³,2025-11-25T20:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1999,2848864,"Dabali, Handigaun",pm25,46.983550,µg/m³,2025-11-25T21:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient

In [7]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
1000,2848864,"Dabali, Handigaun",pm25,56.245883,µg/m³,2025-10-12 06:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-10-12,06:45:00
1001,2848864,"Dabali, Handigaun",pm25,57.654112,µg/m³,2025-10-12 07:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-10-12,07:45:00
1002,2848864,"Dabali, Handigaun",pm25,42.654445,µg/m³,2025-10-12 08:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-10-12,08:45:00
1003,2848864,"Dabali, Handigaun",pm25,46.807793,µg/m³,2025-10-12 09:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-10-12,09:45:00
1004,2848864,"Dabali, Handigaun",pm25,37.498016,µg/m³,2025-10-12 10:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-10-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2848864,"Dabali, Handigaun",pm25,46.697024,µg/m³,2025-11-25 17:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-11-25,17:45:00
1996,2848864,"Dabali, Handigaun",pm25,44.546131,µg/m³,2025-11-25 18:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-11-25,18:45:00
1997,2848864,"Dabali, Handigaun",pm25,47.059048,µg/m³,2025-11-25 19:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-11-25,19:45:00
1998,2848864,"Dabali, Handigaun",pm25,60.145833,µg/m³,2025-11-25 20:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-11-25,20:45:00
1999,2848864,"Dabali, Handigaun",pm25,46.983550,µg/m³,2025-11-25 21:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-11-25,21:45:00

In [8]:
cleaned.to_csv('cleaned_HandigaunLast365days.csv', index=False)

## 2. Handigaun last 30 days data cleaning

In [9]:
df30 = pd.read_csv('Handigaun_last30days.csv')
df30

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,2848864,"Dabali, Handigaun",pm25,22.3,µg/m³,2026-09-12T01:00:00Z,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,NaN,NaN,NaN,Unknown Person,AirGradient
1,2848864,"Dabali, Handigaun",pm25,28.5,µg/m³,2026-09-12T02:00:00Z,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,NaN,NaN,NaN,Unknown Person,AirGradient
2,2848864,"Dabali, Handigaun",pm25,19.1,µg/m³,2026-09-12T03:00:00Z,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,NaN,NaN,NaN,Unknown Person,AirGradient
3,2848864,"Dabali, Handigaun",pm25,17.4,µg/m³,2026-09-12T04:00:00Z,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,NaN,NaN,NaN,Unknown Person,AirGradient
4,2848864,"Dabali, Handigaun",pm25,20.4,µg/m³,2026-09-12T05:00:00Z,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,NaN,NaN,NaN,Unknown Person,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2499,2848864,"Dabali, Handigaun",um003,4114.0,particles/cm³,2026-10-11T20:00:00Z,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,NaN,NaN,NaN,Unknown Person,AirGradient
2500,2848864,"Dabali, Handigaun",um003,3952.0,particles/cm³,2026-10-11T21:00:00Z,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,NaN,NaN,NaN,Unknown Person,AirGradient
2501,2848864,"Dabali, Handigaun",um003,4163.0,particles/cm³,2026-10-11T22:00:00Z,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,NaN,NaN,NaN,Unknown Person,AirGradient
2502,2848864,"Dabali, Handigaun",um003,3892.0,particles/cm³,2026-10-11T23:00:00Z,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,NaN,NaN,NaN,Unknown Person,AirGradient
2503,2848864,"Dabali, Handigaun",um003,4651.0,particles/cm³,2026-10-12T00:00:00Z,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,NaN,NaN,NaN,Unknown Person,AirGradient

In [10]:
df30.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      2504
isMobile         2504
isMonitor        2504
owner_name          0
provider            0
dtype: int64

In [11]:
df30.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [12]:
cleaned1 =df30.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,2848864,"Dabali, Handigaun",pm25,22.3,µg/m³,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1,2848864,"Dabali, Handigaun",pm25,28.5,µg/m³,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
2,2848864,"Dabali, Handigaun",pm25,19.1,µg/m³,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
3,2848864,"Dabali, Handigaun",pm25,17.4,µg/m³,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
4,2848864,"Dabali, Handigaun",pm25,20.4,µg/m³,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
2499,2848864,"Dabali, Handigaun",um003,4114.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
2500,2848864,"Dabali, Handigaun",um003,3952.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
2501,2848864,"Dabali, Handigaun",um003,4163.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
2502,2848864,"Dabali, Handigaun",um003,3892.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
2503,2848864,"Dabali, Handigaun",um003,4651.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient

In [13]:
cleaned1 = cleaned1[cleaned1['parameter']=='pm25']
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,2848864,"Dabali, Handigaun",pm25,22.3,µg/m³,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1,2848864,"Dabali, Handigaun",pm25,28.5,µg/m³,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
2,2848864,"Dabali, Handigaun",pm25,19.1,µg/m³,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
3,2848864,"Dabali, Handigaun",pm25,17.4,µg/m³,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
4,2848864,"Dabali, Handigaun",pm25,20.4,µg/m³,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
621,2848864,"Dabali, Handigaun",pm25,32.2,µg/m³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
622,2848864,"Dabali, Handigaun",pm25,31.8,µg/m³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
623,2848864,"Dabali, Handigaun",pm25,32.7,µg/m³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
624,2848864,"Dabali, Handigaun",pm25,31.4,µg/m³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
625,2848864,"Dabali, Handigaun",pm25,34.8,µg/m³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient

In [14]:
# seperating date and time
cleaned1['datetimeLocal']=pd.to_datetime(cleaned1['datetimeLocal'])
cleaned1['date']=cleaned1['datetimeLocal'].dt.date
cleaned1['time']=cleaned1['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
0,2848864,"Dabali, Handigaun",pm25,22.3,µg/m³,2026-09-12 06:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-09-12,06:45:00
1,2848864,"Dabali, Handigaun",pm25,28.5,µg/m³,2026-09-12 07:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-09-12,07:45:00
2,2848864,"Dabali, Handigaun",pm25,19.1,µg/m³,2026-09-12 08:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-09-12,08:45:00
3,2848864,"Dabali, Handigaun",pm25,17.4,µg/m³,2026-09-12 09:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-09-12,09:45:00
4,2848864,"Dabali, Handigaun",pm25,20.4,µg/m³,2026-09-12 10:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-09-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,2848864,"Dabali, Handigaun",pm25,32.2,µg/m³,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-12,01:45:00
622,2848864,"Dabali, Handigaun",pm25,31.8,µg/m³,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-12,02:45:00
623,2848864,"Dabali, Handigaun",pm25,32.7,µg/m³,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-12,03:45:00
624,2848864,"Dabali, Handigaun",pm25,31.4,µg/m³,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-12,04:45:00
625,2848864,"Dabali, Handigaun",pm25,34.8,µg/m³,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-12,05:45:00

In [15]:
cleaned1.to_csv('cleaned_HandigaunLast30days.csv', index=False)

## 3. Handigaun last 7 Days data Cleaning

In [16]:
df7 = pd.read_csv('Handigaun_last1week.csv')
df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    672 non-null    int64
 1   location_name  672 non-null    str
 2   parameter      672 non-null    str
 3   value          672 non-null    float64
 4   unit           672 non-null    str
 5   datetimeUtc    672 non-null    str
 6   datetimeLocal  672 non-null    str
 7   timezone       672 non-null    str
 8   latitude       672 non-null    float64
 9   longitude      672 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     672 non-null    str
 14  provider       672 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 154.8 KB

In [17]:
df7.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      672
isMobile         672
isMonitor        672
owner_name         0
provider           0
dtype: int64

In [18]:
cleaned2 =df7.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,2848864,"Dabali, Handigaun",pm25,52.5,µg/m³,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1,2848864,"Dabali, Handigaun",pm25,53.0,µg/m³,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
2,2848864,"Dabali, Handigaun",pm25,44.1,µg/m³,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
3,2848864,"Dabali, Handigaun",pm25,42.5,µg/m³,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
4,2848864,"Dabali, Handigaun",pm25,35.0,µg/m³,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
667,2848864,"Dabali, Handigaun",um003,4114.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
668,2848864,"Dabali, Handigaun",um003,3952.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
669,2848864,"Dabali, Handigaun",um003,4163.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
670,2848864,"Dabali, Handigaun",um003,3892.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
671,2848864,"Dabali, Handigaun",um003,4651.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient

In [19]:
cleaned2 = cleaned2[cleaned2['parameter']=='pm25']
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,2848864,"Dabali, Handigaun",pm25,52.5,µg/m³,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1,2848864,"Dabali, Handigaun",pm25,53.0,µg/m³,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
2,2848864,"Dabali, Handigaun",pm25,44.1,µg/m³,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
3,2848864,"Dabali, Handigaun",pm25,42.5,µg/m³,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
4,2848864,"Dabali, Handigaun",pm25,35.0,µg/m³,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
163,2848864,"Dabali, Handigaun",pm25,32.2,µg/m³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
164,2848864,"Dabali, Handigaun",pm25,31.8,µg/m³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
165,2848864,"Dabali, Handigaun",pm25,32.7,µg/m³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
166,2848864,"Dabali, Handigaun",pm25,31.4,µg/m³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
167,2848864,"Dabali, Handigaun",pm25,34.8,µg/m³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient

In [20]:
# seperating date and time
cleaned2['datetimeLocal']=pd.to_datetime(cleaned2['datetimeLocal'])
cleaned2['date']=cleaned2['datetimeLocal'].dt.date
cleaned2['time']=cleaned2['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
0,2848864,"Dabali, Handigaun",pm25,52.5,µg/m³,2026-10-05 06:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-05,06:45:00
1,2848864,"Dabali, Handigaun",pm25,53.0,µg/m³,2026-10-05 07:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-05,07:45:00
2,2848864,"Dabali, Handigaun",pm25,44.1,µg/m³,2026-10-05 08:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-05,08:45:00
3,2848864,"Dabali, Handigaun",pm25,42.5,µg/m³,2026-10-05 09:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-05,09:45:00
4,2848864,"Dabali, Handigaun",pm25,35.0,µg/m³,2026-10-05 10:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-05,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,2848864,"Dabali, Handigaun",pm25,32.2,µg/m³,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-12,01:45:00
164,2848864,"Dabali, Handigaun",pm25,31.8,µg/m³,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-12,02:45:00
165,2848864,"Dabali, Handigaun",pm25,32.7,µg/m³,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-12,03:45:00
166,2848864,"Dabali, Handigaun",pm25,31.4,µg/m³,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-12,04:45:00
167,2848864,"Dabali, Handigaun",pm25,34.8,µg/m³,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-12,05:45:00

In [21]:
cleaned2.to_csv('cleaned_HandigaunLast7days.csv', index=False)

## 4. Handigaun Last 24 hours data Cleaning

In [22]:
df24 = pd.read_csv('Handigaun_last24hours.csv')
df24.info()

<class 'pandas.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    96 non-null     int64
 1   location_name  96 non-null     str
 2   parameter      96 non-null     str
 3   value          96 non-null     float64
 4   unit           96 non-null     str
 5   datetimeUtc    96 non-null     str
 6   datetimeLocal  96 non-null     str
 7   timezone       96 non-null     str
 8   latitude       96 non-null     float64
 9   longitude      96 non-null     float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     96 non-null     str
 14  provider       96 non-null     str
dtypes: float64(6), int64(1), str(8)
memory usage: 22.2 KB

In [23]:
df24.isnull().sum()

location_id       0
location_name     0
parameter         0
value             0
unit              0
datetimeUtc       0
datetimeLocal     0
timezone          0
latitude          0
longitude         0
country_iso      96
isMobile         96
isMonitor        96
owner_name        0
provider          0
dtype: int64

In [24]:
cleaned3 = df24.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,2848864,"Dabali, Handigaun",pm25,40.8,µg/m³,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1,2848864,"Dabali, Handigaun",pm25,34.9,µg/m³,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
2,2848864,"Dabali, Handigaun",pm25,36.5,µg/m³,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
3,2848864,"Dabali, Handigaun",pm25,33.4,µg/m³,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
4,2848864,"Dabali, Handigaun",pm25,33.1,µg/m³,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
91,2848864,"Dabali, Handigaun",um003,4114.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
92,2848864,"Dabali, Handigaun",um003,3952.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
93,2848864,"Dabali, Handigaun",um003,4163.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
94,2848864,"Dabali, Handigaun",um003,3892.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
95,2848864,"Dabali, Handigaun",um003,4651.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient

In [25]:
cleaned3 = cleaned3[cleaned3['parameter']=='pm25']
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,2848864,"Dabali, Handigaun",pm25,40.8,µg/m³,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1,2848864,"Dabali, Handigaun",pm25,34.9,µg/m³,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
2,2848864,"Dabali, Handigaun",pm25,36.5,µg/m³,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
3,2848864,"Dabali, Handigaun",pm25,33.4,µg/m³,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
4,2848864,"Dabali, Handigaun",pm25,33.1,µg/m³,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
5,2848864,"Dabali, Handigaun",pm25,28.9,µg/m³,2026-10-11T11:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
6,2848864,"Dabali, Handigaun",pm25,18.5,µg/m³,2026-10-11T12:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
7,2848864,"Dabali, Handigaun",pm25,14.5,µg/m³,2026-10-11T13:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
8,2848864,"Dabali, Handigaun",pm25,15.3,µg/m³,2026-10-11T14:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
9,2848864,"Dabali, Handigaun",pm25,17.1,µg/m³,2026-10-11T15:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
10,2848864,"Dabali, Handigaun",pm25,20.8,µg/m³,2026-10-11T16:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
11,2848864,"Dabali, Handigaun",pm25,24.4,µg/m³,2026-10-11T17:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
12,2848864,"Dabali, Handigaun",pm25,33.4,µg/m³,2026-10-11T18:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
13,2848864,"Dabali, Handigaun",pm25,32.7,µg/m³,2026-10-11T19:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
14,2848864,"Dabali, Handigaun",pm25,29.0,µg/m³,2026-10-11T20:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
15,2848864,"Dabali, Handigaun",pm25,37.6,µg/m³,2026-10-11T21:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
16,2848864,"Dabali, Handigaun",pm25,34.9,µg/m³,2026-10-11T22:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
17,2848864,"Dabali, Handigaun",pm25,27.9,µg/m³,2026-10-11T23:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
18,2848864,"Dabali, Handigaun",pm25,31.1,µg/m³,2026-10-12T00:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
19,2848864,"Dabali, Handigaun",pm25,32.2,µg/m³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
20,2848864,"Dabali, Handigaun",pm25,31.8,µg/m³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
21,2848864,"Dabali, Handigaun",pm25,32.7,µg/m³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
22,2848864,"Dabali, Handigaun",pm25,31.4,µg/m³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
23,2848864,"Dabali, Handigaun",pm25,34.8,µg/m³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient

In [26]:
# seperating date and time
cleaned3['datetimeLocal']=pd.to_datetime(cleaned3['datetimeLocal'])
cleaned3['date']=cleaned3['datetimeLocal'].dt.date
cleaned3['time']=cleaned3['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
0,2848864,"Dabali, Handigaun",pm25,40.8,µg/m³,2026-10-11 06:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,06:45:00
1,2848864,"Dabali, Handigaun",pm25,34.9,µg/m³,2026-10-11 07:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,07:45:00
2,2848864,"Dabali, Handigaun",pm25,36.5,µg/m³,2026-10-11 08:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,08:45:00
3,2848864,"Dabali, Handigaun",pm25,33.4,µg/m³,2026-10-11 09:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,09:45:00
4,2848864,"Dabali, Handigaun",pm25,33.1,µg/m³,2026-10-11 10:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,10:45:00
5,2848864,"Dabali, Handigaun",pm25,28.9,µg/m³,2026-10-11 11:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,11:45:00
6,2848864,"Dabali, Handigaun",pm25,18.5,µg/m³,2026-10-11 12:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,12:45:00
7,2848864,"Dabali, Handigaun",pm25,14.5,µg/m³,2026-10-11 13:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,13:45:00
8,2848864,"Dabali, Handigaun",pm25,15.3,µg/m³,2026-10-11 14:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,14:45:00
9,2848864,"Dabali, Handigaun",pm25,17.1,µg/m³,2026-10-11 15:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,15:45:00
10,2848864,"Dabali, Handigaun",pm25,20.8,µg/m³,2026-10-11 16:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,16:45:00
11,2848864,"Dabali, Handigaun",pm25,24.4,µg/m³,2026-10-11 17:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,17:45:00
12,2848864,"Dabali, Handigaun",pm25,33.4,µg/m³,2026-10-11 18:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,18:45:00
13,2848864,"Dabali, Handigaun",pm25,32.7,µg/m³,2026-10-11 19:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,19:45:00
14,2848864,"Dabali, Handigaun",pm25,29.0,µg/m³,2026-10-11 20:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,20:45:00
15,2848864,"Dabali, Handigaun",pm25,37.6,µg/m³,2026-10-11 21:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,21:45:00
16,2848864,"Dabali, Handigaun",pm25,34.9,µg/m³,2026-10-11 22:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,22:45:00
17,2848864,"Dabali, Handigaun",pm25,27.9,µg/m³,2026-10-11 23:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-11,23:45:00
18,2848864,"Dabali, Handigaun",pm25,31.1,µg/m³,2026-10-12 00:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-12,00:45:00
19,2848864,"Dabali, Handigaun",pm25,32.2,µg/m³,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-12,01:45:00
20,2848864,"Dabali, Handigaun",pm25,31.8,µg/m³,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-12,02:45:00
21,2848864,"Dabali, Handigaun",pm25,32.7,µg/m³,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-12,03:45:00
22,2848864,"Dabali, Handigaun",pm25,31.4,µg/m³,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-12,04:45:00
23,2848864,"Dabali, Handigaun",pm25,34.8,µg/m³,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2026-10-12,05:45:00

In [27]:
cleaned3.to_csv('cleaned_HandigaunLast24hours.csv', index=False)