In [1]:
import pandas as pd

## 1. Handigaun last 365 days data cleaning

In [2]:
df365 = pd.read_csv('Handigaun_last365days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.1 MB

In [3]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [4]:
df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [5]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,2848864,"Dabali, Handigaun",pm1,35.375694,µg/m³,2025-10-12T06:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1,2848864,"Dabali, Handigaun",pm1,36.312987,µg/m³,2025-10-12T07:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
2,2848864,"Dabali, Handigaun",pm1,26.454127,µg/m³,2025-10-12T08:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
3,2848864,"Dabali, Handigaun",pm1,29.551948,µg/m³,2025-10-12T09:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
4,2848864,"Dabali, Handigaun",pm1,23.263343,µg/m³,2025-10-12T10:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,2848864,"Dabali, Handigaun",um003,6945.656250,particles/cm³,2025-11-25T17:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
4996,2848864,"Dabali, Handigaun",um003,6480.934524,particles/cm³,2025-11-25T18:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
4997,2848864,"Dabali, Handigaun",um003,7145.914286,particles/cm³,2025-11-25T19:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
4998,2848864,"Dabali, Handigaun",um003,10071.276786,particles/cm³,2025-11-25T20:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
4999,2848864,"Dabali, Handigaun",um003,7244.398268,particles/cm³,2025-11-25T21:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient

In [6]:
cleaned = cleaned[cleaned['parameter']=='pm25']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
1000,2848864,"Dabali, Handigaun",pm25,56.245883,µg/m³,2025-10-12T06:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1001,2848864,"Dabali, Handigaun",pm25,57.654112,µg/m³,2025-10-12T07:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1002,2848864,"Dabali, Handigaun",pm25,42.654445,µg/m³,2025-10-12T08:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1003,2848864,"Dabali, Handigaun",pm25,46.807793,µg/m³,2025-10-12T09:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1004,2848864,"Dabali, Handigaun",pm25,37.498016,µg/m³,2025-10-12T10:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
1995,2848864,"Dabali, Handigaun",pm25,46.697024,µg/m³,2025-11-25T17:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1996,2848864,"Dabali, Handigaun",pm25,44.546131,µg/m³,2025-11-25T18:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1997,2848864,"Dabali, Handigaun",pm25,47.059048,µg/m³,2025-11-25T19:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1998,2848864,"Dabali, Handigaun",pm25,60.145833,µg/m³,2025-11-25T20:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient
1999,2848864,"Dabali, Handigaun",pm25,46.983550,µg/m³,2025-11-25T21:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient

In [7]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
1000,2848864,"Dabali, Handigaun",pm25,56.245883,µg/m³,2025-10-12 06:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-10-12,06:45:00
1001,2848864,"Dabali, Handigaun",pm25,57.654112,µg/m³,2025-10-12 07:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-10-12,07:45:00
1002,2848864,"Dabali, Handigaun",pm25,42.654445,µg/m³,2025-10-12 08:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-10-12,08:45:00
1003,2848864,"Dabali, Handigaun",pm25,46.807793,µg/m³,2025-10-12 09:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-10-12,09:45:00
1004,2848864,"Dabali, Handigaun",pm25,37.498016,µg/m³,2025-10-12 10:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-10-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2848864,"Dabali, Handigaun",pm25,46.697024,µg/m³,2025-11-25 17:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-11-25,17:45:00
1996,2848864,"Dabali, Handigaun",pm25,44.546131,µg/m³,2025-11-25 18:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-11-25,18:45:00
1997,2848864,"Dabali, Handigaun",pm25,47.059048,µg/m³,2025-11-25 19:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-11-25,19:45:00
1998,2848864,"Dabali, Handigaun",pm25,60.145833,µg/m³,2025-11-25 20:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-11-25,20:45:00
1999,2848864,"Dabali, Handigaun",pm25,46.983550,µg/m³,2025-11-25 21:45:00+05:45,Asia/Kathmandu,27.681891,85.287078,Unknown Person,AirGradient,2025-11-25,21:45:00

In [8]:
cleaned.to_csv('cleaned_HandigaunLast365days.csv', index=False)