In [1]:
import pandas as pd

## 1. Imadol last 365 days data cleaning

In [2]:
df365 = pd.read_csv('Imadol_last365days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.2 MB

In [3]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [4]:
df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [5]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6121047,Imadol(SC-27)- GD Labs,pm1,32.500000,µg/m³,2025-11-06T12:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1,6121047,Imadol(SC-27)- GD Labs,pm1,15.764083,µg/m³,2025-11-06T13:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
2,6121047,Imadol(SC-27)- GD Labs,pm1,8.081125,µg/m³,2025-11-06T14:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3,6121047,Imadol(SC-27)- GD Labs,pm1,13.876125,µg/m³,2025-11-06T15:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4,6121047,Imadol(SC-27)- GD Labs,pm1,21.259208,µg/m³,2025-11-06T16:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,6121047,Imadol(SC-27)- GD Labs,um003,3960.000000,particles/cm³,2026-02-26T17:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4996,6121047,Imadol(SC-27)- GD Labs,um003,4197.000000,particles/cm³,2026-02-26T18:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4997,6121047,Imadol(SC-27)- GD Labs,um003,4611.000000,particles/cm³,2026-02-26T19:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4998,6121047,Imadol(SC-27)- GD Labs,um003,4226.000000,particles/cm³,2026-02-26T20:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4999,6121047,Imadol(SC-27)- GD Labs,um003,4412.000000,particles/cm³,2026-02-26T21:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient

In [6]:
cleaned = cleaned[cleaned['parameter']=='pm25']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
1000,6121047,Imadol(SC-27)- GD Labs,pm25,49.250000,µg/m³,2025-11-06T12:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1001,6121047,Imadol(SC-27)- GD Labs,pm25,28.694500,µg/m³,2025-11-06T13:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1002,6121047,Imadol(SC-27)- GD Labs,pm25,21.965042,µg/m³,2025-11-06T14:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1003,6121047,Imadol(SC-27)- GD Labs,pm25,27.629958,µg/m³,2025-11-06T15:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1004,6121047,Imadol(SC-27)- GD Labs,pm25,34.937583,µg/m³,2025-11-06T16:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
1995,6121047,Imadol(SC-27)- GD Labs,pm25,94.600000,µg/m³,2026-02-26T17:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1996,6121047,Imadol(SC-27)- GD Labs,pm25,100.000000,µg/m³,2026-02-26T18:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1997,6121047,Imadol(SC-27)- GD Labs,pm25,109.900000,µg/m³,2026-02-26T19:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1998,6121047,Imadol(SC-27)- GD Labs,pm25,101.000000,µg/m³,2026-02-26T20:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1999,6121047,Imadol(SC-27)- GD Labs,pm25,105.500000,µg/m³,2026-02-26T21:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient

In [7]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
1000,6121047,Imadol(SC-27)- GD Labs,pm25,49.250000,µg/m³,2025-11-06 12:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2025-11-06,12:45:00
1001,6121047,Imadol(SC-27)- GD Labs,pm25,28.694500,µg/m³,2025-11-06 13:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2025-11-06,13:45:00
1002,6121047,Imadol(SC-27)- GD Labs,pm25,21.965042,µg/m³,2025-11-06 14:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2025-11-06,14:45:00
1003,6121047,Imadol(SC-27)- GD Labs,pm25,27.629958,µg/m³,2025-11-06 15:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2025-11-06,15:45:00
1004,6121047,Imadol(SC-27)- GD Labs,pm25,34.937583,µg/m³,2025-11-06 16:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2025-11-06,16:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,6121047,Imadol(SC-27)- GD Labs,pm25,94.600000,µg/m³,2026-02-26 17:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-02-26,17:45:00
1996,6121047,Imadol(SC-27)- GD Labs,pm25,100.000000,µg/m³,2026-02-26 18:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-02-26,18:45:00
1997,6121047,Imadol(SC-27)- GD Labs,pm25,109.900000,µg/m³,2026-02-26 19:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-02-26,19:45:00
1998,6121047,Imadol(SC-27)- GD Labs,pm25,101.000000,µg/m³,2026-02-26 20:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-02-26,20:45:00
1999,6121047,Imadol(SC-27)- GD Labs,pm25,105.500000,µg/m³,2026-02-26 21:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-02-26,21:45:00

In [8]:
cleaned.to_csv('cleaned_ImadolLast365days.csv', index=False)

## 2. Imadol last 30 days data cleaning

In [9]:
df30 = pd.read_csv('Imadol_last30days.csv')
df30

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,6121047,Imadol(SC-27)- GD Labs,pm1,15.7,µg/m³,2026-09-05T01:00:00Z,2026-09-05T06:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
1,6121047,Imadol(SC-27)- GD Labs,pm1,13.7,µg/m³,2026-09-05T02:00:00Z,2026-09-05T07:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
2,6121047,Imadol(SC-27)- GD Labs,pm1,16.3,µg/m³,2026-09-05T03:00:00Z,2026-09-05T08:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3,6121047,Imadol(SC-27)- GD Labs,pm1,17.9,µg/m³,2026-09-05T04:00:00Z,2026-09-05T09:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4,6121047,Imadol(SC-27)- GD Labs,pm1,11.4,µg/m³,2026-09-05T05:00:00Z,2026-09-05T10:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4415,6121047,Imadol(SC-27)- GD Labs,um003,1078.0,particles/cm³,2026-10-11T20:00:00Z,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4416,6121047,Imadol(SC-27)- GD Labs,um003,1075.0,particles/cm³,2026-10-11T21:00:00Z,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4417,6121047,Imadol(SC-27)- GD Labs,um003,1093.0,particles/cm³,2026-10-11T22:00:00Z,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4418,6121047,Imadol(SC-27)- GD Labs,um003,974.0,particles/cm³,2026-10-11T23:00:00Z,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4419,6121047,Imadol(SC-27)- GD Labs,um003,968.0,particles/cm³,2026-10-12T00:00:00Z,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient

In [10]:
df30.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      4420
isMobile         4420
isMonitor        4420
owner_name          0
provider            0
dtype: int64

In [11]:
df30.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [12]:
cleaned1 =df30.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6121047,Imadol(SC-27)- GD Labs,pm1,15.7,µg/m³,2026-09-05T06:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1,6121047,Imadol(SC-27)- GD Labs,pm1,13.7,µg/m³,2026-09-05T07:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
2,6121047,Imadol(SC-27)- GD Labs,pm1,16.3,µg/m³,2026-09-05T08:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3,6121047,Imadol(SC-27)- GD Labs,pm1,17.9,µg/m³,2026-09-05T09:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4,6121047,Imadol(SC-27)- GD Labs,pm1,11.4,µg/m³,2026-09-05T10:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4415,6121047,Imadol(SC-27)- GD Labs,um003,1078.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4416,6121047,Imadol(SC-27)- GD Labs,um003,1075.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4417,6121047,Imadol(SC-27)- GD Labs,um003,1093.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4418,6121047,Imadol(SC-27)- GD Labs,um003,974.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4419,6121047,Imadol(SC-27)- GD Labs,um003,968.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient

In [13]:
cleaned1 = cleaned1[cleaned1['parameter']=='pm25']
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
884,6121047,Imadol(SC-27)- GD Labs,pm25,25.7,µg/m³,2026-09-05T06:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
885,6121047,Imadol(SC-27)- GD Labs,pm25,24.1,µg/m³,2026-09-05T07:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
886,6121047,Imadol(SC-27)- GD Labs,pm25,26.0,µg/m³,2026-09-05T08:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
887,6121047,Imadol(SC-27)- GD Labs,pm25,27.0,µg/m³,2026-09-05T09:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
888,6121047,Imadol(SC-27)- GD Labs,pm25,19.8,µg/m³,2026-09-05T10:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
1763,6121047,Imadol(SC-27)- GD Labs,pm25,32.6,µg/m³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1764,6121047,Imadol(SC-27)- GD Labs,pm25,32.9,µg/m³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1765,6121047,Imadol(SC-27)- GD Labs,pm25,33.1,µg/m³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1766,6121047,Imadol(SC-27)- GD Labs,pm25,30.6,µg/m³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1767,6121047,Imadol(SC-27)- GD Labs,pm25,29.9,µg/m³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient

In [14]:
# seperating date and time
cleaned1['datetimeLocal']=pd.to_datetime(cleaned1['datetimeLocal'])
cleaned1['date']=cleaned1['datetimeLocal'].dt.date
cleaned1['time']=cleaned1['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
884,6121047,Imadol(SC-27)- GD Labs,pm25,25.7,µg/m³,2026-09-05 06:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-09-05,06:45:00
885,6121047,Imadol(SC-27)- GD Labs,pm25,24.1,µg/m³,2026-09-05 07:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-09-05,07:45:00
886,6121047,Imadol(SC-27)- GD Labs,pm25,26.0,µg/m³,2026-09-05 08:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-09-05,08:45:00
887,6121047,Imadol(SC-27)- GD Labs,pm25,27.0,µg/m³,2026-09-05 09:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-09-05,09:45:00
888,6121047,Imadol(SC-27)- GD Labs,pm25,19.8,µg/m³,2026-09-05 10:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-09-05,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1763,6121047,Imadol(SC-27)- GD Labs,pm25,32.6,µg/m³,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
1764,6121047,Imadol(SC-27)- GD Labs,pm25,32.9,µg/m³,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
1765,6121047,Imadol(SC-27)- GD Labs,pm25,33.1,µg/m³,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
1766,6121047,Imadol(SC-27)- GD Labs,pm25,30.6,µg/m³,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
1767,6121047,Imadol(SC-27)- GD Labs,pm25,29.9,µg/m³,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [15]:
cleaned1.to_csv('cleaned_ImadolLast30days.csv', index=False)