In [1]:
import pandas as pd

## 1. Imadol last 365 days data cleaning

In [2]:
df365 = pd.read_csv('Imadol_last365days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.2 MB

In [3]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [ ]:

df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [4]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6121047,Imadol(SC-27)- GD Labs,pm1,32.500000,µg/m³,2025-11-06T12:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1,6121047,Imadol(SC-27)- GD Labs,pm1,15.764083,µg/m³,2025-11-06T13:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
2,6121047,Imadol(SC-27)- GD Labs,pm1,8.081125,µg/m³,2025-11-06T14:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3,6121047,Imadol(SC-27)- GD Labs,pm1,13.876125,µg/m³,2025-11-06T15:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4,6121047,Imadol(SC-27)- GD Labs,pm1,21.259208,µg/m³,2025-11-06T16:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,6121047,Imadol(SC-27)- GD Labs,um003,3960.000000,particles/cm³,2026-02-26T17:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4996,6121047,Imadol(SC-27)- GD Labs,um003,4197.000000,particles/cm³,2026-02-26T18:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4997,6121047,Imadol(SC-27)- GD Labs,um003,4611.000000,particles/cm³,2026-02-26T19:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4998,6121047,Imadol(SC-27)- GD Labs,um003,4226.000000,particles/cm³,2026-02-26T20:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4999,6121047,Imadol(SC-27)- GD Labs,um003,4412.000000,particles/cm³,2026-02-26T21:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient

In [5]:
# cleaned = cleaned[cleaned['parameter']=='pm25']
cleaned = cleaned[cleaned['parameter']=='temperature']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
3000,6121047,Imadol(SC-27)- GD Labs,temperature,25.389999,c,2025-11-06T12:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3001,6121047,Imadol(SC-27)- GD Labs,temperature,30.306500,c,2025-11-06T13:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3002,6121047,Imadol(SC-27)- GD Labs,temperature,31.118750,c,2025-11-06T14:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3003,6121047,Imadol(SC-27)- GD Labs,temperature,29.722958,c,2025-11-06T15:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3004,6121047,Imadol(SC-27)- GD Labs,temperature,27.721125,c,2025-11-06T16:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
3995,6121047,Imadol(SC-27)- GD Labs,temperature,20.600000,c,2026-02-26T17:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3996,6121047,Imadol(SC-27)- GD Labs,temperature,20.200000,c,2026-02-26T18:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3997,6121047,Imadol(SC-27)- GD Labs,temperature,19.900000,c,2026-02-26T19:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3998,6121047,Imadol(SC-27)- GD Labs,temperature,19.800000,c,2026-02-26T20:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3999,6121047,Imadol(SC-27)- GD Labs,temperature,19.800000,c,2026-02-26T21:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient

In [6]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
3000,6121047,Imadol(SC-27)- GD Labs,temperature,25.389999,c,2025-11-06 12:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2025-11-06,12:45:00
3001,6121047,Imadol(SC-27)- GD Labs,temperature,30.306500,c,2025-11-06 13:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2025-11-06,13:45:00
3002,6121047,Imadol(SC-27)- GD Labs,temperature,31.118750,c,2025-11-06 14:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2025-11-06,14:45:00
3003,6121047,Imadol(SC-27)- GD Labs,temperature,29.722958,c,2025-11-06 15:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2025-11-06,15:45:00
3004,6121047,Imadol(SC-27)- GD Labs,temperature,27.721125,c,2025-11-06 16:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2025-11-06,16:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,6121047,Imadol(SC-27)- GD Labs,temperature,20.600000,c,2026-02-26 17:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-02-26,17:45:00
3996,6121047,Imadol(SC-27)- GD Labs,temperature,20.200000,c,2026-02-26 18:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-02-26,18:45:00
3997,6121047,Imadol(SC-27)- GD Labs,temperature,19.900000,c,2026-02-26 19:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-02-26,19:45:00
3998,6121047,Imadol(SC-27)- GD Labs,temperature,19.800000,c,2026-02-26 20:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-02-26,20:45:00
3999,6121047,Imadol(SC-27)- GD Labs,temperature,19.800000,c,2026-02-26 21:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-02-26,21:45:00

In [7]:
cleaned.to_csv('cleaned_ImadolLast365days.csv', index=False)

## 2. Imadol last 30 days data cleaning

In [9]:
df30 = pd.read_csv('Imadol_last30days.csv')
df30

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,6121047,Imadol(SC-27)- GD Labs,pm1,15.7,µg/m³,2026-09-05T01:00:00Z,2026-09-05T06:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
1,6121047,Imadol(SC-27)- GD Labs,pm1,13.7,µg/m³,2026-09-05T02:00:00Z,2026-09-05T07:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
2,6121047,Imadol(SC-27)- GD Labs,pm1,16.3,µg/m³,2026-09-05T03:00:00Z,2026-09-05T08:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3,6121047,Imadol(SC-27)- GD Labs,pm1,17.9,µg/m³,2026-09-05T04:00:00Z,2026-09-05T09:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4,6121047,Imadol(SC-27)- GD Labs,pm1,11.4,µg/m³,2026-09-05T05:00:00Z,2026-09-05T10:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4415,6121047,Imadol(SC-27)- GD Labs,um003,1078.0,particles/cm³,2026-10-11T20:00:00Z,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4416,6121047,Imadol(SC-27)- GD Labs,um003,1075.0,particles/cm³,2026-10-11T21:00:00Z,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4417,6121047,Imadol(SC-27)- GD Labs,um003,1093.0,particles/cm³,2026-10-11T22:00:00Z,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4418,6121047,Imadol(SC-27)- GD Labs,um003,974.0,particles/cm³,2026-10-11T23:00:00Z,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4419,6121047,Imadol(SC-27)- GD Labs,um003,968.0,particles/cm³,2026-10-12T00:00:00Z,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient

In [10]:
df30.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      4420
isMobile         4420
isMonitor        4420
owner_name          0
provider            0
dtype: int64

In [11]:
df30.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [12]:
cleaned1 =df30.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6121047,Imadol(SC-27)- GD Labs,pm1,15.7,µg/m³,2026-09-05T06:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1,6121047,Imadol(SC-27)- GD Labs,pm1,13.7,µg/m³,2026-09-05T07:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
2,6121047,Imadol(SC-27)- GD Labs,pm1,16.3,µg/m³,2026-09-05T08:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3,6121047,Imadol(SC-27)- GD Labs,pm1,17.9,µg/m³,2026-09-05T09:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4,6121047,Imadol(SC-27)- GD Labs,pm1,11.4,µg/m³,2026-09-05T10:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4415,6121047,Imadol(SC-27)- GD Labs,um003,1078.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4416,6121047,Imadol(SC-27)- GD Labs,um003,1075.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4417,6121047,Imadol(SC-27)- GD Labs,um003,1093.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4418,6121047,Imadol(SC-27)- GD Labs,um003,974.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4419,6121047,Imadol(SC-27)- GD Labs,um003,968.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient

In [13]:
# cleaned1 = cleaned1[cleaned1['parameter']=='pm25']
cleaned1 = cleaned1[cleaned1['parameter']=='temperature']
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
2652,6121047,Imadol(SC-27)- GD Labs,temperature,25.9,c,2026-09-05T06:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
2653,6121047,Imadol(SC-27)- GD Labs,temperature,26.3,c,2026-09-05T07:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
2654,6121047,Imadol(SC-27)- GD Labs,temperature,27.6,c,2026-09-05T08:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
2655,6121047,Imadol(SC-27)- GD Labs,temperature,29.4,c,2026-09-05T09:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
2656,6121047,Imadol(SC-27)- GD Labs,temperature,30.3,c,2026-09-05T10:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
3531,6121047,Imadol(SC-27)- GD Labs,temperature,23.2,c,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3532,6121047,Imadol(SC-27)- GD Labs,temperature,23.1,c,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3533,6121047,Imadol(SC-27)- GD Labs,temperature,22.7,c,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3534,6121047,Imadol(SC-27)- GD Labs,temperature,22.1,c,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3535,6121047,Imadol(SC-27)- GD Labs,temperature,22.1,c,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient

In [14]:
# seperating date and time
cleaned1['datetimeLocal']=pd.to_datetime(cleaned1['datetimeLocal'])
cleaned1['date']=cleaned1['datetimeLocal'].dt.date
cleaned1['time']=cleaned1['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
2652,6121047,Imadol(SC-27)- GD Labs,temperature,25.9,c,2026-09-05 06:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-09-05,06:45:00
2653,6121047,Imadol(SC-27)- GD Labs,temperature,26.3,c,2026-09-05 07:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-09-05,07:45:00
2654,6121047,Imadol(SC-27)- GD Labs,temperature,27.6,c,2026-09-05 08:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-09-05,08:45:00
2655,6121047,Imadol(SC-27)- GD Labs,temperature,29.4,c,2026-09-05 09:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-09-05,09:45:00
2656,6121047,Imadol(SC-27)- GD Labs,temperature,30.3,c,2026-09-05 10:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-09-05,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3531,6121047,Imadol(SC-27)- GD Labs,temperature,23.2,c,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
3532,6121047,Imadol(SC-27)- GD Labs,temperature,23.1,c,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
3533,6121047,Imadol(SC-27)- GD Labs,temperature,22.7,c,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
3534,6121047,Imadol(SC-27)- GD Labs,temperature,22.1,c,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
3535,6121047,Imadol(SC-27)- GD Labs,temperature,22.1,c,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [15]:
cleaned1.to_csv('cleaned_ImadolLast30days.csv', index=False)

## 3. Imadol last 7 Days data Cleaning

In [16]:
df7 = pd.read_csv('Imadol_last1week.csv')
df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 840 entries, 0 to 839
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    840 non-null    int64
 1   location_name  840 non-null    str
 2   parameter      840 non-null    str
 3   value          840 non-null    float64
 4   unit           840 non-null    str
 5   datetimeUtc    840 non-null    str
 6   datetimeLocal  840 non-null    str
 7   timezone       840 non-null    str
 8   latitude       840 non-null    float64
 9   longitude      840 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     840 non-null    str
 14  provider       840 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 211.6 KB

In [17]:
df7.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      840
isMobile         840
isMonitor        840
owner_name         0
provider           0
dtype: int64

In [18]:
cleaned2 =df7.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6121047,Imadol(SC-27)- GD Labs,pm1,30.0,µg/m³,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1,6121047,Imadol(SC-27)- GD Labs,pm1,31.8,µg/m³,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
2,6121047,Imadol(SC-27)- GD Labs,pm1,30.3,µg/m³,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3,6121047,Imadol(SC-27)- GD Labs,pm1,30.4,µg/m³,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4,6121047,Imadol(SC-27)- GD Labs,pm1,29.1,µg/m³,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
835,6121047,Imadol(SC-27)- GD Labs,um003,1078.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
836,6121047,Imadol(SC-27)- GD Labs,um003,1075.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
837,6121047,Imadol(SC-27)- GD Labs,um003,1093.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
838,6121047,Imadol(SC-27)- GD Labs,um003,974.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
839,6121047,Imadol(SC-27)- GD Labs,um003,968.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient

In [21]:
# cleaned2 = cleaned2[cleaned2['parameter']=='pm25']
cleaned2 = cleaned2[cleaned2['parameter']=='temperature']
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
504,6121047,Imadol(SC-27)- GD Labs,temperature,24.3,c,2026-10-05 06:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-05,06:45:00
505,6121047,Imadol(SC-27)- GD Labs,temperature,24.7,c,2026-10-05 07:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-05,07:45:00
506,6121047,Imadol(SC-27)- GD Labs,temperature,26.5,c,2026-10-05 08:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-05,08:45:00
507,6121047,Imadol(SC-27)- GD Labs,temperature,28.2,c,2026-10-05 09:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-05,09:45:00
508,6121047,Imadol(SC-27)- GD Labs,temperature,29.2,c,2026-10-05 10:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-05,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,6121047,Imadol(SC-27)- GD Labs,temperature,23.2,c,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
668,6121047,Imadol(SC-27)- GD Labs,temperature,23.1,c,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
669,6121047,Imadol(SC-27)- GD Labs,temperature,22.7,c,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
670,6121047,Imadol(SC-27)- GD Labs,temperature,22.1,c,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
671,6121047,Imadol(SC-27)- GD Labs,temperature,22.1,c,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [22]:
# seperating date and time
cleaned2['datetimeLocal']=pd.to_datetime(cleaned2['datetimeLocal'])
cleaned2['date']=cleaned2['datetimeLocal'].dt.date
cleaned2['time']=cleaned2['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
504,6121047,Imadol(SC-27)- GD Labs,temperature,24.3,c,2026-10-05 06:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-05,06:45:00
505,6121047,Imadol(SC-27)- GD Labs,temperature,24.7,c,2026-10-05 07:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-05,07:45:00
506,6121047,Imadol(SC-27)- GD Labs,temperature,26.5,c,2026-10-05 08:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-05,08:45:00
507,6121047,Imadol(SC-27)- GD Labs,temperature,28.2,c,2026-10-05 09:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-05,09:45:00
508,6121047,Imadol(SC-27)- GD Labs,temperature,29.2,c,2026-10-05 10:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-05,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,6121047,Imadol(SC-27)- GD Labs,temperature,23.2,c,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
668,6121047,Imadol(SC-27)- GD Labs,temperature,23.1,c,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
669,6121047,Imadol(SC-27)- GD Labs,temperature,22.7,c,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
670,6121047,Imadol(SC-27)- GD Labs,temperature,22.1,c,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
671,6121047,Imadol(SC-27)- GD Labs,temperature,22.1,c,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [23]:
cleaned2.to_csv('cleaned_ImadolLast7days.csv', index=False)

## 4. Imadol Last 24 hours data Cleaning

In [24]:
df24 = pd.read_csv('Imadol_last24hours.csv')
df24.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    120 non-null    int64
 1   location_name  120 non-null    str
 2   parameter      120 non-null    str
 3   value          120 non-null    float64
 4   unit           120 non-null    str
 5   datetimeUtc    120 non-null    str
 6   datetimeLocal  120 non-null    str
 7   timezone       120 non-null    str
 8   latitude       120 non-null    float64
 9   longitude      120 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     120 non-null    str
 14  provider       120 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 30.3 KB

In [25]:
df24.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      120
isMobile         120
isMonitor        120
owner_name         0
provider           0
dtype: int64

In [26]:
cleaned3 = df24.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6121047,Imadol(SC-27)- GD Labs,pm1,21.5,µg/m³,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
1,6121047,Imadol(SC-27)- GD Labs,pm1,23.3,µg/m³,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
2,6121047,Imadol(SC-27)- GD Labs,pm1,26.6,µg/m³,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
3,6121047,Imadol(SC-27)- GD Labs,pm1,28.0,µg/m³,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
4,6121047,Imadol(SC-27)- GD Labs,pm1,20.8,µg/m³,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
115,6121047,Imadol(SC-27)- GD Labs,um003,1078.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
116,6121047,Imadol(SC-27)- GD Labs,um003,1075.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
117,6121047,Imadol(SC-27)- GD Labs,um003,1093.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
118,6121047,Imadol(SC-27)- GD Labs,um003,974.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
119,6121047,Imadol(SC-27)- GD Labs,um003,968.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient

In [27]:
# cleaned3 = cleaned3[cleaned3['parameter']=='pm25']
cleaned3 = cleaned3[cleaned3['parameter']=='temperature']
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
72,6121047,Imadol(SC-27)- GD Labs,temperature,21.9,c,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
73,6121047,Imadol(SC-27)- GD Labs,temperature,22.2,c,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
74,6121047,Imadol(SC-27)- GD Labs,temperature,23.8,c,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
75,6121047,Imadol(SC-27)- GD Labs,temperature,26.2,c,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
76,6121047,Imadol(SC-27)- GD Labs,temperature,28.0,c,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
77,6121047,Imadol(SC-27)- GD Labs,temperature,30.0,c,2026-10-11T11:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
78,6121047,Imadol(SC-27)- GD Labs,temperature,31.2,c,2026-10-11T12:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
79,6121047,Imadol(SC-27)- GD Labs,temperature,29.7,c,2026-10-11T13:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
80,6121047,Imadol(SC-27)- GD Labs,temperature,29.9,c,2026-10-11T14:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
81,6121047,Imadol(SC-27)- GD Labs,temperature,29.9,c,2026-10-11T15:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
82,6121047,Imadol(SC-27)- GD Labs,temperature,28.4,c,2026-10-11T16:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
83,6121047,Imadol(SC-27)- GD Labs,temperature,26.7,c,2026-10-11T17:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
84,6121047,Imadol(SC-27)- GD Labs,temperature,25.8,c,2026-10-11T18:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
85,6121047,Imadol(SC-27)- GD Labs,temperature,24.7,c,2026-10-11T19:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
86,6121047,Imadol(SC-27)- GD Labs,temperature,24.5,c,2026-10-11T20:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
87,6121047,Imadol(SC-27)- GD Labs,temperature,24.5,c,2026-10-11T21:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
88,6121047,Imadol(SC-27)- GD Labs,temperature,23.9,c,2026-10-11T22:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
89,6121047,Imadol(SC-27)- GD Labs,temperature,24.0,c,2026-10-11T23:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
90,6121047,Imadol(SC-27)- GD Labs,temperature,23.4,c,2026-10-12T00:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
91,6121047,Imadol(SC-27)- GD Labs,temperature,23.2,c,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
92,6121047,Imadol(SC-27)- GD Labs,temperature,23.1,c,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
93,6121047,Imadol(SC-27)- GD Labs,temperature,22.7,c,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
94,6121047,Imadol(SC-27)- GD Labs,temperature,22.1,c,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient
95,6121047,Imadol(SC-27)- GD Labs,temperature,22.1,c,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient

In [28]:
# seperating date and time
cleaned3['datetimeLocal']=pd.to_datetime(cleaned3['datetimeLocal'])
cleaned3['date']=cleaned3['datetimeLocal'].dt.date
cleaned3['time']=cleaned3['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
72,6121047,Imadol(SC-27)- GD Labs,temperature,21.9,c,2026-10-11 06:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,06:45:00
73,6121047,Imadol(SC-27)- GD Labs,temperature,22.2,c,2026-10-11 07:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,07:45:00
74,6121047,Imadol(SC-27)- GD Labs,temperature,23.8,c,2026-10-11 08:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,08:45:00
75,6121047,Imadol(SC-27)- GD Labs,temperature,26.2,c,2026-10-11 09:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,09:45:00
76,6121047,Imadol(SC-27)- GD Labs,temperature,28.0,c,2026-10-11 10:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,10:45:00
77,6121047,Imadol(SC-27)- GD Labs,temperature,30.0,c,2026-10-11 11:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,11:45:00
78,6121047,Imadol(SC-27)- GD Labs,temperature,31.2,c,2026-10-11 12:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,12:45:00
79,6121047,Imadol(SC-27)- GD Labs,temperature,29.7,c,2026-10-11 13:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,13:45:00
80,6121047,Imadol(SC-27)- GD Labs,temperature,29.9,c,2026-10-11 14:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,14:45:00
81,6121047,Imadol(SC-27)- GD Labs,temperature,29.9,c,2026-10-11 15:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,15:45:00
82,6121047,Imadol(SC-27)- GD Labs,temperature,28.4,c,2026-10-11 16:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,16:45:00
83,6121047,Imadol(SC-27)- GD Labs,temperature,26.7,c,2026-10-11 17:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,17:45:00
84,6121047,Imadol(SC-27)- GD Labs,temperature,25.8,c,2026-10-11 18:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,18:45:00
85,6121047,Imadol(SC-27)- GD Labs,temperature,24.7,c,2026-10-11 19:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,19:45:00
86,6121047,Imadol(SC-27)- GD Labs,temperature,24.5,c,2026-10-11 20:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,20:45:00
87,6121047,Imadol(SC-27)- GD Labs,temperature,24.5,c,2026-10-11 21:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,21:45:00
88,6121047,Imadol(SC-27)- GD Labs,temperature,23.9,c,2026-10-11 22:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,22:45:00
89,6121047,Imadol(SC-27)- GD Labs,temperature,24.0,c,2026-10-11 23:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-11,23:45:00
90,6121047,Imadol(SC-27)- GD Labs,temperature,23.4,c,2026-10-12 00:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,00:45:00
91,6121047,Imadol(SC-27)- GD Labs,temperature,23.2,c,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
92,6121047,Imadol(SC-27)- GD Labs,temperature,23.1,c,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
93,6121047,Imadol(SC-27)- GD Labs,temperature,22.7,c,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
94,6121047,Imadol(SC-27)- GD Labs,temperature,22.1,c,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
95,6121047,Imadol(SC-27)- GD Labs,temperature,22.1,c,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.661062,85.347716,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [29]:
cleaned3.to_csv('cleaned_ImadolLast24hours.csv', index=False)