In [1]:
import pandas as pd

## 1. Kupondole last 365 days data cleaning

In [3]:
df365 = pd.read_csv('Kupondole_last356days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.2 MB

In [4]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [5]:
df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [6]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6141912,Kupondole (SC-40)-GD Labs,pm1,20.670000,µg/m³,2025-11-25T13:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
1,6141912,Kupondole (SC-40)-GD Labs,pm1,24.665000,µg/m³,2025-11-25T17:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
2,6141912,Kupondole (SC-40)-GD Labs,pm1,39.665001,µg/m³,2025-11-25T18:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
3,6141912,Kupondole (SC-40)-GD Labs,pm1,37.830002,µg/m³,2025-11-25T19:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
4,6141912,Kupondole (SC-40)-GD Labs,pm1,54.250000,µg/m³,2025-11-25T20:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,6141912,Kupondole (SC-40)-GD Labs,um003,2309.000000,particles/cm³,2026-01-22T17:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
4996,6141912,Kupondole (SC-40)-GD Labs,um003,5327.556641,particles/cm³,2026-01-22T18:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
4997,6141912,Kupondole (SC-40)-GD Labs,um003,5917.419922,particles/cm³,2026-01-22T19:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
4998,6141912,Kupondole (SC-40)-GD Labs,um003,4926.166667,particles/cm³,2026-01-22T20:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
4999,6141912,Kupondole (SC-40)-GD Labs,um003,4798.278320,particles/cm³,2026-01-22T21:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient

In [7]:
cleaned = cleaned[cleaned['parameter']=='pm25']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
1000,6141912,Kupondole (SC-40)-GD Labs,pm25,32.166666,µg/m³,2025-11-25T13:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
1001,6141912,Kupondole (SC-40)-GD Labs,pm25,38.915001,µg/m³,2025-11-25T17:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
1002,6141912,Kupondole (SC-40)-GD Labs,pm25,61.165001,µg/m³,2025-11-25T18:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
1003,6141912,Kupondole (SC-40)-GD Labs,pm25,58.000000,µg/m³,2025-11-25T19:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
1004,6141912,Kupondole (SC-40)-GD Labs,pm25,82.500000,µg/m³,2025-11-25T20:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
1995,6141912,Kupondole (SC-40)-GD Labs,pm25,52.834999,µg/m³,2026-01-22T17:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
1996,6141912,Kupondole (SC-40)-GD Labs,pm25,116.389999,µg/m³,2026-01-22T18:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
1997,6141912,Kupondole (SC-40)-GD Labs,pm25,131.669998,µg/m³,2026-01-22T19:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
1998,6141912,Kupondole (SC-40)-GD Labs,pm25,112.500000,µg/m³,2026-01-22T20:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient
1999,6141912,Kupondole (SC-40)-GD Labs,pm25,111.083333,µg/m³,2026-01-22T21:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient

In [8]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
1000,6141912,Kupondole (SC-40)-GD Labs,pm25,32.166666,µg/m³,2025-11-25 13:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient,2025-11-25,13:45:00
1001,6141912,Kupondole (SC-40)-GD Labs,pm25,38.915001,µg/m³,2025-11-25 17:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient,2025-11-25,17:45:00
1002,6141912,Kupondole (SC-40)-GD Labs,pm25,61.165001,µg/m³,2025-11-25 18:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient,2025-11-25,18:45:00
1003,6141912,Kupondole (SC-40)-GD Labs,pm25,58.000000,µg/m³,2025-11-25 19:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient,2025-11-25,19:45:00
1004,6141912,Kupondole (SC-40)-GD Labs,pm25,82.500000,µg/m³,2025-11-25 20:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient,2025-11-25,20:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,6141912,Kupondole (SC-40)-GD Labs,pm25,52.834999,µg/m³,2026-01-22 17:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient,2026-01-22,17:45:00
1996,6141912,Kupondole (SC-40)-GD Labs,pm25,116.389999,µg/m³,2026-01-22 18:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient,2026-01-22,18:45:00
1997,6141912,Kupondole (SC-40)-GD Labs,pm25,131.669998,µg/m³,2026-01-22 19:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient,2026-01-22,19:45:00
1998,6141912,Kupondole (SC-40)-GD Labs,pm25,112.500000,µg/m³,2026-01-22 20:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient,2026-01-22,20:45:00
1999,6141912,Kupondole (SC-40)-GD Labs,pm25,111.083333,µg/m³,2026-01-22 21:45:00+05:45,Asia/Kathmandu,27.689661,85.310442,Green Decision Labs and Research,AirGradient,2026-01-22,21:45:00

In [9]:
cleaned.to_csv('cleaned_KupondoleLast365days.csv', index=False)