In [1]:
import pandas as pd

## 1. Lagankhel last 365 days data cleaning

In [2]:
df365 = pd.read_csv('Lagankhel_last365Days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.3 MB

In [3]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [4]:
df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [5]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,5509788,Lagankhel (SC - 05) - GD Labs,pm1,29.225833,µg/m³,2025-10-12T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1,5509788,Lagankhel (SC - 05) - GD Labs,pm1,32.216917,µg/m³,2025-10-12T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2,5509788,Lagankhel (SC - 05) - GD Labs,pm1,31.200125,µg/m³,2025-10-12T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3,5509788,Lagankhel (SC - 05) - GD Labs,pm1,32.567722,µg/m³,2025-10-12T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4,5509788,Lagankhel (SC - 05) - GD Labs,pm1,33.081222,µg/m³,2025-10-12T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,5509788,Lagankhel (SC - 05) - GD Labs,um003,2016.966329,particles/cm³,2025-11-27T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4996,5509788,Lagankhel (SC - 05) - GD Labs,um003,2136.280670,particles/cm³,2025-11-27T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4997,5509788,Lagankhel (SC - 05) - GD Labs,um003,2156.245955,particles/cm³,2025-11-27T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4998,5509788,Lagankhel (SC - 05) - GD Labs,um003,2498.888837,particles/cm³,2025-11-27T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4999,5509788,Lagankhel (SC - 05) - GD Labs,um003,3269.216992,particles/cm³,2025-11-27T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [6]:
# cleaned = cleaned[cleaned['parameter']=='pm25']
cleaned = cleaned[cleaned['parameter']=='temperature']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
3000,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.467958,c,2025-10-12T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3001,5509788,Lagankhel (SC - 05) - GD Labs,temperature,23.085417,c,2025-10-12T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3002,5509788,Lagankhel (SC - 05) - GD Labs,temperature,24.098778,c,2025-10-12T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3003,5509788,Lagankhel (SC - 05) - GD Labs,temperature,25.040861,c,2025-10-12T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3004,5509788,Lagankhel (SC - 05) - GD Labs,temperature,26.285500,c,2025-10-12T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
3995,5509788,Lagankhel (SC - 05) - GD Labs,temperature,17.608334,c,2025-11-27T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3996,5509788,Lagankhel (SC - 05) - GD Labs,temperature,17.513667,c,2025-11-27T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3997,5509788,Lagankhel (SC - 05) - GD Labs,temperature,17.335708,c,2025-11-27T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3998,5509788,Lagankhel (SC - 05) - GD Labs,temperature,17.392500,c,2025-11-27T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3999,5509788,Lagankhel (SC - 05) - GD Labs,temperature,17.492333,c,2025-11-27T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [7]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
3000,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.467958,c,2025-10-12 06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-10-12,06:45:00
3001,5509788,Lagankhel (SC - 05) - GD Labs,temperature,23.085417,c,2025-10-12 07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-10-12,07:45:00
3002,5509788,Lagankhel (SC - 05) - GD Labs,temperature,24.098778,c,2025-10-12 08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-10-12,08:45:00
3003,5509788,Lagankhel (SC - 05) - GD Labs,temperature,25.040861,c,2025-10-12 09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-10-12,09:45:00
3004,5509788,Lagankhel (SC - 05) - GD Labs,temperature,26.285500,c,2025-10-12 10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-10-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,5509788,Lagankhel (SC - 05) - GD Labs,temperature,17.608334,c,2025-11-27 03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-11-27,03:45:00
3996,5509788,Lagankhel (SC - 05) - GD Labs,temperature,17.513667,c,2025-11-27 04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-11-27,04:45:00
3997,5509788,Lagankhel (SC - 05) - GD Labs,temperature,17.335708,c,2025-11-27 05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-11-27,05:45:00
3998,5509788,Lagankhel (SC - 05) - GD Labs,temperature,17.392500,c,2025-11-27 06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-11-27,06:45:00
3999,5509788,Lagankhel (SC - 05) - GD Labs,temperature,17.492333,c,2025-11-27 07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-11-27,07:45:00

In [8]:
cleaned.to_csv('cleaned_LagankhelLast365days.csv', index=False)

## 2. Lagankhel last 30 days data cleaning

In [9]:
df30 = pd.read_csv('Lagankhel_last30days.csv')
df30

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,5509788,Lagankhel (SC - 05) - GD Labs,pm1,15.0,µg/m³,2026-09-12T01:00:00Z,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
1,5509788,Lagankhel (SC - 05) - GD Labs,pm1,22.3,µg/m³,2026-09-12T02:00:00Z,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
2,5509788,Lagankhel (SC - 05) - GD Labs,pm1,21.8,µg/m³,2026-09-12T03:00:00Z,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3,5509788,Lagankhel (SC - 05) - GD Labs,pm1,23.3,µg/m³,2026-09-12T04:00:00Z,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4,5509788,Lagankhel (SC - 05) - GD Labs,pm1,17.6,µg/m³,2026-09-12T05:00:00Z,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,5509788,Lagankhel (SC - 05) - GD Labs,um003,1151.0,particles/cm³,2026-10-11T20:00:00Z,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3596,5509788,Lagankhel (SC - 05) - GD Labs,um003,1130.0,particles/cm³,2026-10-11T21:00:00Z,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3597,5509788,Lagankhel (SC - 05) - GD Labs,um003,1155.0,particles/cm³,2026-10-11T22:00:00Z,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3598,5509788,Lagankhel (SC - 05) - GD Labs,um003,1059.0,particles/cm³,2026-10-11T23:00:00Z,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3599,5509788,Lagankhel (SC - 05) - GD Labs,um003,1040.0,particles/cm³,2026-10-12T00:00:00Z,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient

In [10]:
df30.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      3600
isMobile         3600
isMonitor        3600
owner_name          0
provider            0
dtype: int64

In [11]:
df30.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [12]:
cleaned1 =df30.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,5509788,Lagankhel (SC - 05) - GD Labs,pm1,15.0,µg/m³,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1,5509788,Lagankhel (SC - 05) - GD Labs,pm1,22.3,µg/m³,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2,5509788,Lagankhel (SC - 05) - GD Labs,pm1,21.8,µg/m³,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3,5509788,Lagankhel (SC - 05) - GD Labs,pm1,23.3,µg/m³,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4,5509788,Lagankhel (SC - 05) - GD Labs,pm1,17.6,µg/m³,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
3595,5509788,Lagankhel (SC - 05) - GD Labs,um003,1151.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3596,5509788,Lagankhel (SC - 05) - GD Labs,um003,1130.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3597,5509788,Lagankhel (SC - 05) - GD Labs,um003,1155.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3598,5509788,Lagankhel (SC - 05) - GD Labs,um003,1059.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3599,5509788,Lagankhel (SC - 05) - GD Labs,um003,1040.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [13]:
# cleaned1 = cleaned1[cleaned1['parameter']=='pm25']
cleaned1 = cleaned1[cleaned1['parameter']=='temperature']
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
2160,5509788,Lagankhel (SC - 05) - GD Labs,temperature,25.1,c,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2161,5509788,Lagankhel (SC - 05) - GD Labs,temperature,25.5,c,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2162,5509788,Lagankhel (SC - 05) - GD Labs,temperature,26.3,c,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2163,5509788,Lagankhel (SC - 05) - GD Labs,temperature,26.8,c,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2164,5509788,Lagankhel (SC - 05) - GD Labs,temperature,27.8,c,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
2875,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.3,c,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2876,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.2,c,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2877,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.9,c,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2878,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.6,c,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2879,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.5,c,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [14]:
# seperating date and time
cleaned1['datetimeLocal']=pd.to_datetime(cleaned1['datetimeLocal'])
cleaned1['date']=cleaned1['datetimeLocal'].dt.date
cleaned1['time']=cleaned1['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
2160,5509788,Lagankhel (SC - 05) - GD Labs,temperature,25.1,c,2026-09-12 06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-09-12,06:45:00
2161,5509788,Lagankhel (SC - 05) - GD Labs,temperature,25.5,c,2026-09-12 07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-09-12,07:45:00
2162,5509788,Lagankhel (SC - 05) - GD Labs,temperature,26.3,c,2026-09-12 08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-09-12,08:45:00
2163,5509788,Lagankhel (SC - 05) - GD Labs,temperature,26.8,c,2026-09-12 09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-09-12,09:45:00
2164,5509788,Lagankhel (SC - 05) - GD Labs,temperature,27.8,c,2026-09-12 10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-09-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.3,c,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
2876,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.2,c,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
2877,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.9,c,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
2878,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.6,c,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
2879,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.5,c,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [15]:
cleaned1.to_csv('cleaned_LagankhelLast30days.csv', index=False)

## 3. Lagankhel last 7 Days data Cleaning

In [16]:
df7 = pd.read_csv('Lagankhel_last1week.csv')
df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 840 entries, 0 to 839
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    840 non-null    int64
 1   location_name  840 non-null    str
 2   parameter      840 non-null    str
 3   value          840 non-null    float64
 4   unit           840 non-null    str
 5   datetimeUtc    840 non-null    str
 6   datetimeLocal  840 non-null    str
 7   timezone       840 non-null    str
 8   latitude       840 non-null    float64
 9   longitude      840 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     840 non-null    str
 14  provider       840 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 217.3 KB

In [17]:
df7.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      840
isMobile         840
isMonitor        840
owner_name         0
provider           0
dtype: int64

In [18]:
cleaned2 =df7.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,5509788,Lagankhel (SC - 05) - GD Labs,pm1,30.7,µg/m³,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1,5509788,Lagankhel (SC - 05) - GD Labs,pm1,33.8,µg/m³,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2,5509788,Lagankhel (SC - 05) - GD Labs,pm1,32.3,µg/m³,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3,5509788,Lagankhel (SC - 05) - GD Labs,pm1,33.2,µg/m³,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4,5509788,Lagankhel (SC - 05) - GD Labs,pm1,29.2,µg/m³,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
835,5509788,Lagankhel (SC - 05) - GD Labs,um003,1151.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
836,5509788,Lagankhel (SC - 05) - GD Labs,um003,1130.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
837,5509788,Lagankhel (SC - 05) - GD Labs,um003,1155.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
838,5509788,Lagankhel (SC - 05) - GD Labs,um003,1059.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
839,5509788,Lagankhel (SC - 05) - GD Labs,um003,1040.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [19]:
# cleaned2 = cleaned2[cleaned2['parameter']=='pm25']
cleaned2 = cleaned2[cleaned2['parameter']=='temperature']
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
504,5509788,Lagankhel (SC - 05) - GD Labs,temperature,23.8,c,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
505,5509788,Lagankhel (SC - 05) - GD Labs,temperature,23.9,c,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
506,5509788,Lagankhel (SC - 05) - GD Labs,temperature,24.8,c,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
507,5509788,Lagankhel (SC - 05) - GD Labs,temperature,25.3,c,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
508,5509788,Lagankhel (SC - 05) - GD Labs,temperature,26.0,c,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
667,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.3,c,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
668,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.2,c,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
669,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.9,c,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
670,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.6,c,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
671,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.5,c,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [21]:
# seperating date and time
cleaned2['datetimeLocal']=pd.to_datetime(cleaned2['datetimeLocal'])
cleaned2['date']=cleaned2['datetimeLocal'].dt.date
cleaned2['time']=cleaned2['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
504,5509788,Lagankhel (SC - 05) - GD Labs,temperature,23.8,c,2026-10-05 06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-05,06:45:00
505,5509788,Lagankhel (SC - 05) - GD Labs,temperature,23.9,c,2026-10-05 07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-05,07:45:00
506,5509788,Lagankhel (SC - 05) - GD Labs,temperature,24.8,c,2026-10-05 08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-05,08:45:00
507,5509788,Lagankhel (SC - 05) - GD Labs,temperature,25.3,c,2026-10-05 09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-05,09:45:00
508,5509788,Lagankhel (SC - 05) - GD Labs,temperature,26.0,c,2026-10-05 10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-05,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.3,c,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
668,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.2,c,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
669,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.9,c,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
670,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.6,c,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
671,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.5,c,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [22]:
cleaned2.to_csv('cleaned_LagankhelLast7days.csv', index=False)

## 4. Lagankhel Last 24 hours data Cleaning

In [23]:
df24 = pd.read_csv('Lagankhel_last24hours.csv')
df24.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    120 non-null    int64
 1   location_name  120 non-null    str
 2   parameter      120 non-null    str
 3   value          120 non-null    float64
 4   unit           120 non-null    str
 5   datetimeUtc    120 non-null    str
 6   datetimeLocal  120 non-null    str
 7   timezone       120 non-null    str
 8   latitude       120 non-null    float64
 9   longitude      120 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     120 non-null    str
 14  provider       120 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 31.2 KB

In [24]:
df24.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      120
isMobile         120
isMonitor        120
owner_name         0
provider           0
dtype: int64

In [25]:
cleaned3 = df24.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,5509788,Lagankhel (SC - 05) - GD Labs,pm1,23.5,µg/m³,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1,5509788,Lagankhel (SC - 05) - GD Labs,pm1,29.0,µg/m³,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2,5509788,Lagankhel (SC - 05) - GD Labs,pm1,29.0,µg/m³,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3,5509788,Lagankhel (SC - 05) - GD Labs,pm1,28.2,µg/m³,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4,5509788,Lagankhel (SC - 05) - GD Labs,pm1,26.0,µg/m³,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
115,5509788,Lagankhel (SC - 05) - GD Labs,um003,1151.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
116,5509788,Lagankhel (SC - 05) - GD Labs,um003,1130.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
117,5509788,Lagankhel (SC - 05) - GD Labs,um003,1155.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
118,5509788,Lagankhel (SC - 05) - GD Labs,um003,1059.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
119,5509788,Lagankhel (SC - 05) - GD Labs,um003,1040.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [26]:
# cleaned3 = cleaned3[cleaned3['parameter']=='pm25']
cleaned3 = cleaned3[cleaned3['parameter']=='temperature']
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
72,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.1,c,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
73,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.3,c,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
74,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.2,c,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
75,5509788,Lagankhel (SC - 05) - GD Labs,temperature,23.1,c,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
76,5509788,Lagankhel (SC - 05) - GD Labs,temperature,24.4,c,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
77,5509788,Lagankhel (SC - 05) - GD Labs,temperature,25.3,c,2026-10-11T11:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
78,5509788,Lagankhel (SC - 05) - GD Labs,temperature,25.7,c,2026-10-11T12:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
79,5509788,Lagankhel (SC - 05) - GD Labs,temperature,26.0,c,2026-10-11T13:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
80,5509788,Lagankhel (SC - 05) - GD Labs,temperature,26.7,c,2026-10-11T14:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
81,5509788,Lagankhel (SC - 05) - GD Labs,temperature,28.1,c,2026-10-11T15:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
82,5509788,Lagankhel (SC - 05) - GD Labs,temperature,26.7,c,2026-10-11T16:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
83,5509788,Lagankhel (SC - 05) - GD Labs,temperature,25.5,c,2026-10-11T17:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
84,5509788,Lagankhel (SC - 05) - GD Labs,temperature,23.7,c,2026-10-11T18:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
85,5509788,Lagankhel (SC - 05) - GD Labs,temperature,24.1,c,2026-10-11T19:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
86,5509788,Lagankhel (SC - 05) - GD Labs,temperature,23.5,c,2026-10-11T20:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
87,5509788,Lagankhel (SC - 05) - GD Labs,temperature,23.2,c,2026-10-11T21:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
88,5509788,Lagankhel (SC - 05) - GD Labs,temperature,23.0,c,2026-10-11T22:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
89,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.7,c,2026-10-11T23:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
90,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.5,c,2026-10-12T00:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
91,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.3,c,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
92,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.2,c,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
93,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.9,c,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
94,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.6,c,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
95,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.5,c,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [27]:
# seperating date and time
cleaned3['datetimeLocal']=pd.to_datetime(cleaned3['datetimeLocal'])
cleaned3['date']=cleaned3['datetimeLocal'].dt.date
cleaned3['time']=cleaned3['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
72,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.1,c,2026-10-11 06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,06:45:00
73,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.3,c,2026-10-11 07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,07:45:00
74,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.2,c,2026-10-11 08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,08:45:00
75,5509788,Lagankhel (SC - 05) - GD Labs,temperature,23.1,c,2026-10-11 09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,09:45:00
76,5509788,Lagankhel (SC - 05) - GD Labs,temperature,24.4,c,2026-10-11 10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,10:45:00
77,5509788,Lagankhel (SC - 05) - GD Labs,temperature,25.3,c,2026-10-11 11:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,11:45:00
78,5509788,Lagankhel (SC - 05) - GD Labs,temperature,25.7,c,2026-10-11 12:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,12:45:00
79,5509788,Lagankhel (SC - 05) - GD Labs,temperature,26.0,c,2026-10-11 13:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,13:45:00
80,5509788,Lagankhel (SC - 05) - GD Labs,temperature,26.7,c,2026-10-11 14:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,14:45:00
81,5509788,Lagankhel (SC - 05) - GD Labs,temperature,28.1,c,2026-10-11 15:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,15:45:00
82,5509788,Lagankhel (SC - 05) - GD Labs,temperature,26.7,c,2026-10-11 16:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,16:45:00
83,5509788,Lagankhel (SC - 05) - GD Labs,temperature,25.5,c,2026-10-11 17:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,17:45:00
84,5509788,Lagankhel (SC - 05) - GD Labs,temperature,23.7,c,2026-10-11 18:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,18:45:00
85,5509788,Lagankhel (SC - 05) - GD Labs,temperature,24.1,c,2026-10-11 19:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,19:45:00
86,5509788,Lagankhel (SC - 05) - GD Labs,temperature,23.5,c,2026-10-11 20:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,20:45:00
87,5509788,Lagankhel (SC - 05) - GD Labs,temperature,23.2,c,2026-10-11 21:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,21:45:00
88,5509788,Lagankhel (SC - 05) - GD Labs,temperature,23.0,c,2026-10-11 22:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,22:45:00
89,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.7,c,2026-10-11 23:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,23:45:00
90,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.5,c,2026-10-12 00:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,00:45:00
91,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.3,c,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
92,5509788,Lagankhel (SC - 05) - GD Labs,temperature,22.2,c,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
93,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.9,c,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
94,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.6,c,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
95,5509788,Lagankhel (SC - 05) - GD Labs,temperature,21.5,c,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [28]:
cleaned3.to_csv('cleaned_LagankhelLast24hours.csv', index=False)