In [1]:
import pandas as pd

## 1. Lagankhel last 365 days data cleaning

In [30]:
df365 = pd.read_csv('Lagankhel_last365Days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.3 MB

In [31]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [32]:
df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [33]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,5509788,Lagankhel (SC - 05) - GD Labs,pm1,29.225833,µg/m³,2025-10-12T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1,5509788,Lagankhel (SC - 05) - GD Labs,pm1,32.216917,µg/m³,2025-10-12T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2,5509788,Lagankhel (SC - 05) - GD Labs,pm1,31.200125,µg/m³,2025-10-12T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3,5509788,Lagankhel (SC - 05) - GD Labs,pm1,32.567722,µg/m³,2025-10-12T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4,5509788,Lagankhel (SC - 05) - GD Labs,pm1,33.081222,µg/m³,2025-10-12T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,5509788,Lagankhel (SC - 05) - GD Labs,um003,2016.966329,particles/cm³,2025-11-27T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4996,5509788,Lagankhel (SC - 05) - GD Labs,um003,2136.280670,particles/cm³,2025-11-27T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4997,5509788,Lagankhel (SC - 05) - GD Labs,um003,2156.245955,particles/cm³,2025-11-27T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4998,5509788,Lagankhel (SC - 05) - GD Labs,um003,2498.888837,particles/cm³,2025-11-27T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4999,5509788,Lagankhel (SC - 05) - GD Labs,um003,3269.216992,particles/cm³,2025-11-27T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [34]:
# cleaned = cleaned[cleaned['parameter']=='pm25']
# cleaned = cleaned[cleaned['parameter']=='temperature']
cleaned = cleaned[cleaned['parameter']=='relativehumidity']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
2000,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,49.169250,%,2025-10-12T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2001,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,47.179417,%,2025-10-12T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2002,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,45.503514,%,2025-10-12T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2003,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,43.669944,%,2025-10-12T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2004,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,41.028250,%,2025-10-12T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
2995,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,48.523667,%,2025-11-27T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2996,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,48.527333,%,2025-11-27T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2997,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,48.756625,%,2025-11-27T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2998,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,48.326333,%,2025-11-27T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2999,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,48.281000,%,2025-11-27T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [35]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
2000,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,49.169250,%,2025-10-12 06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-10-12,06:45:00
2001,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,47.179417,%,2025-10-12 07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-10-12,07:45:00
2002,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,45.503514,%,2025-10-12 08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-10-12,08:45:00
2003,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,43.669944,%,2025-10-12 09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-10-12,09:45:00
2004,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,41.028250,%,2025-10-12 10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-10-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,48.523667,%,2025-11-27 03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-11-27,03:45:00
2996,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,48.527333,%,2025-11-27 04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-11-27,04:45:00
2997,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,48.756625,%,2025-11-27 05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-11-27,05:45:00
2998,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,48.326333,%,2025-11-27 06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-11-27,06:45:00
2999,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,48.281000,%,2025-11-27 07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-11-27,07:45:00

In [36]:
cleaned.to_csv('cleaned_LagankhelLast365days.csv', index=False)

## 2. Lagankhel last 30 days data cleaning

In [2]:
df30 = pd.read_csv('Lagankhel_last30days.csv')
df30

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,5509788,Lagankhel (SC - 05) - GD Labs,pm1,15.0,µg/m³,2026-09-12T01:00:00Z,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
1,5509788,Lagankhel (SC - 05) - GD Labs,pm1,22.3,µg/m³,2026-09-12T02:00:00Z,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
2,5509788,Lagankhel (SC - 05) - GD Labs,pm1,21.8,µg/m³,2026-09-12T03:00:00Z,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3,5509788,Lagankhel (SC - 05) - GD Labs,pm1,23.3,µg/m³,2026-09-12T04:00:00Z,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4,5509788,Lagankhel (SC - 05) - GD Labs,pm1,17.6,µg/m³,2026-09-12T05:00:00Z,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,5509788,Lagankhel (SC - 05) - GD Labs,um003,1151.0,particles/cm³,2026-10-11T20:00:00Z,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3596,5509788,Lagankhel (SC - 05) - GD Labs,um003,1130.0,particles/cm³,2026-10-11T21:00:00Z,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3597,5509788,Lagankhel (SC - 05) - GD Labs,um003,1155.0,particles/cm³,2026-10-11T22:00:00Z,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3598,5509788,Lagankhel (SC - 05) - GD Labs,um003,1059.0,particles/cm³,2026-10-11T23:00:00Z,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3599,5509788,Lagankhel (SC - 05) - GD Labs,um003,1040.0,particles/cm³,2026-10-12T00:00:00Z,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient

In [3]:
df30.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      3600
isMobile         3600
isMonitor        3600
owner_name          0
provider            0
dtype: int64

In [4]:
df30.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [5]:
cleaned1 =df30.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,5509788,Lagankhel (SC - 05) - GD Labs,pm1,15.0,µg/m³,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1,5509788,Lagankhel (SC - 05) - GD Labs,pm1,22.3,µg/m³,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2,5509788,Lagankhel (SC - 05) - GD Labs,pm1,21.8,µg/m³,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3,5509788,Lagankhel (SC - 05) - GD Labs,pm1,23.3,µg/m³,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4,5509788,Lagankhel (SC - 05) - GD Labs,pm1,17.6,µg/m³,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
3595,5509788,Lagankhel (SC - 05) - GD Labs,um003,1151.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3596,5509788,Lagankhel (SC - 05) - GD Labs,um003,1130.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3597,5509788,Lagankhel (SC - 05) - GD Labs,um003,1155.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3598,5509788,Lagankhel (SC - 05) - GD Labs,um003,1059.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3599,5509788,Lagankhel (SC - 05) - GD Labs,um003,1040.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [6]:
# cleaned1 = cleaned1[cleaned1['parameter']=='pm25']
# cleaned1 = cleaned1[cleaned1['parameter']=='temperature']
cleaned1 = cleaned1[cleaned1['parameter']=='relativehumidity']
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
1440,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,58.0,%,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1441,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,57.0,%,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1442,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,55.0,%,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1443,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,53.0,%,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1444,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,51.0,%,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
2155,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2156,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2157,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,55.0,%,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2158,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,55.0,%,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2159,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [7]:
# seperating date and time
cleaned1['datetimeLocal']=pd.to_datetime(cleaned1['datetimeLocal'])
cleaned1['date']=cleaned1['datetimeLocal'].dt.date
cleaned1['time']=cleaned1['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
1440,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,58.0,%,2026-09-12 06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-09-12,06:45:00
1441,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,57.0,%,2026-09-12 07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-09-12,07:45:00
1442,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,55.0,%,2026-09-12 08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-09-12,08:45:00
1443,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,53.0,%,2026-09-12 09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-09-12,09:45:00
1444,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,51.0,%,2026-09-12 10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-09-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2155,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
2156,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
2157,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,55.0,%,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
2158,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,55.0,%,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
2159,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [8]:
cleaned1.to_csv('cleaned_LagankhelLast30days.csv', index=False)

## 3. Lagankhel last 7 Days data Cleaning

In [9]:
df7 = pd.read_csv('Lagankhel_last1week.csv')
df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 840 entries, 0 to 839
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    840 non-null    int64
 1   location_name  840 non-null    str
 2   parameter      840 non-null    str
 3   value          840 non-null    float64
 4   unit           840 non-null    str
 5   datetimeUtc    840 non-null    str
 6   datetimeLocal  840 non-null    str
 7   timezone       840 non-null    str
 8   latitude       840 non-null    float64
 9   longitude      840 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     840 non-null    str
 14  provider       840 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 217.3 KB

In [10]:
df7.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      840
isMobile         840
isMonitor        840
owner_name         0
provider           0
dtype: int64

In [11]:
cleaned2 =df7.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,5509788,Lagankhel (SC - 05) - GD Labs,pm1,30.7,µg/m³,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1,5509788,Lagankhel (SC - 05) - GD Labs,pm1,33.8,µg/m³,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2,5509788,Lagankhel (SC - 05) - GD Labs,pm1,32.3,µg/m³,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3,5509788,Lagankhel (SC - 05) - GD Labs,pm1,33.2,µg/m³,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4,5509788,Lagankhel (SC - 05) - GD Labs,pm1,29.2,µg/m³,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
835,5509788,Lagankhel (SC - 05) - GD Labs,um003,1151.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
836,5509788,Lagankhel (SC - 05) - GD Labs,um003,1130.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
837,5509788,Lagankhel (SC - 05) - GD Labs,um003,1155.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
838,5509788,Lagankhel (SC - 05) - GD Labs,um003,1059.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
839,5509788,Lagankhel (SC - 05) - GD Labs,um003,1040.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [12]:
# cleaned2 = cleaned2[cleaned2['parameter']=='pm25']
# cleaned2 = cleaned2[cleaned2['parameter']=='temperature']
cleaned2 = cleaned2[cleaned2['parameter']=='relativehumidity']
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
336,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
337,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
338,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,52.0,%,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
339,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,51.0,%,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
340,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,50.0,%,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
499,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
500,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
501,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,55.0,%,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
502,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,55.0,%,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
503,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [13]:
# seperating date and time
cleaned2['datetimeLocal']=pd.to_datetime(cleaned2['datetimeLocal'])
cleaned2['date']=cleaned2['datetimeLocal'].dt.date
cleaned2['time']=cleaned2['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
336,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-05 06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-05,06:45:00
337,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-05 07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-05,07:45:00
338,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,52.0,%,2026-10-05 08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-05,08:45:00
339,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,51.0,%,2026-10-05 09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-05,09:45:00
340,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,50.0,%,2026-10-05 10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-05,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
500,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
501,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,55.0,%,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
502,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,55.0,%,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
503,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [14]:
cleaned2.to_csv('cleaned_LagankhelLast7days.csv', index=False)

## 4. Lagankhel Last 24 hours data Cleaning

In [15]:
df24 = pd.read_csv('Lagankhel_last24hours.csv')
df24.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    120 non-null    int64
 1   location_name  120 non-null    str
 2   parameter      120 non-null    str
 3   value          120 non-null    float64
 4   unit           120 non-null    str
 5   datetimeUtc    120 non-null    str
 6   datetimeLocal  120 non-null    str
 7   timezone       120 non-null    str
 8   latitude       120 non-null    float64
 9   longitude      120 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     120 non-null    str
 14  provider       120 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 31.2 KB

In [16]:
df24.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      120
isMobile         120
isMonitor        120
owner_name         0
provider           0
dtype: int64

In [17]:
cleaned3 = df24.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,5509788,Lagankhel (SC - 05) - GD Labs,pm1,23.5,µg/m³,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1,5509788,Lagankhel (SC - 05) - GD Labs,pm1,29.0,µg/m³,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2,5509788,Lagankhel (SC - 05) - GD Labs,pm1,29.0,µg/m³,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3,5509788,Lagankhel (SC - 05) - GD Labs,pm1,28.2,µg/m³,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4,5509788,Lagankhel (SC - 05) - GD Labs,pm1,26.0,µg/m³,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
115,5509788,Lagankhel (SC - 05) - GD Labs,um003,1151.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
116,5509788,Lagankhel (SC - 05) - GD Labs,um003,1130.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
117,5509788,Lagankhel (SC - 05) - GD Labs,um003,1155.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
118,5509788,Lagankhel (SC - 05) - GD Labs,um003,1059.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
119,5509788,Lagankhel (SC - 05) - GD Labs,um003,1040.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [18]:
# cleaned3 = cleaned3[cleaned3['parameter']=='pm25']
# cleaned3 = cleaned3[cleaned3['parameter']=='temperature']
cleaned3 = cleaned3[cleaned3['parameter']=='relativehumidity']
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
48,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,56.0,%,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
49,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,56.0,%,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
50,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
51,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,51.0,%,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
52,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,48.0,%,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
53,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,45.0,%,2026-10-11T11:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
54,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,43.0,%,2026-10-11T12:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
55,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,42.0,%,2026-10-11T13:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
56,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,40.0,%,2026-10-11T14:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
57,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,38.0,%,2026-10-11T15:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
58,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,40.0,%,2026-10-11T16:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
59,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,44.0,%,2026-10-11T17:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
60,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,49.0,%,2026-10-11T18:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
61,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,50.0,%,2026-10-11T19:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
62,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,52.0,%,2026-10-11T20:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
63,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,52.0,%,2026-10-11T21:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
64,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,52.0,%,2026-10-11T22:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
65,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,53.0,%,2026-10-11T23:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
66,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12T00:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
67,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
68,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
69,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,55.0,%,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
70,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,55.0,%,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
71,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [19]:
# seperating date and time
cleaned3['datetimeLocal']=pd.to_datetime(cleaned3['datetimeLocal'])
cleaned3['date']=cleaned3['datetimeLocal'].dt.date
cleaned3['time']=cleaned3['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
48,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,56.0,%,2026-10-11 06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,06:45:00
49,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,56.0,%,2026-10-11 07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,07:45:00
50,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-11 08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,08:45:00
51,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,51.0,%,2026-10-11 09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,09:45:00
52,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,48.0,%,2026-10-11 10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,10:45:00
53,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,45.0,%,2026-10-11 11:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,11:45:00
54,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,43.0,%,2026-10-11 12:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,12:45:00
55,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,42.0,%,2026-10-11 13:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,13:45:00
56,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,40.0,%,2026-10-11 14:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,14:45:00
57,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,38.0,%,2026-10-11 15:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,15:45:00
58,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,40.0,%,2026-10-11 16:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,16:45:00
59,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,44.0,%,2026-10-11 17:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,17:45:00
60,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,49.0,%,2026-10-11 18:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,18:45:00
61,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,50.0,%,2026-10-11 19:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,19:45:00
62,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,52.0,%,2026-10-11 20:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,20:45:00
63,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,52.0,%,2026-10-11 21:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,21:45:00
64,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,52.0,%,2026-10-11 22:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,22:45:00
65,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,53.0,%,2026-10-11 23:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-11,23:45:00
66,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12 00:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,00:45:00
67,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
68,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
69,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,55.0,%,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
70,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,55.0,%,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
71,5509788,Lagankhel (SC - 05) - GD Labs,relativehumidity,54.0,%,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [20]:
cleaned3.to_csv('cleaned_LagankhelLast24hours.csv', index=False)