In [1]:
import pandas as pd

## 1. Lagankhel last 365 days data cleaning

In [2]:
df365 = pd.read_csv('Lagankhel_last365Days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.3 MB

In [3]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [4]:
df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [5]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,5509788,Lagankhel (SC - 05) - GD Labs,pm1,29.225833,µg/m³,2025-10-12T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1,5509788,Lagankhel (SC - 05) - GD Labs,pm1,32.216917,µg/m³,2025-10-12T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2,5509788,Lagankhel (SC - 05) - GD Labs,pm1,31.200125,µg/m³,2025-10-12T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3,5509788,Lagankhel (SC - 05) - GD Labs,pm1,32.567722,µg/m³,2025-10-12T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4,5509788,Lagankhel (SC - 05) - GD Labs,pm1,33.081222,µg/m³,2025-10-12T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,5509788,Lagankhel (SC - 05) - GD Labs,um003,2016.966329,particles/cm³,2025-11-27T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4996,5509788,Lagankhel (SC - 05) - GD Labs,um003,2136.280670,particles/cm³,2025-11-27T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4997,5509788,Lagankhel (SC - 05) - GD Labs,um003,2156.245955,particles/cm³,2025-11-27T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4998,5509788,Lagankhel (SC - 05) - GD Labs,um003,2498.888837,particles/cm³,2025-11-27T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4999,5509788,Lagankhel (SC - 05) - GD Labs,um003,3269.216992,particles/cm³,2025-11-27T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [6]:
cleaned = cleaned[cleaned['parameter']=='pm25']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
1000,5509788,Lagankhel (SC - 05) - GD Labs,pm25,49.965417,µg/m³,2025-10-12T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1001,5509788,Lagankhel (SC - 05) - GD Labs,pm25,51.792208,µg/m³,2025-10-12T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1002,5509788,Lagankhel (SC - 05) - GD Labs,pm25,49.384625,µg/m³,2025-10-12T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1003,5509788,Lagankhel (SC - 05) - GD Labs,pm25,51.507472,µg/m³,2025-10-12T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1004,5509788,Lagankhel (SC - 05) - GD Labs,pm25,52.939500,µg/m³,2025-10-12T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
1995,5509788,Lagankhel (SC - 05) - GD Labs,pm25,47.139000,µg/m³,2025-11-27T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1996,5509788,Lagankhel (SC - 05) - GD Labs,pm25,48.755500,µg/m³,2025-11-27T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1997,5509788,Lagankhel (SC - 05) - GD Labs,pm25,48.898000,µg/m³,2025-11-27T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1998,5509788,Lagankhel (SC - 05) - GD Labs,pm25,52.980667,µg/m³,2025-11-27T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1999,5509788,Lagankhel (SC - 05) - GD Labs,pm25,67.400000,µg/m³,2025-11-27T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [7]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
1000,5509788,Lagankhel (SC - 05) - GD Labs,pm25,49.965417,µg/m³,2025-10-12 06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-10-12,06:45:00
1001,5509788,Lagankhel (SC - 05) - GD Labs,pm25,51.792208,µg/m³,2025-10-12 07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-10-12,07:45:00
1002,5509788,Lagankhel (SC - 05) - GD Labs,pm25,49.384625,µg/m³,2025-10-12 08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-10-12,08:45:00
1003,5509788,Lagankhel (SC - 05) - GD Labs,pm25,51.507472,µg/m³,2025-10-12 09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-10-12,09:45:00
1004,5509788,Lagankhel (SC - 05) - GD Labs,pm25,52.939500,µg/m³,2025-10-12 10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-10-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,5509788,Lagankhel (SC - 05) - GD Labs,pm25,47.139000,µg/m³,2025-11-27 03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-11-27,03:45:00
1996,5509788,Lagankhel (SC - 05) - GD Labs,pm25,48.755500,µg/m³,2025-11-27 04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-11-27,04:45:00
1997,5509788,Lagankhel (SC - 05) - GD Labs,pm25,48.898000,µg/m³,2025-11-27 05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-11-27,05:45:00
1998,5509788,Lagankhel (SC - 05) - GD Labs,pm25,52.980667,µg/m³,2025-11-27 06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-11-27,06:45:00
1999,5509788,Lagankhel (SC - 05) - GD Labs,pm25,67.400000,µg/m³,2025-11-27 07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2025-11-27,07:45:00

In [8]:
cleaned.to_csv('cleaned_LagankhelLast365days.csv', index=False)

## 2. Lagankhel last 30 days data cleaning

In [9]:
df30 = pd.read_csv('Lagankhel_last30days.csv')
df30

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,5509788,Lagankhel (SC - 05) - GD Labs,pm1,15.0,µg/m³,2026-09-12T01:00:00Z,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
1,5509788,Lagankhel (SC - 05) - GD Labs,pm1,22.3,µg/m³,2026-09-12T02:00:00Z,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
2,5509788,Lagankhel (SC - 05) - GD Labs,pm1,21.8,µg/m³,2026-09-12T03:00:00Z,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3,5509788,Lagankhel (SC - 05) - GD Labs,pm1,23.3,µg/m³,2026-09-12T04:00:00Z,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4,5509788,Lagankhel (SC - 05) - GD Labs,pm1,17.6,µg/m³,2026-09-12T05:00:00Z,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,5509788,Lagankhel (SC - 05) - GD Labs,um003,1151.0,particles/cm³,2026-10-11T20:00:00Z,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3596,5509788,Lagankhel (SC - 05) - GD Labs,um003,1130.0,particles/cm³,2026-10-11T21:00:00Z,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3597,5509788,Lagankhel (SC - 05) - GD Labs,um003,1155.0,particles/cm³,2026-10-11T22:00:00Z,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3598,5509788,Lagankhel (SC - 05) - GD Labs,um003,1059.0,particles/cm³,2026-10-11T23:00:00Z,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3599,5509788,Lagankhel (SC - 05) - GD Labs,um003,1040.0,particles/cm³,2026-10-12T00:00:00Z,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient

In [10]:
df30.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      3600
isMobile         3600
isMonitor        3600
owner_name          0
provider            0
dtype: int64

In [11]:
df30.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [12]:
cleaned1 =df30.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,5509788,Lagankhel (SC - 05) - GD Labs,pm1,15.0,µg/m³,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1,5509788,Lagankhel (SC - 05) - GD Labs,pm1,22.3,µg/m³,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
2,5509788,Lagankhel (SC - 05) - GD Labs,pm1,21.8,µg/m³,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3,5509788,Lagankhel (SC - 05) - GD Labs,pm1,23.3,µg/m³,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
4,5509788,Lagankhel (SC - 05) - GD Labs,pm1,17.6,µg/m³,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
3595,5509788,Lagankhel (SC - 05) - GD Labs,um003,1151.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3596,5509788,Lagankhel (SC - 05) - GD Labs,um003,1130.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3597,5509788,Lagankhel (SC - 05) - GD Labs,um003,1155.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3598,5509788,Lagankhel (SC - 05) - GD Labs,um003,1059.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
3599,5509788,Lagankhel (SC - 05) - GD Labs,um003,1040.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [13]:
cleaned1 = cleaned1[cleaned1['parameter']=='pm25']
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
720,5509788,Lagankhel (SC - 05) - GD Labs,pm25,23.8,µg/m³,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
721,5509788,Lagankhel (SC - 05) - GD Labs,pm25,31.7,µg/m³,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
722,5509788,Lagankhel (SC - 05) - GD Labs,pm25,31.7,µg/m³,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
723,5509788,Lagankhel (SC - 05) - GD Labs,pm25,33.8,µg/m³,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
724,5509788,Lagankhel (SC - 05) - GD Labs,pm25,25.6,µg/m³,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
1435,5509788,Lagankhel (SC - 05) - GD Labs,pm25,32.8,µg/m³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1436,5509788,Lagankhel (SC - 05) - GD Labs,pm25,32.5,µg/m³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1437,5509788,Lagankhel (SC - 05) - GD Labs,pm25,32.8,µg/m³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1438,5509788,Lagankhel (SC - 05) - GD Labs,pm25,31.0,µg/m³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient
1439,5509788,Lagankhel (SC - 05) - GD Labs,pm25,30.4,µg/m³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient

In [14]:
# seperating date and time
cleaned1['datetimeLocal']=pd.to_datetime(cleaned1['datetimeLocal'])
cleaned1['date']=cleaned1['datetimeLocal'].dt.date
cleaned1['time']=cleaned1['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
720,5509788,Lagankhel (SC - 05) - GD Labs,pm25,23.8,µg/m³,2026-09-12 06:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-09-12,06:45:00
721,5509788,Lagankhel (SC - 05) - GD Labs,pm25,31.7,µg/m³,2026-09-12 07:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-09-12,07:45:00
722,5509788,Lagankhel (SC - 05) - GD Labs,pm25,31.7,µg/m³,2026-09-12 08:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-09-12,08:45:00
723,5509788,Lagankhel (SC - 05) - GD Labs,pm25,33.8,µg/m³,2026-09-12 09:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-09-12,09:45:00
724,5509788,Lagankhel (SC - 05) - GD Labs,pm25,25.6,µg/m³,2026-09-12 10:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-09-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1435,5509788,Lagankhel (SC - 05) - GD Labs,pm25,32.8,µg/m³,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
1436,5509788,Lagankhel (SC - 05) - GD Labs,pm25,32.5,µg/m³,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
1437,5509788,Lagankhel (SC - 05) - GD Labs,pm25,32.8,µg/m³,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
1438,5509788,Lagankhel (SC - 05) - GD Labs,pm25,31.0,µg/m³,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
1439,5509788,Lagankhel (SC - 05) - GD Labs,pm25,30.4,µg/m³,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.666459,85.323093,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [15]:
cleaned1.to_csv('cleaned_LagankhelLast30days.csv', index=False)