In [1]:
import pandas as pd

## 1. Mid-Baneswor last 365 days data cleaning

In [2]:
df365 = pd.read_csv('MidBaneswor_last365days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.3 MB

In [3]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [4]:
df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [5]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,23.511938,µg/m³,2025-11-25T14:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
1,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,27.541000,µg/m³,2025-11-25T15:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
2,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,29.162458,µg/m³,2025-11-25T16:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,29.044750,µg/m³,2025-11-25T17:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
4,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,29.902833,µg/m³,2025-11-25T18:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,4555.244499,particles/cm³,2026-01-06T06:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
4996,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,5024.717250,particles/cm³,2026-01-06T07:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
4997,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,6685.772559,particles/cm³,2026-01-06T08:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
4998,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,5069.113997,particles/cm³,2026-01-06T09:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
4999,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,5772.225618,particles/cm³,2026-01-06T10:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient

In [6]:
# cleaned = cleaned[cleaned['parameter']=='pm25']
cleaned = cleaned[cleaned['parameter']=='temperature']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
3000,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,21.313750,c,2025-11-25T14:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3001,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,21.889250,c,2025-11-25T15:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3002,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,21.304528,c,2025-11-25T16:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3003,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,20.175167,c,2025-11-25T17:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3004,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,20.141000,c,2025-11-25T18:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
3995,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,13.735167,c,2026-01-06T06:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3996,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,13.748764,c,2026-01-06T07:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3997,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,14.127181,c,2026-01-06T08:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3998,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,15.200500,c,2026-01-06T09:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3999,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,16.560944,c,2026-01-06T10:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient

In [7]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
3000,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,21.313750,c,2025-11-25 14:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2025-11-25,14:45:00
3001,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,21.889250,c,2025-11-25 15:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2025-11-25,15:45:00
3002,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,21.304528,c,2025-11-25 16:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2025-11-25,16:45:00
3003,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,20.175167,c,2025-11-25 17:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2025-11-25,17:45:00
3004,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,20.141000,c,2025-11-25 18:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2025-11-25,18:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,13.735167,c,2026-01-06 06:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-01-06,06:45:00
3996,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,13.748764,c,2026-01-06 07:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-01-06,07:45:00
3997,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,14.127181,c,2026-01-06 08:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-01-06,08:45:00
3998,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,15.200500,c,2026-01-06 09:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-01-06,09:45:00
3999,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,16.560944,c,2026-01-06 10:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-01-06,10:45:00

In [8]:
cleaned.to_csv('cleaned_MidBanesworLast365days.csv', index=False)

## 2. MidBaneswor last 30 days data cleaning

In [9]:
df30 = pd.read_csv('MidBaneswor_last30days.csv')
df30

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,14.3,µg/m³,2026-09-12T01:00:00Z,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
1,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,17.2,µg/m³,2026-09-12T02:00:00Z,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
2,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,20.8,µg/m³,2026-09-12T03:00:00Z,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,12.8,µg/m³,2026-09-12T04:00:00Z,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,19.2,µg/m³,2026-09-12T05:00:00Z,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1428.0,particles/cm³,2026-10-11T20:00:00Z,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3596,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1786.0,particles/cm³,2026-10-11T21:00:00Z,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3597,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1532.0,particles/cm³,2026-10-11T22:00:00Z,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3598,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1279.0,particles/cm³,2026-10-11T23:00:00Z,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3599,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1228.0,particles/cm³,2026-10-12T00:00:00Z,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient

In [10]:
df30.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      3600
isMobile         3600
isMonitor        3600
owner_name          0
provider            0
dtype: int64

In [11]:
df30.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [12]:
cleaned1 =df30.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,14.3,µg/m³,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
1,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,17.2,µg/m³,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
2,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,20.8,µg/m³,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,12.8,µg/m³,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
4,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,19.2,µg/m³,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
3595,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1428.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3596,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1786.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3597,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1532.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3598,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1279.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3599,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1228.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient

In [13]:
# cleaned1 = cleaned1[cleaned1['parameter']=='pm25']
cleaned1 = cleaned1[cleaned1['parameter']=='temperature']
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
2160,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,26.5,c,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
2161,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,26.7,c,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
2162,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,27.6,c,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
2163,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,28.7,c,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
2164,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,29.7,c,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
2875,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.4,c,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
2876,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.1,c,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
2877,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.9,c,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
2878,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.8,c,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
2879,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.5,c,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient

In [14]:
# seperating date and time
cleaned1['datetimeLocal']=pd.to_datetime(cleaned1['datetimeLocal'])
cleaned1['date']=cleaned1['datetimeLocal'].dt.date
cleaned1['time']=cleaned1['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
2160,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,26.5,c,2026-09-12 06:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-09-12,06:45:00
2161,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,26.7,c,2026-09-12 07:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-09-12,07:45:00
2162,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,27.6,c,2026-09-12 08:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-09-12,08:45:00
2163,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,28.7,c,2026-09-12 09:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-09-12,09:45:00
2164,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,29.7,c,2026-09-12 10:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-09-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.4,c,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
2876,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.1,c,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
2877,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.9,c,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
2878,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.8,c,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
2879,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.5,c,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [15]:
cleaned1.to_csv('cleaned_MidBanesworLast30days.csv', index=False)

## 3. Mid-Baneswor last 7 days data cleaning

In [16]:
df7 = pd.read_csv('MidBaneswor_last1week.csv')
df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 840 entries, 0 to 839
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    840 non-null    int64
 1   location_name  840 non-null    str
 2   parameter      840 non-null    str
 3   value          840 non-null    float64
 4   unit           840 non-null    str
 5   datetimeUtc    840 non-null    str
 6   datetimeLocal  840 non-null    str
 7   timezone       840 non-null    str
 8   latitude       840 non-null    float64
 9   longitude      840 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     840 non-null    str
 14  provider       840 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 217.3 KB

In [17]:
df7.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      840
isMobile         840
isMonitor        840
owner_name         0
provider           0
dtype: int64

In [18]:
cleaned2 =df7.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,31.6,µg/m³,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
1,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,33.5,µg/m³,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
2,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,34.0,µg/m³,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,35.0,µg/m³,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
4,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,34.5,µg/m³,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
835,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1428.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
836,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1786.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
837,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1532.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
838,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1279.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
839,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1228.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient

In [19]:
# cleaned2 = cleaned2[cleaned2['parameter']=='pm25']
cleaned2 = cleaned2[cleaned2['parameter']=='temperature']
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
504,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,24.9,c,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
505,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,25.2,c,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
506,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,26.0,c,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
507,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,26.5,c,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
508,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,27.6,c,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
667,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.4,c,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
668,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.1,c,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
669,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.9,c,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
670,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.8,c,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
671,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.5,c,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient

In [20]:
# seperating date and time
cleaned2['datetimeLocal']=pd.to_datetime(cleaned2['datetimeLocal'])
cleaned2['date']=cleaned2['datetimeLocal'].dt.date
cleaned2['time']=cleaned2['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
504,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,24.9,c,2026-10-05 06:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-05,06:45:00
505,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,25.2,c,2026-10-05 07:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-05,07:45:00
506,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,26.0,c,2026-10-05 08:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-05,08:45:00
507,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,26.5,c,2026-10-05 09:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-05,09:45:00
508,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,27.6,c,2026-10-05 10:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-05,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.4,c,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
668,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.1,c,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
669,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.9,c,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
670,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.8,c,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
671,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.5,c,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [21]:
cleaned2.to_csv('cleaned_MidBanesworLast7days.csv', index=False)

## 4. Mid-Baneswor Last 24 hours data Cleaning

In [22]:
df24 = pd.read_csv('MidBaneswor_last24hours.csv')
df24.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    120 non-null    int64
 1   location_name  120 non-null    str
 2   parameter      120 non-null    str
 3   value          120 non-null    float64
 4   unit           120 non-null    str
 5   datetimeUtc    120 non-null    str
 6   datetimeLocal  120 non-null    str
 7   timezone       120 non-null    str
 8   latitude       120 non-null    float64
 9   longitude      120 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     120 non-null    str
 14  provider       120 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 31.2 KB

In [23]:
df24.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      120
isMobile         120
isMonitor        120
owner_name         0
provider           0
dtype: int64

In [24]:
cleaned3 = df24.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,28.2,µg/m³,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
1,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,30.7,µg/m³,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
2,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,31.3,µg/m³,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,26.8,µg/m³,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
4,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,23.8,µg/m³,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
115,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1428.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
116,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1786.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
117,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1532.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
118,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1279.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
119,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,1228.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient

In [25]:
# cleaned3 = cleaned3[cleaned3['parameter']=='pm25']
cleaned3 = cleaned3[cleaned3['parameter']=='temperature']
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
72,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.2,c,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
73,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.6,c,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
74,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.5,c,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
75,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,24.6,c,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
76,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,25.5,c,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
77,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,26.3,c,2026-10-11T11:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
78,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,27.0,c,2026-10-11T12:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
79,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,27.3,c,2026-10-11T13:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
80,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,27.3,c,2026-10-11T14:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
81,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,27.1,c,2026-10-11T15:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
82,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,26.7,c,2026-10-11T16:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
83,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,26.2,c,2026-10-11T17:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
84,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,25.5,c,2026-10-11T18:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
85,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,25.2,c,2026-10-11T19:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
86,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,24.8,c,2026-10-11T20:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
87,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,24.4,c,2026-10-11T21:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
88,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,24.1,c,2026-10-11T22:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
89,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.8,c,2026-10-11T23:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
90,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.5,c,2026-10-12T00:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
91,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.4,c,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
92,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.1,c,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
93,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.9,c,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
94,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.8,c,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
95,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.5,c,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient

In [26]:
cleaned3['datetimeLocal']=pd.to_datetime(cleaned3['datetimeLocal'])
cleaned3['date']=cleaned3['datetimeLocal'].dt.date
cleaned3['time']=cleaned3['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
72,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.2,c,2026-10-11 06:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,06:45:00
73,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.6,c,2026-10-11 07:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,07:45:00
74,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.5,c,2026-10-11 08:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,08:45:00
75,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,24.6,c,2026-10-11 09:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,09:45:00
76,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,25.5,c,2026-10-11 10:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,10:45:00
77,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,26.3,c,2026-10-11 11:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,11:45:00
78,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,27.0,c,2026-10-11 12:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,12:45:00
79,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,27.3,c,2026-10-11 13:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,13:45:00
80,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,27.3,c,2026-10-11 14:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,14:45:00
81,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,27.1,c,2026-10-11 15:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,15:45:00
82,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,26.7,c,2026-10-11 16:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,16:45:00
83,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,26.2,c,2026-10-11 17:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,17:45:00
84,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,25.5,c,2026-10-11 18:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,18:45:00
85,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,25.2,c,2026-10-11 19:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,19:45:00
86,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,24.8,c,2026-10-11 20:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,20:45:00
87,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,24.4,c,2026-10-11 21:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,21:45:00
88,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,24.1,c,2026-10-11 22:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,22:45:00
89,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.8,c,2026-10-11 23:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-11,23:45:00
90,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.5,c,2026-10-12 00:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-12,00:45:00
91,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.4,c,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
92,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,23.1,c,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
93,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.9,c,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
94,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.8,c,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
95,6142022,Mid Baneshwor (SC-39)-GD Labs,temperature,22.5,c,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [27]:
cleaned3.to_csv('cleaned_MidBanesworLast24hours.csv', index=False)