In [1]:
import pandas as pd

## 1. Mid-Baneswor last 365 days data cleaning

In [2]:
df365 = pd.read_csv('MidBaneswor_last365days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.3 MB

In [3]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [4]:
df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [5]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,23.511938,µg/m³,2025-11-25T14:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
1,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,27.541000,µg/m³,2025-11-25T15:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
2,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,29.162458,µg/m³,2025-11-25T16:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
3,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,29.044750,µg/m³,2025-11-25T17:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
4,6142022,Mid Baneshwor (SC-39)-GD Labs,pm1,29.902833,µg/m³,2025-11-25T18:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,4555.244499,particles/cm³,2026-01-06T06:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
4996,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,5024.717250,particles/cm³,2026-01-06T07:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
4997,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,6685.772559,particles/cm³,2026-01-06T08:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
4998,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,5069.113997,particles/cm³,2026-01-06T09:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
4999,6142022,Mid Baneshwor (SC-39)-GD Labs,um003,5772.225618,particles/cm³,2026-01-06T10:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient

In [6]:
cleaned = cleaned[cleaned['parameter']=='pm25']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
1000,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,38.878687,µg/m³,2025-11-25T14:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
1001,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,44.905125,µg/m³,2025-11-25T15:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
1002,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,48.938361,µg/m³,2025-11-25T16:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
1003,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,48.021458,µg/m³,2025-11-25T17:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
1004,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,49.416167,µg/m³,2025-11-25T18:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
1995,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,97.325000,µg/m³,2026-01-06T06:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
1996,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,107.025500,µg/m³,2026-01-06T07:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
1997,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,144.185445,µg/m³,2026-01-06T08:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
1998,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,110.216833,µg/m³,2026-01-06T09:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient
1999,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,124.994500,µg/m³,2026-01-06T10:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient

In [7]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
1000,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,38.878687,µg/m³,2025-11-25 14:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2025-11-25,14:45:00
1001,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,44.905125,µg/m³,2025-11-25 15:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2025-11-25,15:45:00
1002,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,48.938361,µg/m³,2025-11-25 16:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2025-11-25,16:45:00
1003,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,48.021458,µg/m³,2025-11-25 17:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2025-11-25,17:45:00
1004,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,49.416167,µg/m³,2025-11-25 18:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2025-11-25,18:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,97.325000,µg/m³,2026-01-06 06:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-01-06,06:45:00
1996,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,107.025500,µg/m³,2026-01-06 07:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-01-06,07:45:00
1997,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,144.185445,µg/m³,2026-01-06 08:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-01-06,08:45:00
1998,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,110.216833,µg/m³,2026-01-06 09:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-01-06,09:45:00
1999,6142022,Mid Baneshwor (SC-39)-GD Labs,pm25,124.994500,µg/m³,2026-01-06 10:45:00+05:45,Asia/Kathmandu,27.693662,85.340501,Green Decision Labs and Research,AirGradient,2026-01-06,10:45:00

In [10]:
cleaned.to_csv('cleaned_MidBanesworLast365days.csv', index=False)