In [1]:
import pandas as pd

## 1. Tokha last 365 days data cleaning

In [2]:
df365 = pd.read_csv('Tokha_last365days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.2 MB

In [3]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [4]:
df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [5]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6121046,Tokha (SC-31) - GD Labs,pm1,23.830000,µg/m³,2025-11-06T12:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1,6121046,Tokha (SC-31) - GD Labs,pm1,10.654375,µg/m³,2025-11-06T13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
2,6121046,Tokha (SC-31) - GD Labs,pm1,6.696833,µg/m³,2025-11-06T14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3,6121046,Tokha (SC-31) - GD Labs,pm1,6.523375,µg/m³,2025-11-06T15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4,6121046,Tokha (SC-31) - GD Labs,pm1,8.390597,µg/m³,2025-11-06T16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,6121046,Tokha (SC-31) - GD Labs,um003,3330.002995,particles/cm³,2026-01-01T13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4996,6121046,Tokha (SC-31) - GD Labs,um003,3189.911165,particles/cm³,2026-01-01T14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4997,6121046,Tokha (SC-31) - GD Labs,um003,2703.277995,particles/cm³,2026-01-01T15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4998,6121046,Tokha (SC-31) - GD Labs,um003,2331.860677,particles/cm³,2026-01-01T16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4999,6121046,Tokha (SC-31) - GD Labs,um003,2864.800533,particles/cm³,2026-01-01T17:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient

In [6]:
# cleaned = cleaned[cleaned['parameter']=='pm25']
cleaned = cleaned[cleaned['parameter']=='temperature']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
3000,6121046,Tokha (SC-31) - GD Labs,temperature,21.280001,c,2025-11-06T12:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3001,6121046,Tokha (SC-31) - GD Labs,temperature,26.194292,c,2025-11-06T13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3002,6121046,Tokha (SC-31) - GD Labs,temperature,24.907375,c,2025-11-06T14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3003,6121046,Tokha (SC-31) - GD Labs,temperature,24.813208,c,2025-11-06T15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3004,6121046,Tokha (SC-31) - GD Labs,temperature,24.615111,c,2025-11-06T16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
3995,6121046,Tokha (SC-31) - GD Labs,temperature,19.623500,c,2026-01-01T13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3996,6121046,Tokha (SC-31) - GD Labs,temperature,19.656667,c,2026-01-01T14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3997,6121046,Tokha (SC-31) - GD Labs,temperature,19.548667,c,2026-01-01T15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3998,6121046,Tokha (SC-31) - GD Labs,temperature,19.390500,c,2026-01-01T16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3999,6121046,Tokha (SC-31) - GD Labs,temperature,19.174728,c,2026-01-01T17:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient

In [7]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
3000,6121046,Tokha (SC-31) - GD Labs,temperature,21.280001,c,2025-11-06 12:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2025-11-06,12:45:00
3001,6121046,Tokha (SC-31) - GD Labs,temperature,26.194292,c,2025-11-06 13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2025-11-06,13:45:00
3002,6121046,Tokha (SC-31) - GD Labs,temperature,24.907375,c,2025-11-06 14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2025-11-06,14:45:00
3003,6121046,Tokha (SC-31) - GD Labs,temperature,24.813208,c,2025-11-06 15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2025-11-06,15:45:00
3004,6121046,Tokha (SC-31) - GD Labs,temperature,24.615111,c,2025-11-06 16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2025-11-06,16:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,6121046,Tokha (SC-31) - GD Labs,temperature,19.623500,c,2026-01-01 13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-01-01,13:45:00
3996,6121046,Tokha (SC-31) - GD Labs,temperature,19.656667,c,2026-01-01 14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-01-01,14:45:00
3997,6121046,Tokha (SC-31) - GD Labs,temperature,19.548667,c,2026-01-01 15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-01-01,15:45:00
3998,6121046,Tokha (SC-31) - GD Labs,temperature,19.390500,c,2026-01-01 16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-01-01,16:45:00
3999,6121046,Tokha (SC-31) - GD Labs,temperature,19.174728,c,2026-01-01 17:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-01-01,17:45:00

In [8]:
cleaned.to_csv('cleaned_TokhaLast365days.csv', index=False)

## 2. Tokha last 30 days data cleaning

In [9]:
df30 = pd.read_csv('Tokha_last30days.csv')
df30

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,6121046,Tokha (SC-31) - GD Labs,pm1,9.7,µg/m³,2026-09-12T01:00:00Z,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
1,6121046,Tokha (SC-31) - GD Labs,pm1,8.6,µg/m³,2026-09-12T02:00:00Z,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
2,6121046,Tokha (SC-31) - GD Labs,pm1,17.3,µg/m³,2026-09-12T03:00:00Z,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3,6121046,Tokha (SC-31) - GD Labs,pm1,15.8,µg/m³,2026-09-12T04:00:00Z,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4,6121046,Tokha (SC-31) - GD Labs,pm1,6.1,µg/m³,2026-09-12T05:00:00Z,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3505,6121046,Tokha (SC-31) - GD Labs,um003,788.0,particles/cm³,2026-10-11T20:00:00Z,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3506,6121046,Tokha (SC-31) - GD Labs,um003,826.0,particles/cm³,2026-10-11T21:00:00Z,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3507,6121046,Tokha (SC-31) - GD Labs,um003,1127.0,particles/cm³,2026-10-11T22:00:00Z,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3508,6121046,Tokha (SC-31) - GD Labs,um003,1493.0,particles/cm³,2026-10-11T23:00:00Z,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3509,6121046,Tokha (SC-31) - GD Labs,um003,1823.0,particles/cm³,2026-10-12T00:00:00Z,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient

In [10]:
df30.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      3510
isMobile         3510
isMonitor        3510
owner_name          0
provider            0
dtype: int64

In [11]:
df30.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [12]:
cleaned1 =df30.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6121046,Tokha (SC-31) - GD Labs,pm1,9.7,µg/m³,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1,6121046,Tokha (SC-31) - GD Labs,pm1,8.6,µg/m³,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
2,6121046,Tokha (SC-31) - GD Labs,pm1,17.3,µg/m³,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3,6121046,Tokha (SC-31) - GD Labs,pm1,15.8,µg/m³,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4,6121046,Tokha (SC-31) - GD Labs,pm1,6.1,µg/m³,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
3505,6121046,Tokha (SC-31) - GD Labs,um003,788.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3506,6121046,Tokha (SC-31) - GD Labs,um003,826.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3507,6121046,Tokha (SC-31) - GD Labs,um003,1127.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3508,6121046,Tokha (SC-31) - GD Labs,um003,1493.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3509,6121046,Tokha (SC-31) - GD Labs,um003,1823.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient

In [14]:
# cleaned1 = cleaned1[cleaned1['parameter']=='pm25']
cleaned1 = cleaned1[cleaned1['parameter']=='temperature']
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
2106,6121046,Tokha (SC-31) - GD Labs,temperature,26.3,c,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
2107,6121046,Tokha (SC-31) - GD Labs,temperature,26.9,c,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
2108,6121046,Tokha (SC-31) - GD Labs,temperature,27.3,c,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
2109,6121046,Tokha (SC-31) - GD Labs,temperature,28.1,c,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
2110,6121046,Tokha (SC-31) - GD Labs,temperature,28.9,c,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
2803,6121046,Tokha (SC-31) - GD Labs,temperature,22.6,c,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
2804,6121046,Tokha (SC-31) - GD Labs,temperature,22.6,c,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
2805,6121046,Tokha (SC-31) - GD Labs,temperature,22.4,c,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
2806,6121046,Tokha (SC-31) - GD Labs,temperature,22.2,c,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
2807,6121046,Tokha (SC-31) - GD Labs,temperature,22.0,c,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient

In [15]:
# seperating date and time
cleaned1['datetimeLocal']=pd.to_datetime(cleaned1['datetimeLocal'])
cleaned1['date']=cleaned1['datetimeLocal'].dt.date
cleaned1['time']=cleaned1['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
2106,6121046,Tokha (SC-31) - GD Labs,temperature,26.3,c,2026-09-12 06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-09-12,06:45:00
2107,6121046,Tokha (SC-31) - GD Labs,temperature,26.9,c,2026-09-12 07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-09-12,07:45:00
2108,6121046,Tokha (SC-31) - GD Labs,temperature,27.3,c,2026-09-12 08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-09-12,08:45:00
2109,6121046,Tokha (SC-31) - GD Labs,temperature,28.1,c,2026-09-12 09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-09-12,09:45:00
2110,6121046,Tokha (SC-31) - GD Labs,temperature,28.9,c,2026-09-12 10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-09-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2803,6121046,Tokha (SC-31) - GD Labs,temperature,22.6,c,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
2804,6121046,Tokha (SC-31) - GD Labs,temperature,22.6,c,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
2805,6121046,Tokha (SC-31) - GD Labs,temperature,22.4,c,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
2806,6121046,Tokha (SC-31) - GD Labs,temperature,22.2,c,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
2807,6121046,Tokha (SC-31) - GD Labs,temperature,22.0,c,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [17]:
cleaned1.to_csv('cleaned_TokhaLast30days.csv', index=False)

## 3. Tokha last 7 days data Cleaning

In [18]:
df7 = pd.read_csv('Tokha_last1week.csv')
df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    800 non-null    int64
 1   location_name  800 non-null    str
 2   parameter      800 non-null    str
 3   value          800 non-null    float64
 4   unit           800 non-null    str
 5   datetimeUtc    800 non-null    str
 6   datetimeLocal  800 non-null    str
 7   timezone       800 non-null    str
 8   latitude       800 non-null    float64
 9   longitude      800 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     800 non-null    str
 14  provider       800 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 202.3 KB

In [19]:
df7.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      800
isMobile         800
isMonitor        800
owner_name         0
provider           0
dtype: int64

In [20]:
cleaned2 =df7.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6121046,Tokha (SC-31) - GD Labs,pm1,28.9,µg/m³,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1,6121046,Tokha (SC-31) - GD Labs,pm1,33.4,µg/m³,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
2,6121046,Tokha (SC-31) - GD Labs,pm1,34.4,µg/m³,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3,6121046,Tokha (SC-31) - GD Labs,pm1,34.7,µg/m³,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4,6121046,Tokha (SC-31) - GD Labs,pm1,34.2,µg/m³,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
795,6121046,Tokha (SC-31) - GD Labs,um003,788.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
796,6121046,Tokha (SC-31) - GD Labs,um003,826.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
797,6121046,Tokha (SC-31) - GD Labs,um003,1127.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
798,6121046,Tokha (SC-31) - GD Labs,um003,1493.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
799,6121046,Tokha (SC-31) - GD Labs,um003,1823.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient

In [21]:
# cleaned2 = cleaned2[cleaned2['parameter']=='pm25']
cleaned2 = cleaned2[cleaned2['parameter']=='temperature']
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
480,6121046,Tokha (SC-31) - GD Labs,temperature,24.8,c,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
481,6121046,Tokha (SC-31) - GD Labs,temperature,25.0,c,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
482,6121046,Tokha (SC-31) - GD Labs,temperature,25.5,c,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
483,6121046,Tokha (SC-31) - GD Labs,temperature,26.2,c,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
484,6121046,Tokha (SC-31) - GD Labs,temperature,26.8,c,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
635,6121046,Tokha (SC-31) - GD Labs,temperature,22.6,c,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
636,6121046,Tokha (SC-31) - GD Labs,temperature,22.6,c,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
637,6121046,Tokha (SC-31) - GD Labs,temperature,22.4,c,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
638,6121046,Tokha (SC-31) - GD Labs,temperature,22.2,c,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
639,6121046,Tokha (SC-31) - GD Labs,temperature,22.0,c,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient

In [22]:
# seperating date and time
cleaned2['datetimeLocal']=pd.to_datetime(cleaned2['datetimeLocal'])
cleaned2['date']=cleaned2['datetimeLocal'].dt.date
cleaned2['time']=cleaned2['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
480,6121046,Tokha (SC-31) - GD Labs,temperature,24.8,c,2026-10-05 06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-05,06:45:00
481,6121046,Tokha (SC-31) - GD Labs,temperature,25.0,c,2026-10-05 07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-05,07:45:00
482,6121046,Tokha (SC-31) - GD Labs,temperature,25.5,c,2026-10-05 08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-05,08:45:00
483,6121046,Tokha (SC-31) - GD Labs,temperature,26.2,c,2026-10-05 09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-05,09:45:00
484,6121046,Tokha (SC-31) - GD Labs,temperature,26.8,c,2026-10-05 10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-05,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,6121046,Tokha (SC-31) - GD Labs,temperature,22.6,c,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
636,6121046,Tokha (SC-31) - GD Labs,temperature,22.6,c,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
637,6121046,Tokha (SC-31) - GD Labs,temperature,22.4,c,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
638,6121046,Tokha (SC-31) - GD Labs,temperature,22.2,c,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
639,6121046,Tokha (SC-31) - GD Labs,temperature,22.0,c,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [23]:
cleaned2.to_csv('cleaned_TokhaLast7days.csv', index=False)

## 4. Tokha last 24 hours data cleaning

In [24]:
df24 = pd.read_csv('Tokha_last24hours.csv')
df24.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    120 non-null    int64
 1   location_name  120 non-null    str
 2   parameter      120 non-null    str
 3   value          120 non-null    float64
 4   unit           120 non-null    str
 5   datetimeUtc    120 non-null    str
 6   datetimeLocal  120 non-null    str
 7   timezone       120 non-null    str
 8   latitude       120 non-null    float64
 9   longitude      120 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     120 non-null    str
 14  provider       120 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 30.5 KB

In [25]:
df24.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      120
isMobile         120
isMonitor        120
owner_name         0
provider           0
dtype: int64

In [26]:
cleaned3 = df24.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6121046,Tokha (SC-31) - GD Labs,pm1,32.1,µg/m³,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1,6121046,Tokha (SC-31) - GD Labs,pm1,27.9,µg/m³,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
2,6121046,Tokha (SC-31) - GD Labs,pm1,27.1,µg/m³,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3,6121046,Tokha (SC-31) - GD Labs,pm1,23.7,µg/m³,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4,6121046,Tokha (SC-31) - GD Labs,pm1,18.7,µg/m³,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
115,6121046,Tokha (SC-31) - GD Labs,um003,788.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
116,6121046,Tokha (SC-31) - GD Labs,um003,826.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
117,6121046,Tokha (SC-31) - GD Labs,um003,1127.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
118,6121046,Tokha (SC-31) - GD Labs,um003,1493.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
119,6121046,Tokha (SC-31) - GD Labs,um003,1823.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient

In [27]:
# cleaned3 = cleaned3[cleaned3['parameter']=='pm25']
cleaned3 = cleaned3[cleaned3['parameter']=='temperature']
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
72,6121046,Tokha (SC-31) - GD Labs,temperature,21.8,c,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
73,6121046,Tokha (SC-31) - GD Labs,temperature,22.1,c,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
74,6121046,Tokha (SC-31) - GD Labs,temperature,22.4,c,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
75,6121046,Tokha (SC-31) - GD Labs,temperature,22.8,c,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
76,6121046,Tokha (SC-31) - GD Labs,temperature,23.2,c,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
77,6121046,Tokha (SC-31) - GD Labs,temperature,24.2,c,2026-10-11T11:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
78,6121046,Tokha (SC-31) - GD Labs,temperature,24.9,c,2026-10-11T12:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
79,6121046,Tokha (SC-31) - GD Labs,temperature,25.1,c,2026-10-11T13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
80,6121046,Tokha (SC-31) - GD Labs,temperature,25.1,c,2026-10-11T14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
81,6121046,Tokha (SC-31) - GD Labs,temperature,24.9,c,2026-10-11T15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
82,6121046,Tokha (SC-31) - GD Labs,temperature,24.9,c,2026-10-11T16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
83,6121046,Tokha (SC-31) - GD Labs,temperature,24.7,c,2026-10-11T17:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
84,6121046,Tokha (SC-31) - GD Labs,temperature,24.6,c,2026-10-11T18:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
85,6121046,Tokha (SC-31) - GD Labs,temperature,24.2,c,2026-10-11T19:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
86,6121046,Tokha (SC-31) - GD Labs,temperature,23.9,c,2026-10-11T20:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
87,6121046,Tokha (SC-31) - GD Labs,temperature,23.7,c,2026-10-11T21:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
88,6121046,Tokha (SC-31) - GD Labs,temperature,23.3,c,2026-10-11T22:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
89,6121046,Tokha (SC-31) - GD Labs,temperature,23.0,c,2026-10-11T23:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
90,6121046,Tokha (SC-31) - GD Labs,temperature,22.8,c,2026-10-12T00:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
91,6121046,Tokha (SC-31) - GD Labs,temperature,22.6,c,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
92,6121046,Tokha (SC-31) - GD Labs,temperature,22.6,c,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
93,6121046,Tokha (SC-31) - GD Labs,temperature,22.4,c,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
94,6121046,Tokha (SC-31) - GD Labs,temperature,22.2,c,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
95,6121046,Tokha (SC-31) - GD Labs,temperature,22.0,c,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient

In [28]:
# seperating date and time
cleaned3['datetimeLocal']=pd.to_datetime(cleaned3['datetimeLocal'])
cleaned3['date']=cleaned3['datetimeLocal'].dt.date
cleaned3['time']=cleaned3['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
72,6121046,Tokha (SC-31) - GD Labs,temperature,21.8,c,2026-10-11 06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,06:45:00
73,6121046,Tokha (SC-31) - GD Labs,temperature,22.1,c,2026-10-11 07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,07:45:00
74,6121046,Tokha (SC-31) - GD Labs,temperature,22.4,c,2026-10-11 08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,08:45:00
75,6121046,Tokha (SC-31) - GD Labs,temperature,22.8,c,2026-10-11 09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,09:45:00
76,6121046,Tokha (SC-31) - GD Labs,temperature,23.2,c,2026-10-11 10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,10:45:00
77,6121046,Tokha (SC-31) - GD Labs,temperature,24.2,c,2026-10-11 11:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,11:45:00
78,6121046,Tokha (SC-31) - GD Labs,temperature,24.9,c,2026-10-11 12:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,12:45:00
79,6121046,Tokha (SC-31) - GD Labs,temperature,25.1,c,2026-10-11 13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,13:45:00
80,6121046,Tokha (SC-31) - GD Labs,temperature,25.1,c,2026-10-11 14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,14:45:00
81,6121046,Tokha (SC-31) - GD Labs,temperature,24.9,c,2026-10-11 15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,15:45:00
82,6121046,Tokha (SC-31) - GD Labs,temperature,24.9,c,2026-10-11 16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,16:45:00
83,6121046,Tokha (SC-31) - GD Labs,temperature,24.7,c,2026-10-11 17:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,17:45:00
84,6121046,Tokha (SC-31) - GD Labs,temperature,24.6,c,2026-10-11 18:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,18:45:00
85,6121046,Tokha (SC-31) - GD Labs,temperature,24.2,c,2026-10-11 19:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,19:45:00
86,6121046,Tokha (SC-31) - GD Labs,temperature,23.9,c,2026-10-11 20:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,20:45:00
87,6121046,Tokha (SC-31) - GD Labs,temperature,23.7,c,2026-10-11 21:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,21:45:00
88,6121046,Tokha (SC-31) - GD Labs,temperature,23.3,c,2026-10-11 22:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,22:45:00
89,6121046,Tokha (SC-31) - GD Labs,temperature,23.0,c,2026-10-11 23:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-11,23:45:00
90,6121046,Tokha (SC-31) - GD Labs,temperature,22.8,c,2026-10-12 00:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,00:45:00
91,6121046,Tokha (SC-31) - GD Labs,temperature,22.6,c,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
92,6121046,Tokha (SC-31) - GD Labs,temperature,22.6,c,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
93,6121046,Tokha (SC-31) - GD Labs,temperature,22.4,c,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
94,6121046,Tokha (SC-31) - GD Labs,temperature,22.2,c,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
95,6121046,Tokha (SC-31) - GD Labs,temperature,22.0,c,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [29]:
cleaned3.to_csv('cleaned_TokhaLast24hours.csv', index=False)