In [1]:
import pandas as pd

## 1. Tokha last 365 days data cleaning

In [2]:
df365 = pd.read_csv('Tokha_last365days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.2 MB

In [3]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [4]:
df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [5]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6121046,Tokha (SC-31) - GD Labs,pm1,23.830000,µg/m³,2025-11-06T12:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1,6121046,Tokha (SC-31) - GD Labs,pm1,10.654375,µg/m³,2025-11-06T13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
2,6121046,Tokha (SC-31) - GD Labs,pm1,6.696833,µg/m³,2025-11-06T14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3,6121046,Tokha (SC-31) - GD Labs,pm1,6.523375,µg/m³,2025-11-06T15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4,6121046,Tokha (SC-31) - GD Labs,pm1,8.390597,µg/m³,2025-11-06T16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,6121046,Tokha (SC-31) - GD Labs,um003,3330.002995,particles/cm³,2026-01-01T13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4996,6121046,Tokha (SC-31) - GD Labs,um003,3189.911165,particles/cm³,2026-01-01T14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4997,6121046,Tokha (SC-31) - GD Labs,um003,2703.277995,particles/cm³,2026-01-01T15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4998,6121046,Tokha (SC-31) - GD Labs,um003,2331.860677,particles/cm³,2026-01-01T16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4999,6121046,Tokha (SC-31) - GD Labs,um003,2864.800533,particles/cm³,2026-01-01T17:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient

In [6]:
cleaned = cleaned[cleaned['parameter']=='pm25']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
1000,6121046,Tokha (SC-31) - GD Labs,pm25,38.500000,µg/m³,2025-11-06T12:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1001,6121046,Tokha (SC-31) - GD Labs,pm25,24.792000,µg/m³,2025-11-06T13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1002,6121046,Tokha (SC-31) - GD Labs,pm25,20.204250,µg/m³,2025-11-06T14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1003,6121046,Tokha (SC-31) - GD Labs,pm25,19.634167,µg/m³,2025-11-06T15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1004,6121046,Tokha (SC-31) - GD Labs,pm25,20.873194,µg/m³,2025-11-06T16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
1995,6121046,Tokha (SC-31) - GD Labs,pm25,76.046667,µg/m³,2026-01-01T13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1996,6121046,Tokha (SC-31) - GD Labs,pm25,73.958167,µg/m³,2026-01-01T14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1997,6121046,Tokha (SC-31) - GD Labs,pm25,62.536000,µg/m³,2026-01-01T15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1998,6121046,Tokha (SC-31) - GD Labs,pm25,53.916167,µg/m³,2026-01-01T16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1999,6121046,Tokha (SC-31) - GD Labs,pm25,65.736000,µg/m³,2026-01-01T17:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient

In [7]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
1000,6121046,Tokha (SC-31) - GD Labs,pm25,38.500000,µg/m³,2025-11-06 12:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2025-11-06,12:45:00
1001,6121046,Tokha (SC-31) - GD Labs,pm25,24.792000,µg/m³,2025-11-06 13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2025-11-06,13:45:00
1002,6121046,Tokha (SC-31) - GD Labs,pm25,20.204250,µg/m³,2025-11-06 14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2025-11-06,14:45:00
1003,6121046,Tokha (SC-31) - GD Labs,pm25,19.634167,µg/m³,2025-11-06 15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2025-11-06,15:45:00
1004,6121046,Tokha (SC-31) - GD Labs,pm25,20.873194,µg/m³,2025-11-06 16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2025-11-06,16:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,6121046,Tokha (SC-31) - GD Labs,pm25,76.046667,µg/m³,2026-01-01 13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-01-01,13:45:00
1996,6121046,Tokha (SC-31) - GD Labs,pm25,73.958167,µg/m³,2026-01-01 14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-01-01,14:45:00
1997,6121046,Tokha (SC-31) - GD Labs,pm25,62.536000,µg/m³,2026-01-01 15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-01-01,15:45:00
1998,6121046,Tokha (SC-31) - GD Labs,pm25,53.916167,µg/m³,2026-01-01 16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-01-01,16:45:00
1999,6121046,Tokha (SC-31) - GD Labs,pm25,65.736000,µg/m³,2026-01-01 17:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-01-01,17:45:00

In [8]:
cleaned.to_csv('cleaned_TokhaLast365days.csv', index=False)

## 2. Tokha last 30 days data cleaning

In [9]:
df30 = pd.read_csv('Tokha_last30days.csv')
df30

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,6121046,Tokha (SC-31) - GD Labs,pm1,9.7,µg/m³,2026-09-12T01:00:00Z,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
1,6121046,Tokha (SC-31) - GD Labs,pm1,8.6,µg/m³,2026-09-12T02:00:00Z,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
2,6121046,Tokha (SC-31) - GD Labs,pm1,17.3,µg/m³,2026-09-12T03:00:00Z,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3,6121046,Tokha (SC-31) - GD Labs,pm1,15.8,µg/m³,2026-09-12T04:00:00Z,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4,6121046,Tokha (SC-31) - GD Labs,pm1,6.1,µg/m³,2026-09-12T05:00:00Z,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3505,6121046,Tokha (SC-31) - GD Labs,um003,788.0,particles/cm³,2026-10-11T20:00:00Z,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3506,6121046,Tokha (SC-31) - GD Labs,um003,826.0,particles/cm³,2026-10-11T21:00:00Z,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3507,6121046,Tokha (SC-31) - GD Labs,um003,1127.0,particles/cm³,2026-10-11T22:00:00Z,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3508,6121046,Tokha (SC-31) - GD Labs,um003,1493.0,particles/cm³,2026-10-11T23:00:00Z,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3509,6121046,Tokha (SC-31) - GD Labs,um003,1823.0,particles/cm³,2026-10-12T00:00:00Z,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient

In [10]:
df30.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      3510
isMobile         3510
isMonitor        3510
owner_name          0
provider            0
dtype: int64

In [11]:
df30.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [12]:
cleaned1 =df30.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6121046,Tokha (SC-31) - GD Labs,pm1,9.7,µg/m³,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1,6121046,Tokha (SC-31) - GD Labs,pm1,8.6,µg/m³,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
2,6121046,Tokha (SC-31) - GD Labs,pm1,17.3,µg/m³,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3,6121046,Tokha (SC-31) - GD Labs,pm1,15.8,µg/m³,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4,6121046,Tokha (SC-31) - GD Labs,pm1,6.1,µg/m³,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
3505,6121046,Tokha (SC-31) - GD Labs,um003,788.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3506,6121046,Tokha (SC-31) - GD Labs,um003,826.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3507,6121046,Tokha (SC-31) - GD Labs,um003,1127.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3508,6121046,Tokha (SC-31) - GD Labs,um003,1493.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3509,6121046,Tokha (SC-31) - GD Labs,um003,1823.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient

In [13]:
cleaned1 = cleaned1[cleaned1['parameter']=='pm25']
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
702,6121046,Tokha (SC-31) - GD Labs,pm25,20.4,µg/m³,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
703,6121046,Tokha (SC-31) - GD Labs,pm25,20.2,µg/m³,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
704,6121046,Tokha (SC-31) - GD Labs,pm25,27.9,µg/m³,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
705,6121046,Tokha (SC-31) - GD Labs,pm25,25.6,µg/m³,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
706,6121046,Tokha (SC-31) - GD Labs,pm25,14.2,µg/m³,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
1399,6121046,Tokha (SC-31) - GD Labs,pm25,26.1,µg/m³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1400,6121046,Tokha (SC-31) - GD Labs,pm25,27.1,µg/m³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1401,6121046,Tokha (SC-31) - GD Labs,pm25,33.5,µg/m³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1402,6121046,Tokha (SC-31) - GD Labs,pm25,39.4,µg/m³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1403,6121046,Tokha (SC-31) - GD Labs,pm25,43.1,µg/m³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient

In [14]:
# seperating date and time
cleaned1['datetimeLocal']=pd.to_datetime(cleaned1['datetimeLocal'])
cleaned1['date']=cleaned1['datetimeLocal'].dt.date
cleaned1['time']=cleaned1['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
702,6121046,Tokha (SC-31) - GD Labs,pm25,20.4,µg/m³,2026-09-12 06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-09-12,06:45:00
703,6121046,Tokha (SC-31) - GD Labs,pm25,20.2,µg/m³,2026-09-12 07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-09-12,07:45:00
704,6121046,Tokha (SC-31) - GD Labs,pm25,27.9,µg/m³,2026-09-12 08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-09-12,08:45:00
705,6121046,Tokha (SC-31) - GD Labs,pm25,25.6,µg/m³,2026-09-12 09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-09-12,09:45:00
706,6121046,Tokha (SC-31) - GD Labs,pm25,14.2,µg/m³,2026-09-12 10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-09-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1399,6121046,Tokha (SC-31) - GD Labs,pm25,26.1,µg/m³,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
1400,6121046,Tokha (SC-31) - GD Labs,pm25,27.1,µg/m³,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
1401,6121046,Tokha (SC-31) - GD Labs,pm25,33.5,µg/m³,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
1402,6121046,Tokha (SC-31) - GD Labs,pm25,39.4,µg/m³,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
1403,6121046,Tokha (SC-31) - GD Labs,pm25,43.1,µg/m³,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [15]:
cleaned1.to_csv('cleaned_TokhaLast30days.csv', index=False)

## 3. Tokha last 7 days data Cleaning

In [16]:
df7 = pd.read_csv('Tokha_last1week.csv')
df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    800 non-null    int64
 1   location_name  800 non-null    str
 2   parameter      800 non-null    str
 3   value          800 non-null    float64
 4   unit           800 non-null    str
 5   datetimeUtc    800 non-null    str
 6   datetimeLocal  800 non-null    str
 7   timezone       800 non-null    str
 8   latitude       800 non-null    float64
 9   longitude      800 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     800 non-null    str
 14  provider       800 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 202.3 KB

In [17]:
df7.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      800
isMobile         800
isMonitor        800
owner_name         0
provider           0
dtype: int64

In [18]:
cleaned2 =df7.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6121046,Tokha (SC-31) - GD Labs,pm1,28.9,µg/m³,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1,6121046,Tokha (SC-31) - GD Labs,pm1,33.4,µg/m³,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
2,6121046,Tokha (SC-31) - GD Labs,pm1,34.4,µg/m³,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3,6121046,Tokha (SC-31) - GD Labs,pm1,34.7,µg/m³,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4,6121046,Tokha (SC-31) - GD Labs,pm1,34.2,µg/m³,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
795,6121046,Tokha (SC-31) - GD Labs,um003,788.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
796,6121046,Tokha (SC-31) - GD Labs,um003,826.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
797,6121046,Tokha (SC-31) - GD Labs,um003,1127.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
798,6121046,Tokha (SC-31) - GD Labs,um003,1493.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
799,6121046,Tokha (SC-31) - GD Labs,um003,1823.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient

In [19]:
cleaned2 = cleaned2[cleaned2['parameter']=='pm25']
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
160,6121046,Tokha (SC-31) - GD Labs,pm25,46.2,µg/m³,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
161,6121046,Tokha (SC-31) - GD Labs,pm25,54.2,µg/m³,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
162,6121046,Tokha (SC-31) - GD Labs,pm25,56.2,µg/m³,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
163,6121046,Tokha (SC-31) - GD Labs,pm25,58.0,µg/m³,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
164,6121046,Tokha (SC-31) - GD Labs,pm25,57.6,µg/m³,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
315,6121046,Tokha (SC-31) - GD Labs,pm25,26.1,µg/m³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
316,6121046,Tokha (SC-31) - GD Labs,pm25,27.1,µg/m³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
317,6121046,Tokha (SC-31) - GD Labs,pm25,33.5,µg/m³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
318,6121046,Tokha (SC-31) - GD Labs,pm25,39.4,µg/m³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
319,6121046,Tokha (SC-31) - GD Labs,pm25,43.1,µg/m³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient

In [20]:
# seperating date and time
cleaned2['datetimeLocal']=pd.to_datetime(cleaned2['datetimeLocal'])
cleaned2['date']=cleaned2['datetimeLocal'].dt.date
cleaned2['time']=cleaned2['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
160,6121046,Tokha (SC-31) - GD Labs,pm25,46.2,µg/m³,2026-10-05 06:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-05,06:45:00
161,6121046,Tokha (SC-31) - GD Labs,pm25,54.2,µg/m³,2026-10-05 07:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-05,07:45:00
162,6121046,Tokha (SC-31) - GD Labs,pm25,56.2,µg/m³,2026-10-05 08:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-05,08:45:00
163,6121046,Tokha (SC-31) - GD Labs,pm25,58.0,µg/m³,2026-10-05 09:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-05,09:45:00
164,6121046,Tokha (SC-31) - GD Labs,pm25,57.6,µg/m³,2026-10-05 10:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-05,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,6121046,Tokha (SC-31) - GD Labs,pm25,26.1,µg/m³,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
316,6121046,Tokha (SC-31) - GD Labs,pm25,27.1,µg/m³,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
317,6121046,Tokha (SC-31) - GD Labs,pm25,33.5,µg/m³,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
318,6121046,Tokha (SC-31) - GD Labs,pm25,39.4,µg/m³,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
319,6121046,Tokha (SC-31) - GD Labs,pm25,43.1,µg/m³,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [21]:
cleaned2.to_csv('cleaned_TokhaLast7days.csv', index=False)