In [1]:
import pandas as pd

## 1. Tokha last 365 days data cleaning

In [2]:
df365 = pd.read_csv('Tokha_last365days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.2 MB

In [3]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [4]:
df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [5]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6121046,Tokha (SC-31) - GD Labs,pm1,23.830000,µg/m³,2025-11-06T12:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1,6121046,Tokha (SC-31) - GD Labs,pm1,10.654375,µg/m³,2025-11-06T13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
2,6121046,Tokha (SC-31) - GD Labs,pm1,6.696833,µg/m³,2025-11-06T14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
3,6121046,Tokha (SC-31) - GD Labs,pm1,6.523375,µg/m³,2025-11-06T15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4,6121046,Tokha (SC-31) - GD Labs,pm1,8.390597,µg/m³,2025-11-06T16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,6121046,Tokha (SC-31) - GD Labs,um003,3330.002995,particles/cm³,2026-01-01T13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4996,6121046,Tokha (SC-31) - GD Labs,um003,3189.911165,particles/cm³,2026-01-01T14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4997,6121046,Tokha (SC-31) - GD Labs,um003,2703.277995,particles/cm³,2026-01-01T15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4998,6121046,Tokha (SC-31) - GD Labs,um003,2331.860677,particles/cm³,2026-01-01T16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
4999,6121046,Tokha (SC-31) - GD Labs,um003,2864.800533,particles/cm³,2026-01-01T17:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient

In [6]:
cleaned = cleaned[cleaned['parameter']=='pm25']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
1000,6121046,Tokha (SC-31) - GD Labs,pm25,38.500000,µg/m³,2025-11-06T12:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1001,6121046,Tokha (SC-31) - GD Labs,pm25,24.792000,µg/m³,2025-11-06T13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1002,6121046,Tokha (SC-31) - GD Labs,pm25,20.204250,µg/m³,2025-11-06T14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1003,6121046,Tokha (SC-31) - GD Labs,pm25,19.634167,µg/m³,2025-11-06T15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1004,6121046,Tokha (SC-31) - GD Labs,pm25,20.873194,µg/m³,2025-11-06T16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
1995,6121046,Tokha (SC-31) - GD Labs,pm25,76.046667,µg/m³,2026-01-01T13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1996,6121046,Tokha (SC-31) - GD Labs,pm25,73.958167,µg/m³,2026-01-01T14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1997,6121046,Tokha (SC-31) - GD Labs,pm25,62.536000,µg/m³,2026-01-01T15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1998,6121046,Tokha (SC-31) - GD Labs,pm25,53.916167,µg/m³,2026-01-01T16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient
1999,6121046,Tokha (SC-31) - GD Labs,pm25,65.736000,µg/m³,2026-01-01T17:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient

In [7]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
1000,6121046,Tokha (SC-31) - GD Labs,pm25,38.500000,µg/m³,2025-11-06 12:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2025-11-06,12:45:00
1001,6121046,Tokha (SC-31) - GD Labs,pm25,24.792000,µg/m³,2025-11-06 13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2025-11-06,13:45:00
1002,6121046,Tokha (SC-31) - GD Labs,pm25,20.204250,µg/m³,2025-11-06 14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2025-11-06,14:45:00
1003,6121046,Tokha (SC-31) - GD Labs,pm25,19.634167,µg/m³,2025-11-06 15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2025-11-06,15:45:00
1004,6121046,Tokha (SC-31) - GD Labs,pm25,20.873194,µg/m³,2025-11-06 16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2025-11-06,16:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,6121046,Tokha (SC-31) - GD Labs,pm25,76.046667,µg/m³,2026-01-01 13:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-01-01,13:45:00
1996,6121046,Tokha (SC-31) - GD Labs,pm25,73.958167,µg/m³,2026-01-01 14:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-01-01,14:45:00
1997,6121046,Tokha (SC-31) - GD Labs,pm25,62.536000,µg/m³,2026-01-01 15:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-01-01,15:45:00
1998,6121046,Tokha (SC-31) - GD Labs,pm25,53.916167,µg/m³,2026-01-01 16:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-01-01,16:45:00
1999,6121046,Tokha (SC-31) - GD Labs,pm25,65.736000,µg/m³,2026-01-01 17:45:00+05:45,Asia/Kathmandu,27.756028,85.326846,Green Decision Labs and Research,AirGradient,2026-01-01,17:45:00

In [8]:
cleaned.to_csv('cleaned_TokhaLast365days.csv', index=False)