In [1]:
import pandas as pd

## 1. Tyanglaphant last 365 days data cleaning

In [2]:
df365 = pd.read_csv('Tyanglaphant_last365days.csv')
df365.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    5000 non-null   int64
 1   location_name  5000 non-null   str
 2   parameter      5000 non-null   str
 3   value          5000 non-null   float64
 4   unit           5000 non-null   str
 5   datetimeUtc    5000 non-null   str
 6   datetimeLocal  5000 non-null   str
 7   timezone       5000 non-null   str
 8   latitude       5000 non-null   float64
 9   longitude      5000 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     5000 non-null   str
 14  provider       5000 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 1.3 MB

In [3]:
df365.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      5000
isMobile         5000
isMonitor        5000
owner_name          0
provider            0
dtype: int64

In [4]:
df365.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [5]:
cleaned =df365.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,14.111104,µg/m³,2025-10-14T12:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
1,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,10.595500,µg/m³,2025-10-14T13:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
2,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,16.655227,µg/m³,2025-10-14T14:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
3,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,17.146292,µg/m³,2025-10-14T15:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
4,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,18.712917,µg/m³,2025-10-14T16:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
4995,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,4329.377995,particles/cm³,2025-12-03T06:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
4996,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,5118.461491,particles/cm³,2025-12-03T07:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
4997,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,5056.814160,particles/cm³,2025-12-03T08:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
4998,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,3858.091829,particles/cm³,2025-12-03T09:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
4999,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,4014.774837,particles/cm³,2025-12-03T10:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient

In [6]:
# cleaned = cleaned[cleaned['parameter']=='pm25']
# cleaned = cleaned[cleaned['parameter']=='temperature']
cleaned = cleaned[cleaned['parameter']=='relativehumidity']
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
2000,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,44.470001,%,2025-10-14T11:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
2001,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,37.172519,%,2025-10-14T12:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
2002,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,34.310000,%,2025-10-14T13:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
2003,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,35.213500,%,2025-10-14T14:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
2004,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,37.111125,%,2025-10-14T15:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
2995,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,58.105000,%,2025-12-03T06:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
2996,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,58.557833,%,2025-12-03T07:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
2997,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,56.699833,%,2025-12-03T08:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
2998,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,53.405500,%,2025-12-03T09:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
2999,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,49.946000,%,2025-12-03T10:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient

In [7]:
# seperating date and time
cleaned['datetimeLocal']=pd.to_datetime(cleaned['datetimeLocal'])
cleaned['date']=cleaned['datetimeLocal'].dt.date
cleaned['time']=cleaned['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
2000,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,44.470001,%,2025-10-14 11:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2025-10-14,11:45:00
2001,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,37.172519,%,2025-10-14 12:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2025-10-14,12:45:00
2002,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,34.310000,%,2025-10-14 13:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2025-10-14,13:45:00
2003,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,35.213500,%,2025-10-14 14:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2025-10-14,14:45:00
2004,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,37.111125,%,2025-10-14 15:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2025-10-14,15:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,58.105000,%,2025-12-03 06:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2025-12-03,06:45:00
2996,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,58.557833,%,2025-12-03 07:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2025-12-03,07:45:00
2997,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,56.699833,%,2025-12-03 08:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2025-12-03,08:45:00
2998,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,53.405500,%,2025-12-03 09:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2025-12-03,09:45:00
2999,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,49.946000,%,2025-12-03 10:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2025-12-03,10:45:00

In [8]:
cleaned.to_csv('cleaned_TyanglaphatLast365days.csv', index=False)

## 2. Tyanglaphat last 30 days data cleaning

In [9]:
df30 = pd.read_csv('Tyanglaphant_last30days.csv')
df30

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,7.7,µg/m³,2026-09-12T01:00:00Z,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
1,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,13.5,µg/m³,2026-09-12T02:00:00Z,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
2,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,18.3,µg/m³,2026-09-12T03:00:00Z,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,14.0,µg/m³,2026-09-12T04:00:00Z,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
4,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,18.7,µg/m³,2026-09-12T05:00:00Z,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3590,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1070.0,particles/cm³,2026-10-11T20:00:00Z,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3591,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1134.0,particles/cm³,2026-10-11T21:00:00Z,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3592,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1243.0,particles/cm³,2026-10-11T22:00:00Z,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3593,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1234.0,particles/cm³,2026-10-11T23:00:00Z,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient
3594,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1243.0,particles/cm³,2026-10-12T00:00:00Z,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,NaN,NaN,NaN,Green Decision Labs and Research,AirGradient

In [10]:
df30.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      3595
isMobile         3595
isMonitor        3595
owner_name          0
provider            0
dtype: int64

In [11]:
df30.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [12]:
cleaned1 =df30.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,7.7,µg/m³,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
1,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,13.5,µg/m³,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
2,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,18.3,µg/m³,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
3,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,14.0,µg/m³,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
4,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,18.7,µg/m³,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
3590,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1070.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
3591,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1134.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
3592,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1243.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
3593,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1234.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
3594,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1243.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient

In [13]:
# cleaned1 = cleaned1[cleaned1['parameter']=='pm25']
# cleaned1 = cleaned1[cleaned1['parameter']=='temperature']
cleaned1 = cleaned1[cleaned1['parameter']=='relativehumidity']
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
1438,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,56.0,%,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
1439,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,55.0,%,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
1440,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,52.0,%,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
1441,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,49.0,%,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
1442,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,49.0,%,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
2152,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,50.0,%,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
2153,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,51.0,%,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
2154,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,52.0,%,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
2155,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,52.0,%,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
2156,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,54.0,%,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient

In [14]:
# seperating date and time
cleaned1['datetimeLocal']=pd.to_datetime(cleaned1['datetimeLocal'])
cleaned1['date']=cleaned1['datetimeLocal'].dt.date
cleaned1['time']=cleaned1['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned1

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
1438,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,56.0,%,2026-09-12 06:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-09-12,06:45:00
1439,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,55.0,%,2026-09-12 07:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-09-12,07:45:00
1440,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,52.0,%,2026-09-12 08:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-09-12,08:45:00
1441,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,49.0,%,2026-09-12 09:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-09-12,09:45:00
1442,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,49.0,%,2026-09-12 10:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-09-12,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2152,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,50.0,%,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
2153,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,51.0,%,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
2154,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,52.0,%,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
2155,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,52.0,%,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
2156,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,54.0,%,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [15]:
cleaned1.to_csv('cleaned_TyanglaphatLast30days.csv', index=False)

## 3. Tyanglaphat last 7 days data cleaning

In [17]:
df7 = pd.read_csv('Tyanglaphant_last1week.csv')
df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 835 entries, 0 to 834
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    835 non-null    int64
 1   location_name  835 non-null    str
 2   parameter      835 non-null    str
 3   value          835 non-null    float64
 4   unit           835 non-null    str
 5   datetimeUtc    835 non-null    str
 6   datetimeLocal  835 non-null    str
 7   timezone       835 non-null    str
 8   latitude       835 non-null    float64
 9   longitude      835 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     835 non-null    str
 14  provider       835 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 217.7 KB

In [18]:
df7.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      835
isMobile         835
isMonitor        835
owner_name         0
provider           0
dtype: int64

In [19]:
cleaned2 =df7.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,29.2,µg/m³,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
1,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,31.3,µg/m³,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
2,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,33.0,µg/m³,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
3,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,31.7,µg/m³,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
4,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,25.9,µg/m³,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
830,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1070.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
831,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1134.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
832,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1243.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
833,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1234.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
834,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1243.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient

In [20]:
# cleaned2 = cleaned2[cleaned2['parameter']=='pm25']
# cleaned2 = cleaned2[cleaned2['parameter']=='temperature']
cleaned2 = cleaned2[cleaned2['parameter']=='relativehumidity']
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
334,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,54.0,%,2026-10-05T06:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
335,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,53.0,%,2026-10-05T07:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
336,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,51.0,%,2026-10-05T08:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
337,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,50.0,%,2026-10-05T09:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
338,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,47.0,%,2026-10-05T10:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
496,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,50.0,%,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
497,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,51.0,%,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
498,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,52.0,%,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
499,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,52.0,%,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
500,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,54.0,%,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient

In [21]:
# seperating date and time
cleaned2['datetimeLocal']=pd.to_datetime(cleaned2['datetimeLocal'])
cleaned2['date']=cleaned2['datetimeLocal'].dt.date
cleaned2['time']=cleaned2['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned2

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
334,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,54.0,%,2026-10-05 06:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-05,06:45:00
335,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,53.0,%,2026-10-05 07:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-05,07:45:00
336,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,51.0,%,2026-10-05 08:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-05,08:45:00
337,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,50.0,%,2026-10-05 09:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-05,09:45:00
338,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,47.0,%,2026-10-05 10:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-05,10:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,50.0,%,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
497,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,51.0,%,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
498,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,52.0,%,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
499,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,52.0,%,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
500,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,54.0,%,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [23]:
cleaned2.to_csv('cleaned_TyanglaphatLast7days.csv', index=False)

## 4. Tyanglaphat last 24 hours data cleaning

In [24]:
df24 = pd.read_csv('Tyanglaphant_last24hours.csv')
df24.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    120 non-null    int64
 1   location_name  120 non-null    str
 2   parameter      120 non-null    str
 3   value          120 non-null    float64
 4   unit           120 non-null    str
 5   datetimeUtc    120 non-null    str
 6   datetimeLocal  120 non-null    str
 7   timezone       120 non-null    str
 8   latitude       120 non-null    float64
 9   longitude      120 non-null    float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     120 non-null    str
 14  provider       120 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 31.4 KB

In [25]:
df24.isnull().sum()

location_id        0
location_name      0
parameter          0
value              0
unit               0
datetimeUtc        0
datetimeLocal      0
timezone           0
latitude           0
longitude          0
country_iso      120
isMobile         120
isMonitor        120
owner_name         0
provider           0
dtype: int64

In [26]:
cleaned3 = df24.drop(columns=['country_iso', 'isMobile', 'isMonitor', 'datetimeUtc'], inplace=False)
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,21.8,µg/m³,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
1,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,20.3,µg/m³,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
2,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,22.5,µg/m³,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
3,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,24.3,µg/m³,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
4,6094777,Tyanglaphat (SC - 21) - GD Labs,pm1,25.1,µg/m³,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...
115,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1070.0,particles/cm³,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
116,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1134.0,particles/cm³,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
117,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1243.0,particles/cm³,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
118,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1234.0,particles/cm³,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
119,6094777,Tyanglaphat (SC - 21) - GD Labs,um003,1243.0,particles/cm³,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient

In [27]:
# cleaned3 = cleaned3[cleaned3['parameter']=='pm25']
# cleaned3 = cleaned3[cleaned3['parameter']=='temperature']
cleaned3 = cleaned3[cleaned3['parameter']=='relativehumidity']
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider
48,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,54.0,%,2026-10-11T06:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
49,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,54.0,%,2026-10-11T07:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
50,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,52.0,%,2026-10-11T08:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
51,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,51.0,%,2026-10-11T09:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
52,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,50.0,%,2026-10-11T10:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
53,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,44.0,%,2026-10-11T11:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
54,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,43.0,%,2026-10-11T12:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
55,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,42.0,%,2026-10-11T13:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
56,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,42.0,%,2026-10-11T14:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
57,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,42.0,%,2026-10-11T15:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
58,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,41.0,%,2026-10-11T16:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
59,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,44.0,%,2026-10-11T17:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
60,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,47.0,%,2026-10-11T18:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
61,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,47.0,%,2026-10-11T19:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
62,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,48.0,%,2026-10-11T20:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
63,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,48.0,%,2026-10-11T21:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
64,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,49.0,%,2026-10-11T22:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
65,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,50.0,%,2026-10-11T23:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
66,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,50.0,%,2026-10-12T00:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
67,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,50.0,%,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
68,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,51.0,%,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
69,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,52.0,%,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
70,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,52.0,%,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient
71,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,54.0,%,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient

In [28]:
# seperating date and time
cleaned3['datetimeLocal']=pd.to_datetime(cleaned3['datetimeLocal'])
cleaned3['date']=cleaned3['datetimeLocal'].dt.date
cleaned3['time']=cleaned3['datetimeLocal'].dt.strftime('%H:%M:%S')
cleaned3

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,owner_name,provider,date,time
48,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,54.0,%,2026-10-11 06:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,06:45:00
49,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,54.0,%,2026-10-11 07:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,07:45:00
50,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,52.0,%,2026-10-11 08:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,08:45:00
51,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,51.0,%,2026-10-11 09:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,09:45:00
52,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,50.0,%,2026-10-11 10:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,10:45:00
53,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,44.0,%,2026-10-11 11:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,11:45:00
54,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,43.0,%,2026-10-11 12:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,12:45:00
55,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,42.0,%,2026-10-11 13:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,13:45:00
56,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,42.0,%,2026-10-11 14:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,14:45:00
57,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,42.0,%,2026-10-11 15:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,15:45:00
58,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,41.0,%,2026-10-11 16:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,16:45:00
59,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,44.0,%,2026-10-11 17:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,17:45:00
60,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,47.0,%,2026-10-11 18:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,18:45:00
61,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,47.0,%,2026-10-11 19:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,19:45:00
62,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,48.0,%,2026-10-11 20:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,20:45:00
63,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,48.0,%,2026-10-11 21:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,21:45:00
64,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,49.0,%,2026-10-11 22:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,22:45:00
65,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,50.0,%,2026-10-11 23:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-11,23:45:00
66,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,50.0,%,2026-10-12 00:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-12,00:45:00
67,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,50.0,%,2026-10-12 01:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-12,01:45:00
68,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,51.0,%,2026-10-12 02:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-12,02:45:00
69,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,52.0,%,2026-10-12 03:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-12,03:45:00
70,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,52.0,%,2026-10-12 04:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-12,04:45:00
71,6094777,Tyanglaphat (SC - 21) - GD Labs,relativehumidity,54.0,%,2026-10-12 05:45:00+05:45,Asia/Kathmandu,27.686165,85.28026,Green Decision Labs and Research,AirGradient,2026-10-12,05:45:00

In [29]:
cleaned3.to_csv('cleaned_TyanglaphantLast24hours.csv', index=False)