## 1. Bagdol last 30 days data cleaning

In [2]:
import pandas as pd

In [7]:
df30 = pd.read_csv('OpenAQdataset/Bagdol_last30days.csv')
df30

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,6230465,Bagdol,pm1,13.3,µg/m³,2026-09-12T01:00:00Z,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
1,6230465,Bagdol,pm1,20.1,µg/m³,2026-09-12T02:00:00Z,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
2,6230465,Bagdol,pm1,22.0,µg/m³,2026-09-12T03:00:00Z,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
3,6230465,Bagdol,pm1,23.0,µg/m³,2026-09-12T04:00:00Z,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
4,6230465,Bagdol,pm1,17.6,µg/m³,2026-09-12T05:00:00Z,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3590,6230465,Bagdol,um003,1279.0,particles/cm³,2026-10-11T20:00:00Z,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
3591,6230465,Bagdol,um003,1193.0,particles/cm³,2026-10-11T21:00:00Z,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
3592,6230465,Bagdol,um003,1174.0,particles/cm³,2026-10-11T22:00:00Z,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
3593,6230465,Bagdol,um003,1218.0,particles/cm³,2026-10-11T23:00:00Z,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient
3594,6230465,Bagdol,um003,1276.0,particles/cm³,2026-10-12T00:00:00Z,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,NaN,NaN,NaN,KIAS,AirGradient

In [8]:
df30.info()

<class 'pandas.DataFrame'>
RangeIndex: 3595 entries, 0 to 3594
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    3595 non-null   int64
 1   location_name  3595 non-null   str
 2   parameter      3595 non-null   str
 3   value          3595 non-null   float64
 4   unit           3595 non-null   str
 5   datetimeUtc    3595 non-null   str
 6   datetimeLocal  3595 non-null   str
 7   timezone       3595 non-null   str
 8   latitude       3595 non-null   float64
 9   longitude      3595 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     3595 non-null   str
 14  provider       3595 non-null   str
dtypes: float64(6), int64(1), str(8)
memory usage: 750.7 KB

In [9]:
df30.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      3595
isMobile         3595
isMonitor        3595
owner_name          0
provider            0
dtype: int64

In [11]:
df30.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='str')

In [12]:
df30.drop(columns=['country_iso', 'isMobile', 'isMonitor'], inplace=False)

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,owner_name,provider
0,6230465,Bagdol,pm1,13.3,µg/m³,2026-09-12T01:00:00Z,2026-09-12T06:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
1,6230465,Bagdol,pm1,20.1,µg/m³,2026-09-12T02:00:00Z,2026-09-12T07:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
2,6230465,Bagdol,pm1,22.0,µg/m³,2026-09-12T03:00:00Z,2026-09-12T08:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
3,6230465,Bagdol,pm1,23.0,µg/m³,2026-09-12T04:00:00Z,2026-09-12T09:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
4,6230465,Bagdol,pm1,17.6,µg/m³,2026-09-12T05:00:00Z,2026-09-12T10:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
...,...,...,...,...,...,...,...,...,...,...,...,...
3590,6230465,Bagdol,um003,1279.0,particles/cm³,2026-10-11T20:00:00Z,2026-10-12T01:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
3591,6230465,Bagdol,um003,1193.0,particles/cm³,2026-10-11T21:00:00Z,2026-10-12T02:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
3592,6230465,Bagdol,um003,1174.0,particles/cm³,2026-10-11T22:00:00Z,2026-10-12T03:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
3593,6230465,Bagdol,um003,1218.0,particles/cm³,2026-10-11T23:00:00Z,2026-10-12T04:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient
3594,6230465,Bagdol,um003,1276.0,particles/cm³,2026-10-12T00:00:00Z,2026-10-12T05:45:00+05:45,Asia/Kathmandu,27.671706,85.301619,KIAS,AirGradient